/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Persona
 * Id: 5c472aff-38b6-43b1-b234-dd256d184690
 * Codename: persona
 */
export type Persona =
  | 'luke__lead_dev_'
  | 'casey__content_strategist_'
  | 'alex__architect___user_persona_'
  | 'todd__technical_writer___user_persona_'
  | 'stacy__content_strategist___user_persona_'
  | 'connie__copywriter___user_persona_'
  | 'dave__in_house_developer_persona_'
  | 'will__agency_developer_persona_';
