/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Position category
 * Id: aa89c4b2-ec18-403c-8a7b-7523a332f8e2
 * Codename: position_category
 */
export type PositionCategory =
  | 'customer_success'
  | 'engineering'
  | 'finance'
  | 'hr_administration'
  | 'management'
  | 'marketing'
  | 'product'
  | 'revenue_operations'
  | 'sales'
  | 'ux';
