/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Region
 * Id: fedb56cb-5f6a-4780-b2fe-289ac6f2ad4f
 * Codename: regions
 */
export type Regions = 'americas' | 'asia' | 'europe' | 'australia_and_oceania';
