/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Release projects
 * Id: 45c50f4b-5e32-4332-ae05-f2abaa8c24b5
 * Codename: release_projects
 */
export type ReleaseProjects = 'rebranding' | 'product_update';
