import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Client Action - Open FAQ
 * Id: 02b75e3a-e757-4bd6-a7d1-6fd8e5d33de0
 * Codename: client_action___open_faq
 */
export type ClientActionOpenFaqModel = IContentItem<{
  /**
   * FAQ ID (text)
   * Required: false
   * Id: a257ca9b-887d-1c49-89f8-0ed9e284c44e
   * Codename: faq_id
   *
   * Client ID (Anchor without #) of FAQ to open
   */
  faqId: Elements.TextElement;
}>;
