import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Compare Kontent with X
 * Id: 90332bf5-3f17-47e4-9cb6-c67ae578b0c7
 * Codename: compare_kontent_with_x
 */
export type CompareKontentWithXModel = IContentItem<{
  /**
   * Text (rich_text)
   * Required: false
   * Id: ac3e382e-8f7b-4f97-8d19-6721135d618d
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * Tick icon (asset)
   * Required: false
   * Id: 082bc187-d692-4de8-81ac-44bf4fbfcab9
   * Codename: tick_icon
   */
  tickIcon: Elements.AssetsElement;

  /**
   * Cross icon (asset)
   * Required: false
   * Id: 3769c948-c3aa-47c9-985e-6e011c45b294
   * Codename: cross_icon
   */
  crossIcon: Elements.AssetsElement;

  /**
   * Selector (multiple_choice)
   * Required: true
   * Id: d5ffc07f-cbca-4dbc-9ef4-c7bea5440e0e
   * Codename: selector
   */
  selector: Elements.MultipleChoiceElement;
}>;
