import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { HeroKK } from '../content-type-snippets/hero_kk';
import { ContactUsKkCardModel } from './ContactUsKkCardModel';
import { OfficeModel } from './OfficeModel';
import { NewsletterSubscriptionModel } from './NewsletterSubscriptionModel';
import { Metadata } from '../content-type-snippets/metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Contact Us KK
 * Id: e5dd5073-b94f-4a53-a45e-de6a8443927c
 * Codename: contact_us_kk
 */
export type ContactUsKkModel = IContentItem<{
  /**
   * Cards (modular_content)
   * Required: false
   * Id: c6e7b5bc-757d-4784-a345-8c55b2eddf22
   * Codename: cards
   */
  cards: Elements.LinkedItemsElement<ContactUsKkCardModel>;

  /**
   * Heading (text)
   * Required: false
   * Id: bcdf2651-bd90-45fb-b2be-08c8f3c7228a
   * Codename: offices_heading
   */
  officesHeading: Elements.TextElement;

  /**
   * Offices (modular_content)
   * Required: false
   * Id: f3c4b7a9-cb21-4c5c-ad48-df7796bc6f86
   * Codename: offices
   */
  offices: Elements.LinkedItemsElement<OfficeModel>;

  /**
   * CTA Banner (modular_content)
   * Required: false
   * Id: 685c9ac1-aec7-4766-901c-45fa34d4b55c
   * Codename: cta_banner
   */
  ctaBanner: Elements.LinkedItemsElement<NewsletterSubscriptionModel>;
}> &
  HeroKK &
  Metadata;
