import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Content piece
 * Id: 03409c7b-6519-46a2-a5ee-7483a8e6f24f
 * Codename: content_piece
 */
export type ContentPieceModel = IContentItem<{
  /**
   * Heading (rich_text)
   * Required: false
   * Id: d8b14b04-b542-487e-8910-b7b7c4850b6a
   * Codename: heading
   */
  heading: Elements.RichTextElement;

  /**
   * Text (rich_text)
   * Required: false
   * Id: a8c5146c-35b8-40c9-a233-32e6ed75781f
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * Link text (text)
   * Required: false
   * Id: 8791673f-1ccb-4ad5-a460-3fb9c427ac1b
   * Codename: link_text
   */
  linkText: Elements.TextElement;

  /**
   * Link URL (text)
   * Required: false
   * Id: d69ad875-c474-4fb9-9c39-1ed166e731e6
   * Codename: link_url
   */
  linkUrl: Elements.TextElement;

  /**
   * Image (asset)
   * Required: false
   * Id: 5e13279c-6be8-477b-9358-d44024045a00
   * Codename: image
   */
  image: Elements.AssetsElement;

  /**
   * Coming soon (multiple_choice)
   * Required: false
   * Id: b665918e-0dec-4f2c-bd24-cf62e007fb96
   * Codename: coming_soon
   */
  comingSoon: Elements.MultipleChoiceElement;
}>;
