import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Content Item - HTML Source
 * Id: 0c4372d4-4846-40b6-bdf9-dde98528f80f
 * Codename: content_item___html_source
 */
export type ContentItemHtmlSourceModel = IContentItem<{
  /**
   * HTML Code (text)
   * Required: false
   * Id: 820b38eb-aa8d-a379-30f7-dc08c1d32a94
   * Codename: html_code
   */
  htmlCode: Elements.TextElement;
}>;
