import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Country
 * Id: 3b8c7eec-3848-4cb8-ac6f-897864272088
 * Codename: country
 */
export type CountryModel = IContentItem<{
  /**
   * Name (text)
   * Required: false
   * Id: 5dc9a0fa-6f82-82ed-5c4e-2a1cda31d41b
   * Codename: name
   *
   * Name of country
   */
  name: Elements.TextElement;
}>;
