import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { HeroKK } from '../content-type-snippets/hero_kk';
import { ModularItemCardElementModel } from './ModularItemCardElementModel';
import { ListItemModel } from './ListItemModel';
import { TestimonialModel } from './TestimonialModel';
import { RichTestimonialModel } from './RichTestimonialModel';
import { ContentItemCodeModel } from './ContentItemCodeModel';
import { CtaBannerComponentModel } from './CtaBannerComponentModel';
import { Metadata } from '../content-type-snippets/metadata';
import { SitemapMetadata } from '../content-type-snippets/sitemap_metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * .NET Page
 * Id: 5ffd3334-b906-45d2-aba8-8d69b51fcb48
 * Codename: dotnet_page
 */
export type DotnetPageModel = IContentItem<{
  /**
   * Heading (text)
   * Required: false
   * Id: db182225-170d-4567-9e04-5a83dab80971
   * Codename: heading_support
   */
  headingSupport: Elements.TextElement;

  /**
   * Cards (modular_content)
   * Required: false
   * Id: 6b65781d-7595-4ea4-8adb-cfaf9a3b7d73
   * Codename: cards_support
   */
  cardsSupport: Elements.LinkedItemsElement<ModularItemCardElementModel>;

  /**
   * Heading (text)
   * Required: false
   * Id: ca55fb1c-d590-4e2c-8889-7fab6fd33ee2
   * Codename: heading_statiq
   */
  headingStatiq: Elements.TextElement;

  /**
   * Statiq Card (modular_content)
   * Required: false
   * Id: 8df83f23-ea0d-423c-b5b2-162804d5e0e5
   * Codename: statiq_card
   */
  statiqCard: Elements.LinkedItemsElement<ModularItemCardElementModel>;

  /**
   * Heading (text)
   * Required: false
   * Id: 25f8ffd1-2788-492b-953b-fc99253d4405
   * Codename: heading_nuget
   */
  headingNuget: Elements.TextElement;

  /**
   * Logo (asset)
   * Required: false
   * Id: d1c4c420-dca5-4450-b873-1e467ceddcd7
   * Codename: logo_nuget
   */
  logoNuget: Elements.AssetsElement;

  /**
   * Simple Cards (modular_content)
   * Required: false
   * Id: c1f77da8-c712-48d7-ac19-edf11cbf8201
   * Codename: cards_nuget
   */
  cardsNuget: Elements.LinkedItemsElement<ModularItemCardElementModel>;

  /**
   * Heading (text)
   * Required: false
   * Id: e13e195d-d8dd-4d02-8235-fd4dbf52d8c0
   * Codename: heading_features
   */
  headingFeatures: Elements.TextElement;

  /**
   * List Item (modular_content)
   * Required: false
   * Id: bab58835-0a84-414a-9ba7-db85b1c67896
   * Codename: list_item
   */
  listItem: Elements.LinkedItemsElement<ListItemModel>;

  /**
   * Testimonial (modular_content)
   * Required: false
   * Id: 77707081-5398-41cc-94ad-62500184dc2c
   * Codename: testimonial
   */
  testimonial: Elements.LinkedItemsElement<
    TestimonialModel | RichTestimonialModel
  >;

  /**
   * Heading (text)
   * Required: false
   * Id: b425a4af-748c-435f-b0cc-0e506eb34761
   * Codename: heading_end
   */
  headingEnd: Elements.TextElement;

  /**
   * Text (rich_text)
   * Required: false
   * Id: 94a4963b-1a03-4afe-9eaf-158add017f10
   * Codename: text_end
   */
  textEnd: Elements.RichTextElement;

  /**
   * Support doesn't end here cards (modular_content)
   * Required: false
   * Id: 85c7b827-0feb-4694-ae81-5b050df9f548
   * Codename: cards_end
   */
  cardsEnd: Elements.LinkedItemsElement<ModularItemCardElementModel>;

  /**
   * Heading (text)
   * Required: false
   * Id: 40af3736-7840-42c9-b6a8-f517ead791ce
   * Codename: heading_get_started
   */
  headingGetStarted: Elements.TextElement;

  /**
   * Code (modular_content)
   * Required: false
   * Id: 9b347c2f-eb0d-44ff-9c6f-926bea25bf76
   * Codename: code
   */
  code: Elements.LinkedItemsElement<ContentItemCodeModel>;

  /**
   * CTA Banner (modular_content)
   * Required: false
   * Id: 2e294a99-df2b-40b7-811c-70357f1c3d8e
   * Codename: cta_banner
   */
  ctaBanner: Elements.LinkedItemsElement<CtaBannerComponentModel>;
}> &
  HeroKK &
  Metadata &
  SitemapMetadata;
