import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Floating menu item
 * Id: 532e5d77-e128-496e-825c-b846ce065c91
 * Codename: floating_menu_item
 */
export type FloatingMenuItemModel = IContentItem<{
  /**
   * Text (text)
   * Required: false
   * Id: 0c676226-6dc9-4664-a04d-fd489cd205e4
   * Codename: text
   */
  text: Elements.TextElement;

  /**
   * Sub items (modular_content)
   * Required: false
   * Id: 7469ab09-9d60-49d8-b3b2-1e05f0ed2ced
   * Codename: sub_items
   */
  subItems: Elements.LinkedItemsElement<FloatingMenuItemModel>;
}>;
