import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { FloatingMenuItemModel } from './FloatingMenuItemModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Floating menu
 * Id: a75fe560-58f9-4706-9aa2-0c7d02c09122
 * Codename: floating_menu
 */
export type FloatingMenuModel = IContentItem<{
  /**
   * Items (modular_content)
   * Required: false
   * Id: 01f9be4c-57b7-4c45-a89d-47239f047260
   * Codename: items
   */
  items: Elements.LinkedItemsElement<FloatingMenuItemModel>;
}>;
