import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { FooterItemModel } from './FooterItemModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Footer
 * Id: 5c833d83-3287-4f94-b341-86c8768f0ea2
 * Codename: footer
 */
export type FooterModel = IContentItem<{
  /**
   * #1 section title (text)
   * Required: false
   * Id: a68c90e1-54d3-2392-9352-77c3d0df132c
   * Codename: section_title_1
   */
  sectionTitle1: Elements.TextElement;

  /**
   * #1 section items (modular_content)
   * Required: false
   * Id: 8d518d4f-3a5e-379d-15d4-0736ff20f052
   * Codename: section_items_1
   */
  sectionItems1: Elements.LinkedItemsElement<FooterItemModel>;

  /**
   * #2 section title (text)
   * Required: false
   * Id: 69e49a36-6c56-61df-2544-8c3f019aa176
   * Codename: section_title_2
   */
  sectionTitle2: Elements.TextElement;

  /**
   * #2 section items (modular_content)
   * Required: false
   * Id: 100cd72f-5410-9b42-21e6-75b3f7413da1
   * Codename: section_items_2
   */
  sectionItems2: Elements.LinkedItemsElement<FooterItemModel>;

  /**
   * #3 section title (text)
   * Required: false
   * Id: 66ae0f81-5f8d-75a8-4d41-78c1c9cb1db4
   * Codename: section_title_3
   */
  sectionTitle3: Elements.TextElement;

  /**
   * #3 section items (modular_content)
   * Required: false
   * Id: 89c78523-9357-0393-170a-da1854f233a4
   * Codename: section_items_3
   */
  sectionItems3: Elements.LinkedItemsElement<FooterItemModel>;

  /**
   * #4 section title (text)
   * Required: false
   * Id: f1141c5d-c94d-1c6c-2654-2a5743e7b3b9
   * Codename: section_title_4
   */
  sectionTitle4: Elements.TextElement;

  /**
   * #4 section items (modular_content)
   * Required: false
   * Id: bf3edba3-2f93-a39d-ba5e-0eadab9ca4c2
   * Codename: section_items_4
   */
  sectionItems4: Elements.LinkedItemsElement<FooterItemModel>;

  /**
   * #5 section title (text)
   * Required: false
   * Id: b79915ed-51d1-6e15-5908-df7c409866b2
   * Codename: section_title_5
   */
  sectionTitle5: Elements.TextElement;

  /**
   * #5 section items (modular_content)
   * Required: false
   * Id: f11465ec-2242-3357-b4dd-5cfabc7cbb6e
   * Codename: section_items_5
   */
  sectionItems5: Elements.LinkedItemsElement<FooterItemModel>;

  /**
   * #6 section title (text)
   * Required: false
   * Id: c13cdeab-9a58-d2d7-2505-e30b21c886cc
   * Codename: section_title_6
   */
  sectionTitle6: Elements.TextElement;

  /**
   * #6 section items (modular_content)
   * Required: false
   * Id: b479851b-e7ca-76cf-ce54-6d281af8dcd7
   * Codename: section_items_6
   */
  sectionItems6: Elements.LinkedItemsElement<FooterItemModel>;

  /**
   * Copyright items (modular_content)
   * Required: false
   * Id: 64d319e7-2c74-402f-87ae-52fa0cda3356
   * Codename: copyright_items
   */
  copyrightItems: Elements.LinkedItemsElement<IContentItem>;

  /**
   * Social media title (text)
   * Required: false
   * Id: 0b34fe7f-3866-6d8b-def2-31de10f74bb4
   * Codename: social_media_title
   */
  socialMediaTitle: Elements.TextElement;

  /**
   * Newsletter title (text)
   * Required: false
   * Id: a26cc812-d8dd-13ed-2cf6-61fe2e58fc37
   * Codename: newsletter_title
   */
  newsletterTitle: Elements.TextElement;

  /**
   * Newsletter description (text)
   * Required: false
   * Id: 02948dfb-1d03-c169-6bf1-a2e6cdb5a10c
   * Codename: newsletter_description
   */
  newsletterDescription: Elements.TextElement;

  /**
   * Newsletter placeholder (text)
   * Required: false
   * Id: 8743d973-125d-7aab-b426-7666ccd13e6f
   * Codename: newsletter_placeholder
   */
  newsletterPlaceholder: Elements.TextElement;
}>;
