import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { HeadlessCmsSurveyQuestionModel } from './HeadlessCmsSurveyQuestionModel';
import { SharedContentModel } from './SharedContentModel';
import { SitemapMetadata } from '../content-type-snippets/sitemap_metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Headless CMS Survey landing page
 * Id: 9db1981f-4402-4617-ae92-a11afbb3c3b8
 * Codename: headless_cms_survey_landing_page
 */
export type HeadlessCmsSurveyLandingPageModel = IContentItem<{
  /**
   * Main title first part (text)
   * Required: false
   * Id: b890f981-e1da-4f10-a746-0e5ae258d906
   * Codename: main_title_first_part
   */
  mainTitleFirstPart: Elements.TextElement;

  /**
   * Main title second part (text)
   * Required: false
   * Id: 6ec48609-dc11-4a93-a820-767122c06c34
   * Codename: main_title_second_part
   */
  mainTitleSecondPart: Elements.TextElement;

  /**
   * Main subtitle (text)
   * Required: false
   * Id: debcd2b6-4dba-4639-a4d9-d05225528293
   * Codename: main_subtitle
   */
  mainSubtitle: Elements.TextElement;

  /**
   * Questions (modular_content)
   * Required: false
   * Id: 213782d6-59f6-4a80-ba79-2132ea37fb7f
   * Codename: questions
   */
  questions: Elements.LinkedItemsElement<HeadlessCmsSurveyQuestionModel>;

  /**
   * Download section title (text)
   * Required: false
   * Id: f834475a-68aa-4fbe-9b46-069608892739
   * Codename: download_section_title
   */
  downloadSectionTitle: Elements.TextElement;

  /**
   * Download section primary CTA (modular_content)
   * Required: true
   * Id: 6e90a176-3678-4273-b1a4-dcec78d70f9f
   * Codename: download_section_primary_cta
   */
  downloadSectionPrimaryCta: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Download section secondary CTA (modular_content)
   * Required: true
   * Id: 3f522828-ed2c-4fc3-9d35-da8da166f54f
   * Codename: download_section_secondary_cta
   */
  downloadSectionSecondaryCta: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Report Thank You title (text)
   * Required: false
   * Id: 7a14fde6-1173-4bff-a93c-72dd8d1b6e67
   * Codename: report_thank_you_title
   */
  reportThankYouTitle: Elements.TextElement;

  /**
   * Presentation Thank You title (text)
   * Required: false
   * Id: 799d2c0c-6ebe-4553-aad0-8a6ca7b57506
   * Codename: presentation_thank_you_title
   */
  presentationThankYouTitle: Elements.TextElement;

  /**
   * Report Thank You text (rich_text)
   * Required: false
   * Id: 728386ce-6e01-488b-89c8-901c07a2cf45
   * Codename: report_thank_you_text
   */
  reportThankYouText: Elements.RichTextElement;

  /**
   * Presentation Thank You text (rich_text)
   * Required: false
   * Id: 794af252-915a-4a6d-84ff-c9c82a46945d
   * Codename: presentation_thank_you_text
   */
  presentationThankYouText: Elements.RichTextElement;

  /**
   * Additional info title (text)
   * Required: false
   * Id: af64d43c-cb51-4a9e-9fd8-82cb00d49523
   * Codename: additional_info_title
   */
  additionalInfoTitle: Elements.TextElement;

  /**
   * Additional info image (asset)
   * Required: false
   * Id: 592a3bbc-bc5a-43e3-8b92-0c5343187212
   * Codename: additional_info_image
   */
  additionalInfoImage: Elements.AssetsElement;

  /**
   * Additional info first paragraph (text)
   * Required: false
   * Id: fc6c7050-b54a-4481-b18a-c912d6dc51b9
   * Codename: additional_info_first_paragraph
   */
  additionalInfoFirstParagraph: Elements.TextElement;

  /**
   * Additional info first CTA (modular_content)
   * Required: false
   * Id: a8dce246-9597-4df3-b834-c47acd41e7fb
   * Codename: additional_info_first_cta
   */
  additionalInfoFirstCta: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Additional info second paragraph (text)
   * Required: false
   * Id: 51dd4b16-170c-40a7-affe-669269976417
   * Codename: additional_info_second_paragraph
   */
  additionalInfoSecondParagraph: Elements.TextElement;

  /**
   * Additional info second CTA (modular_content)
   * Required: false
   * Id: f68ae110-e69e-4d11-9f1a-d8530d058460
   * Codename: additional_info_second_cta
   */
  additionalInfoSecondCta: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Report PDF (asset)
   * Required: false
   * Id: e1472898-ec0a-4590-bbc1-32eeaefcc18d
   * Codename: report_pdf
   */
  reportPdf: Elements.AssetsElement;

  /**
   * Report PPT (asset)
   * Required: false
   * Id: 3a7d8e47-81ae-4ec8-9081-25eb4c1655a7
   * Codename: report_ppt
   */
  reportPpt: Elements.AssetsElement;

  /**
   * Open Graph Image (asset)
   * Required: false
   * Id: b8cb54da-4ff5-4b86-ab4e-ccd196d1e52f
   * Codename: open_graph_image
   */
  openGraphImage: Elements.AssetsElement;
}> &
  SitemapMetadata;
