import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { ReleaseProjects } from '../taxonomies/release_projects';
import { HeroKK } from '../content-type-snippets/hero_kk';
import { SharedContentModel } from './SharedContentModel';
import { ListItemModel } from './ListItemModel';
import { CtaBannerComponentModel } from './CtaBannerComponentModel';
import { TestimonialModel } from './TestimonialModel';
import { RichTestimonialModel } from './RichTestimonialModel';
import { ResourceLinkModel } from './ResourceLinkModel';
import { Metadata } from '../content-type-snippets/metadata';
import { SitemapMetadata } from '../content-type-snippets/sitemap_metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Integration
 * Id: fd924902-21f5-4d94-bc35-6633085c203d
 * Codename: integration
 */
export type IntegrationModel = IContentItem<{
  /**
   * Logo (asset)
   * Required: true
   * Id: 2b668919-c726-445a-af10-bbcd06e11185
   * Codename: logo
   */
  logo: Elements.AssetsElement;

  /**
   * Logo alternative (asset)
   * Required: false
   * Id: cfe80f9f-3b27-42dc-9dc2-a79d05974f9f
   * Codename: logo_alternative
   */
  logoAlternative: Elements.AssetsElement;

  /**
   * Name (text)
   * Required: true
   * Id: 366dcf63-a78d-4668-af19-98d898e3913a
   * Codename: name
   */
  name: Elements.TextElement;

  /**
   * Description (rich_text)
   * Required: true
   * Id: fea3696c-5130-49e5-9433-2da1b65f5afb
   * Codename: description
   */
  description: Elements.RichTextElement;

  /**
   * Has dedicated subpage (multiple_choice)
   * Required: false
   * Id: 70cdaa96-6cbd-46c9-b4d3-2287ad1647d5
   * Codename: has_subpage
   *
   * Check the field if you want the integration to have its dedicated subpage /integrations/* and fill in the details in the "Detail" tab
   */
  hasSubpage: Elements.MultipleChoiceElement;

  /**
   * Category (multiple_choice)
   * Required: true
   * Id: d3cf3557-db2c-46e5-8525-01e6ffdf3cf1
   * Codename: category
   */
  category: Elements.MultipleChoiceElement;

  /**
   * Type (multiple_choice)
   * Required: false
   * Id: d87a805f-6f06-41e1-bfc1-cc585c0a74de
   * Codename: type
   */
  type: Elements.MultipleChoiceElement;

  /**
   * IsComingSoon (multiple_choice)
   * Required: false
   * Id: c00c82f3-0233-4b31-ba02-e3ddebc27162
   * Codename: iscomingsoon
   */
  iscomingsoon: Elements.MultipleChoiceElement;

  /**
   * Release projects (taxonomy)
   * Required: false
   * Id: 6e471da3-b571-4cd1-9b17-a85445084e0a
   * Codename: release_projects
   */
  releaseProjects: Elements.TaxonomyElement<ReleaseProjects>;

  /**
   * URL Slug (url_slug)
   * Required: true
   * Id: 193ec5e2-17f6-4439-8501-4e92b740d1ee
   * Codename: url_slug
   */
  urlSlug: Elements.UrlSlugElement;

  /**
   * Optional Hero CTA Button (modular_content)
   * Required: false
   * Id: b94ec392-f8b1-40c1-aa35-c7303519851f
   * Codename: hero_cta_button
   */
  heroCtaButton: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Video section heading (text)
   * Required: false
   * Id: 85f4d7be-473f-4489-a456-527302b22fb1
   * Codename: video_section_heading
   */
  videoSectionHeading: Elements.TextElement;

  /**
   * Video section text (rich_text)
   * Required: false
   * Id: d2e667f1-4cfb-42bb-ae53-ea49b3bfdbf0
   * Codename: video_section_text
   */
  videoSectionText: Elements.RichTextElement;

  /**
   * YouTube Poster (asset)
   * Required: false
   * Id: 902f3f4e-035b-4778-ab85-481bfb85b595
   * Codename: youtube_poster
   */
  youtubePoster: Elements.AssetsElement;

  /**
   * YouTube Embed ID (text)
   * Required: false
   * Id: ff989ab3-37be-4642-807b-bdb111d9bd39
   * Codename: video_id
   *
   * e.g. ZHfgKcRQRko
   */
  videoId: Elements.TextElement;

  /**
   * Fallback Video Image (asset)
   * Required: false
   * Id: 1f6f03ca-270e-4cee-9b5a-cc8836e6c82d
   * Codename: fallback_image
   *
   * If there is no YouTube ID, the page will use this image. Please make sure that you use EITHER the Image or the Video. Make sure to fill in the image description as well.
   */
  fallbackImage: Elements.AssetsElement;

  /**
   * Features Image (asset)
   * Required: false
   * Id: 9e0003b0-fd6c-4879-83fb-d44dbbdcae78
   * Codename: features_image
   *
   * Make sure to fill in the image description as well
   */
  featuresImage: Elements.AssetsElement;

  /**
   * Features (modular_content)
   * Required: false
   * Id: bd17914d-0603-4136-8c75-0c14f7864a13
   * Codename: features
   */
  features: Elements.LinkedItemsElement<ListItemModel>;

  /**
   * Optional Features CTA Button (modular_content)
   * Required: false
   * Id: a261804a-5d4f-4751-a28a-d2cb29907341
   * Codename: features_cta_button
   */
  featuresCtaButton: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * CTA Banner (modular_content)
   * Required: false
   * Id: b11960f7-1d7e-4d51-b097-fbcca66e6c16
   * Codename: cta_banner
   */
  ctaBanner: Elements.LinkedItemsElement<CtaBannerComponentModel>;

  /**
   * Testimonial (modular_content)
   * Required: false
   * Id: 0c6ec8d6-feb7-41f0-89bc-eeb641057236
   * Codename: testimonial
   */
  testimonial: Elements.LinkedItemsElement<
    TestimonialModel | RichTestimonialModel
  >;

  /**
   * Resources heading (text)
   * Required: false
   * Id: 306af960-d651-4851-b933-c9b874d93c9a
   * Codename: resources_heading
   */
  resourcesHeading: Elements.TextElement;

  /**
   * Related resources (modular_content)
   * Required: false
   * Id: f3ecdfbf-66d1-4f01-a089-4c207f13de59
   * Codename: related_resources
   */
  relatedResources: Elements.LinkedItemsElement<ResourceLinkModel>;
}> &
  HeroKK &
  Metadata &
  SitemapMetadata;
