import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { HeroKK } from '../content-type-snippets/hero_kk';
import { ContentItemYoutubeVideoModel } from './ContentItemYoutubeVideoModel';
import { ModularItemCardElementModel } from './ModularItemCardElementModel';
import { CtaBannerComponentModel } from './CtaBannerComponentModel';
import { Metadata } from '../content-type-snippets/metadata';
import { SitemapMetadata } from '../content-type-snippets/sitemap_metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * JAMstack Hub
 * Id: b8dae60d-ce8c-45b2-81cb-01a4335aa455
 * Codename: jamstack_hub
 */
export type JamstackHubModel = IContentItem<{
  /**
   * Video (modular_content)
   * Required: false
   * Id: 38d88993-077b-4759-9a1a-70dc3adb362e
   * Codename: video
   */
  video: Elements.LinkedItemsElement<ContentItemYoutubeVideoModel>;

  /**
   * Resources (modular_content)
   * Required: false
   * Id: 4d845670-9e89-44fa-9839-3679a3d48c18
   * Codename: resources
   */
  resources: Elements.LinkedItemsElement<ModularItemCardElementModel>;

  /**
   * CTA Banner (modular_content)
   * Required: false
   * Id: df5f8198-7138-4a71-a41e-b00475cea670
   * Codename: cta_banner
   */
  ctaBanner: Elements.LinkedItemsElement<CtaBannerComponentModel>;
}> &
  HeroKK &
  Metadata &
  SitemapMetadata;
