import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Kontent Selling Point
 * Id: 35c2ec7b-c226-42fd-a2c9-ad7b44b46b79
 * Codename: kontent_selling_point
 */
export type KontentSellingPointModel = IContentItem<{
  /**
   * Icon (asset)
   * Required: true
   * Id: 4ae7ce99-b4bb-448e-9aa9-44d8656a619f
   * Codename: icon
   */
  icon: Elements.AssetsElement;

  /**
   * Heading (text)
   * Required: true
   * Id: 8f76c16f-4536-429f-98be-23448942f817
   * Codename: heading
   */
  heading: Elements.TextElement;

  /**
   * Text (rich_text)
   * Required: true
   * Id: 3cec110e-6c85-457f-b1fe-f153027c8839
   * Codename: text
   */
  text: Elements.RichTextElement;
}>;
