import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { SharedContentModel } from './SharedContentModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Kontent Unique Feature
 * Id: 35a7d7d3-e02f-45d2-8217-cc1e63212893
 * Codename: kontent_unique_feature
 */
export type KontentUniqueFeatureModel = IContentItem<{
  /**
   * Name (text)
   * Required: true
   * Id: 94054a21-df45-41cd-99ae-664db2c6e8b9
   * Codename: name
   */
  name: Elements.TextElement;

  /**
   * Perex (rich_text)
   * Required: false
   * Id: b5b579b1-e1af-47ce-b7da-3cc42ca07085
   * Codename: perex
   *
   * Short description of the feature displayed on the card preview
   */
  perex: Elements.RichTextElement;

  /**
   * Card image (asset)
   * Required: true
   * Id: 6190e0b5-f62d-455f-a61c-1a866b40ba20
   * Codename: card_image
   *
   * Image displayed on the card
   */
  cardImage: Elements.AssetsElement;

  /**
   * Full text (rich_text)
   * Required: false
   * Id: 03eaedf0-3ab8-44c8-b8f3-c88903f33e29
   * Codename: full_text
   *
   * Full text of the feature
   */
  fullText: Elements.RichTextElement;

  /**
   * Button (modular_content)
   * Required: false
   * Id: 3223b675-b3e3-43d6-8a5e-09bf419d4c49
   * Codename: button
   *
   * Button with a link to a dedicated page of the feature
   */
  button: Elements.LinkedItemsElement<SharedContentModel>;
}>;
