import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Main menu item
 * Id: 496f3188-7d49-44f7-a32e-a38c02f7c2d8
 * Codename: main_menu_item
 */
export type MainMenuItemModel = IContentItem<{
  /**
   * Title (text)
   * Required: false
   * Id: fed941cb-0be2-3e02-c41c-a66b196c5d36
   * Codename: title
   *
   * Text which will be used in menu
   */
  title: Elements.TextElement;

  /**
   * URL (text)
   * Required: false
   * Id: 74b3b23b-9d4a-d97a-70f8-f96ac91debd3
   * Codename: url
   *
   * Use short URL (i.e. /blog) for page on our web, use the full URL for external URLs (i.e. https://developer.kenticocloud.com/)
   */
  url: Elements.TextElement;

  /**
   * Tracking code (text)
   * Required: false
   * Id: 7861929f-5692-7deb-f109-023e75ab2e34
   * Codename: tracking_code
   *
   * Tracking code for Google Analytics
   */
  trackingCode: Elements.TextElement;

  /**
   * Is separated (multiple_choice)
   * Required: false
   * Id: 42bdb8a1-33ed-f467-aca8-5bab732b4805
   * Codename: is_separated
   *
   * If set to "yes", there will be separator line displayed above menu item
   */
  isSeparated: Elements.MultipleChoiceElement;
}>;
