import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { HeroKK } from '../content-type-snippets/hero_kk';
import { PartnerSpaceSectionModel } from './PartnerSpaceSectionModel';
import { PartnerPlanModel } from './PartnerPlanModel';
import { PartnerSpaceContactsModel } from './PartnerSpaceContactsModel';
import { Metadata } from '../content-type-snippets/metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Partner space
 * Id: 7afe060f-d89f-4921-9480-b8d5eff4185e
 * Codename: partner_space
 */
export type PartnerSpaceModel = IContentItem<{
  /**
   * Heading (text)
   * Required: false
   * Id: a0ad9d75-a9ac-4a7c-a5be-da984225f21b
   * Codename: heading_resources
   */
  headingResources: Elements.TextElement;

  /**
   * Resources (modular_content)
   * Required: false
   * Id: 59b49bd8-bc0b-4796-9ffe-df46c146df17
   * Codename: resources
   */
  resources: Elements.LinkedItemsElement<PartnerSpaceSectionModel>;

  /**
   * Onboarding journey (rich_text)
   * Required: false
   * Id: 16321b8b-6ff1-4b31-be28-2316eec53f91
   * Codename: onboarding_journey
   */
  onboardingJourney: Elements.RichTextElement;

  /**
   * Heading (text)
   * Required: false
   * Id: 31d00c98-ed5d-401e-ad71-d5ba6c270685
   * Codename: heading_levels
   */
  headingLevels: Elements.TextElement;

  /**
   * Partner levels (modular_content)
   * Required: false
   * Id: c9a2c73f-0886-40eb-93ee-18b3f25fa5e8
   * Codename: partner_levels
   */
  partnerLevels: Elements.LinkedItemsElement<PartnerPlanModel>;

  /**
   * Heading (text)
   * Required: false
   * Id: d5eec579-a82a-473d-ad95-d8918b4f2217
   * Codename: heading_contacts
   */
  headingContacts: Elements.TextElement;

  /**
   * Contacts (modular_content)
   * Required: false
   * Id: 9bd65f25-9c9e-41c0-8a55-afa26c6465bc
   * Codename: contacts
   */
  contacts: Elements.LinkedItemsElement<PartnerSpaceContactsModel>;

  /**
   * Login button text (text)
   * Required: false
   * Id: 4a79a2ac-ffa4-4397-9887-130ca00d5bc0
   * Codename: login_button_text
   */
  loginButtonText: Elements.TextElement;

  /**
   * Logout button text (text)
   * Required: false
   * Id: 59a3f854-1a77-4f74-8709-99a005a57e32
   * Codename: logout_button_text
   */
  logoutButtonText: Elements.TextElement;

  /**
   * Become partner button text (text)
   * Required: false
   * Id: 085eec74-d083-442d-a2ee-9a73044e3ca9
   * Codename: become_partner_button_text
   */
  becomePartnerButtonText: Elements.TextElement;

  /**
   * Hero headline (not authenticated) (text)
   * Required: false
   * Id: 0dbed8e5-adba-4d18-bcc7-4d23ac67cfed
   * Codename: hero_headline__not_authenticated_
   */
  heroHeadlineNotAuthenticated: Elements.TextElement;

  /**
   * Hero lead paragraph (not authenticated) (rich_text)
   * Required: false
   * Id: a4540a72-7b9b-4217-83fd-088eb1a7774d
   * Codename: hero_lead_paragraph__not_authenticated_
   */
  heroLeadParagraphNotAuthenticated: Elements.RichTextElement;

  /**
   * Hero headline (authenticated, not partner) (text)
   * Required: false
   * Id: 661f1c33-8441-423b-853f-1933be86a3fa
   * Codename: hero_headline__authenticated__not_partner_
   */
  heroHeadlineAuthenticatedNotPartner: Elements.TextElement;

  /**
   * Hero lead paragraph (authenticated, not partner) (rich_text)
   * Required: false
   * Id: 1e611fd6-d826-4bb6-a8c8-0e82b0efcf83
   * Codename: hero_lead_paragraph__authenticated__not_partner_
   */
  heroLeadParagraphAuthenticatedNotPartner: Elements.RichTextElement;
}> &
  HeroKK &
  Metadata;
