import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Partner onboarding - FAQ
 * Id: b9057e53-cd8b-4d9d-a4a6-f301f6152f6f
 * Codename: partner_onboarding___faq
 */
export type PartnerOnboardingFaqModel = IContentItem<{
  /**
   * Question (text)
   * Required: false
   * Id: 1512b61a-49aa-4f95-8973-7c572d53f81e
   * Codename: question
   */
  question: Elements.TextElement;

  /**
   * Answer (rich_text)
   * Required: false
   * Id: 28a75563-adaf-4478-bf6e-8b71d02d1db5
   * Codename: answer
   */
  answer: Elements.RichTextElement;
}>;
