import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { HeroKK } from '../content-type-snippets/hero_kk';
import { SharedContentModel } from './SharedContentModel';
import { PricingPagePlanV3Model } from './PricingPagePlanV3Model';
import { CustomerFeedbackBubbleModel } from './CustomerFeedbackBubbleModel';
import { Metadata } from '../content-type-snippets/metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Premium Support Page
 * Id: 57395342-d115-437d-93ed-2abc941c0549
 * Codename: premium_support_page
 */
export type PremiumSupportPageModel = IContentItem<{
  /**
   * CTA Button (modular_content)
   * Required: false
   * Id: c5f278e5-47e1-4cc3-9956-2931a52467e1
   * Codename: cta_button
   */
  ctaButton: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Plans (modular_content)
   * Required: false
   * Id: 2e1dea43-554c-4957-99fd-5564829978cf
   * Codename: plans
   */
  plans: Elements.LinkedItemsElement<PricingPagePlanV3Model>;

  /**
   * Feature 1 (text)
   * Required: false
   * Id: 720489ff-6987-44bc-a578-39eed0de8da2
   * Codename: feature_1
   */
  feature1: Elements.TextElement;

  /**
   * Feature 2 (text)
   * Required: false
   * Id: 55467e57-c14b-4222-afa7-aefcd576ce0e
   * Codename: feature_2
   */
  feature2: Elements.TextElement;

  /**
   * Heading (text)
   * Required: false
   * Id: ab2517fa-a8f5-4366-bff6-6dda7fb9c1b2
   * Codename: heading
   */
  heading: Elements.TextElement;

  /**
   * Feedback (modular_content)
   * Required: false
   * Id: 1fc5942d-0ec2-4710-9a2e-8cacf5a8dbd7
   * Codename: feedback
   */
  feedback: Elements.LinkedItemsElement<CustomerFeedbackBubbleModel>;

  /**
   * Heading 1 (text)
   * Required: false
   * Id: 03d7035c-0723-40ae-b7ba-20f54007908f
   * Codename: heading_1
   */
  heading1: Elements.TextElement;

  /**
   * Image 1 (asset)
   * Required: false
   * Id: 64536d79-de4f-4b05-9543-ea41257c8f30
   * Codename: image_1
   */
  image1: Elements.AssetsElement;

  /**
   * Heading 2 (text)
   * Required: false
   * Id: 5b60d2b2-d0bf-466c-9bd0-a57ef47bf584
   * Codename: heading_2
   */
  heading2: Elements.TextElement;

  /**
   * Image 2 (asset)
   * Required: false
   * Id: 212b2e4d-9681-4378-805b-34d2fb2a4d03
   * Codename: image_2
   */
  image2: Elements.AssetsElement;
}> &
  HeroKK &
  Metadata;
