import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Pricing page - features category v3
 * Id: 39005603-9194-4e8c-9683-5c2d5bc2b586
 * Codename: pricing_page___features_category_v3
 */
export type PricingPageFeaturesCategoryV3Model = IContentItem<{
  /**
   * Title (text)
   * Required: false
   * Id: 766c6bfb-16fb-4dc5-81db-b92dd8f4220b
   * Codename: title
   */
  title: Elements.TextElement;
}>;
