import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { PricingPlanCardComponentModel } from './PricingPlanCardComponentModel';
import { CtaBannerComponentModel } from './CtaBannerComponentModel';
import { PricingPageFeatureV3Model } from './PricingPageFeatureV3Model';
import { PricingPageFeaturesCategoryV3Model } from './PricingPageFeaturesCategoryV3Model';
import { TestimonialModel } from './TestimonialModel';
import { UmlpElementTextImageBlockModel } from './UmlpElementTextImageBlockModel';
import { LogoModel } from './LogoModel';
import { PricingPageFaqCategoryModel } from './PricingPageFaqCategoryModel';
import { Metadata } from '../content-type-snippets/metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Pricing page
 * Id: d2560f09-4899-4faf-bd6a-677ed6954f20
 * Codename: pricing_page_v3
 */
export type PricingPageV3Model = IContentItem<{
  /**
   * Heading (rich_text)
   * Required: false
   * Id: 4c095478-d559-4058-90b2-3fa731acc68f
   * Codename: heading_plans
   */
  headingPlans: Elements.RichTextElement;

  /**
   * Subheading (text)
   * Required: false
   * Id: 6db85b63-f022-470d-8b3a-dbf0c820e3a8
   * Codename: subheading_plans
   */
  subheadingPlans: Elements.TextElement;

  /**
   * Plans (modular_content)
   * Required: true
   * Id: 38be8ed0-d3ba-491f-9067-13283e9a1e7c
   * Codename: plans
   */
  plans: Elements.LinkedItemsElement<PricingPlanCardComponentModel>;

  /**
   * Heading (rich_text)
   * Required: false
   * Id: 6d9b2c29-92d2-418c-a4c5-91bd79f4eb0b
   * Codename: heading_compare
   */
  headingCompare: Elements.RichTextElement;

  /**
   * Subheading (text)
   * Required: false
   * Id: c924f98f-b28a-41b2-a99a-905d16dbd2ac
   * Codename: subheading_compare
   */
  subheadingCompare: Elements.TextElement;

  /**
   * Developer plan CTA text (text)
   * Required: false
   * Id: baf1335a-f6e8-443d-ab82-ae6fc311f62c
   * Codename: developer_plan_cta_text
   */
  developerPlanCtaText: Elements.TextElement;

  /**
   * Developer plan banner (modular_content)
   * Required: false
   * Id: 3c7df2d8-071e-4c76-ac39-9c694ea5e721
   * Codename: developer_plan_banner
   */
  developerPlanBanner: Elements.LinkedItemsElement<CtaBannerComponentModel>;

  /**
   * Compare plans CTA text (text)
   * Required: false
   * Id: 210328e5-3e92-4ac8-a6c7-91682c84a76d
   * Codename: compare_plans_cta_text
   */
  comparePlansCtaText: Elements.TextElement;

  /**
   * Features (modular_content)
   * Required: false
   * Id: 15e93118-499f-4219-9992-93e3dfc3027c
   * Codename: features
   */
  features: Elements.LinkedItemsElement<
    PricingPageFeatureV3Model | PricingPageFeaturesCategoryV3Model
  >;

  /**
   * Tag text (text)
   * Required: false
   * Id: 40346974-e139-42be-8b90-9510f9add7d3
   * Codename: tag_text
   */
  tagText: Elements.TextElement;

  /**
   * Heading (rich_text)
   * Required: false
   * Id: fb7c87a1-8332-4f4e-85a7-95621a0d6788
   * Codename: heading_support
   */
  headingSupport: Elements.RichTextElement;

  /**
   * Text (rich_text)
   * Required: false
   * Id: 8361f4f6-e6d8-44a5-b999-7c8ebc65b1a7
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * Heading (rich_text)
   * Required: false
   * Id: f0bcce4a-ed09-40ac-b155-063bf42dc236
   * Codename: heading_testimonials
   */
  headingTestimonials: Elements.RichTextElement;

  /**
   * Testimonials (modular_content)
   * Required: false
   * Id: bb953676-b4dc-4b80-8ec0-20148d160666
   * Codename: testimonials
   */
  testimonials: Elements.LinkedItemsElement<TestimonialModel>;

  /**
   * Text image block (modular_content)
   * Required: true
   * Id: d4cebe70-f59f-4bd0-9772-2715e710f347
   * Codename: text_image_block
   */
  textImageBlock: Elements.LinkedItemsElement<UmlpElementTextImageBlockModel>;

  /**
   * Logos (modular_content)
   * Required: true
   * Id: 86788b02-2803-4828-a1ea-da4b0785042f
   * Codename: logos
   */
  logos: Elements.LinkedItemsElement<LogoModel>;

  /**
   * Heading (rich_text)
   * Required: false
   * Id: facb53a5-c74f-4325-9408-3e102f5a178a
   * Codename: heading_faqs
   */
  headingFaqs: Elements.RichTextElement;

  /**
   * FAQs (modular_content)
   * Required: false
   * Id: f0ab0f06-d396-4fe9-a5de-dc0de692a2eb
   * Codename: faqs
   */
  faqs: Elements.LinkedItemsElement<PricingPageFaqCategoryModel>;

  /**
   * CTA Banner (modular_content)
   * Required: false
   * Id: 6bd37b83-05e0-4291-a749-936149c1937a
   * Codename: cta_banner
   */
  ctaBanner: Elements.LinkedItemsElement<CtaBannerComponentModel>;
}> &
  Metadata;
