import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { PricingPageFaqModel } from './PricingPageFaqModel';
import { ReleaseProjects } from '../taxonomies/release_projects';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Pricing page - FAQ category
 * Id: 334569c0-c2ab-438d-85ef-3c128ee13f67
 * Codename: pricing_page___faq_category
 */
export type PricingPageFaqCategoryModel = IContentItem<{
  /**
   * Category name (text)
   * Required: false
   * Id: db2efed4-0c3c-2611-5ad8-e9cf72653eb0
   * Codename: category_name
   *
   * Category name is not required,  but should be specified if there is more than one FAQ category on page
   */
  categoryName: Elements.TextElement;

  /**
   * FAQs (modular_content)
   * Required: false
   * Id: 70b080fb-c930-5e2f-6e09-5cbd92177a3d
   * Codename: faqs
   */
  faqs: Elements.LinkedItemsElement<PricingPageFaqModel>;

  /**
   * Anchor (text)
   * Required: false
   * Id: 69df3672-ae4c-34a9-de9c-4d06b88748e9
   * Codename: anchor
   */
  anchor: Elements.TextElement;

  /**
   * Release projects (taxonomy)
   * Required: false
   * Id: 9155aeb0-dd02-49df-8e6b-f64a7abfc858
   * Codename: release_projects
   */
  releaseProjects: Elements.TaxonomyElement<ReleaseProjects>;
}>;
