import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { SitemapMetadata } from '../content-type-snippets/sitemap_metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Resource
 * Id: 535862ca-566f-4ad8-9fd0-4df4a848e6ba
 * Codename: resource
 */
export type ResourceModel = IContentItem<{
  /**
   * Title (text)
   * Required: true
   * Id: d2b51eeb-f261-4a9a-9a7f-003a9a47ffe8
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Type (multiple_choice)
   * Required: true
   * Id: 78a41e16-ab39-4539-ac22-268e441a50a2
   * Codename: type
   */
  type: Elements.MultipleChoiceElement;

  /**
   * URL (text)
   * Required: true
   * Id: dfcfd0b1-a218-498c-a48c-612cf92c8bc2
   * Codename: url
   */
  url: Elements.TextElement;

  /**
   * Open URL in a new tab (multiple_choice)
   * Required: false
   * Id: a8acbae8-2395-451b-912c-e9e1505e4cb3
   * Codename: open_url_in_a_new_tab
   */
  openUrlInANewTab: Elements.MultipleChoiceElement;

  /**
   * Author (text)
   * Required: false
   * Id: 98a29ef7-c404-40a7-95aa-056c02339a26
   * Codename: author
   */
  author: Elements.TextElement;

  /**
   * Publish date (date_time)
   * Required: true
   * Id: e37427e9-7bf4-4d1e-a9da-1595b1d61ea7
   * Codename: publish_date
   */
  publishDate: Elements.DateTimeElement;

  /**
   * Header image (asset)
   * Required: true
   * Id: 10886cf2-ffca-4b67-9a71-362773874934
   * Codename: header_image
   */
  headerImage: Elements.AssetsElement;

  /**
   * Is highlighted (multiple_choice)
   * Required: true
   * Id: 693e5055-bd29-4988-9c65-3b7fed92f8d9
   * Codename: is_highlighted
   */
  isHighlighted: Elements.MultipleChoiceElement;
}> &
  SitemapMetadata;
