import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { ServicesKkUnorderedListModel } from './ServicesKkUnorderedListModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Services - Service
 * Id: bf66c69b-e4f0-48f4-b5dd-078493886d03
 * Codename: services___service
 */
export type ServicesServiceModel = IContentItem<{
  /**
   * Heading (rich_text)
   * Required: false
   * Id: e15308d5-72cd-4e2a-8767-6d21e5da4bc9
   * Codename: heading
   */
  heading: Elements.RichTextElement;

  /**
   * Text (rich_text)
   * Required: false
   * Id: d67ad23e-bc63-4f55-8eab-9ba297b1c227
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * List (modular_content)
   * Required: false
   * Id: f63cc904-0d57-4b76-b63f-dfa94ca68d8c
   * Codename: list
   */
  list: Elements.LinkedItemsElement<ServicesKkUnorderedListModel>;
}>;
