import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Solutions page - Custom Product Capability
 * Id: b42a8241-0a01-47b4-8620-998ad182c1fa
 * Codename: solutions_page___custom_product_capability
 */
export type SolutionsPageCustomProductCapabilityModel = IContentItem<{
  /**
   * Title (text)
   * Required: false
   * Id: 42093dd7-a4f9-4682-823f-61ec2c5d2645
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Description (text)
   * Required: false
   * Id: fb423c3c-e0e1-4476-8874-d42bdd377f7f
   * Codename: description
   */
  description: Elements.TextElement;
}>;
