import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Time zone
 * Id: fa475e4a-f450-443d-bec2-6e0c69bdb8e4
 * Codename: time_zone
 */
export type TimeZoneModel = IContentItem<{
  /**
   * Title (text)
   * Required: false
   * Id: fed1bd7f-fb86-42f2-920e-9c1b58c70573
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Timezone database name (text)
   * Required: true
   * Id: 4050271d-350e-4078-ab6d-abb4b65420c5
   * Codename: timezone_database_name
   *
   * Timezone idetifier e.g. "America/New_York" (Full table: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
   */
  timezoneDatabaseName: Elements.TextElement;
}>;
