import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { TrialSignupStepModel } from './TrialSignupStepModel';
import { SharedContentModel } from './SharedContentModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Trial signup component
 * Id: e889277e-72cb-426e-964e-0ef6f451e7e4
 * Codename: trial_signup_component
 */
export type TrialSignupComponentModel = IContentItem<{
  /**
   * Trial headline (text)
   * Required: false
   * Id: b5d36576-7635-4340-be68-f2dbaa99d5b7
   * Codename: trial_headline
   */
  trialHeadline: Elements.TextElement;

  /**
   * Trial steps (modular_content)
   * Required: false
   * Id: 4d148a4b-cc84-4e92-b63c-6b1dd678461a
   * Codename: trial_steps
   */
  trialSteps: Elements.LinkedItemsElement<TrialSignupStepModel>;

  /**
   * Schedule demo headline (text)
   * Required: false
   * Id: 430631f6-eef7-45ea-a4ca-e6c1e0038eb2
   * Codename: schedule_demo_headline
   */
  scheduleDemoHeadline: Elements.TextElement;

  /**
   * Schedule demo button (modular_content)
   * Required: false
   * Id: 4189f9ea-3645-44c7-8faa-be0dcb4139f3
   * Codename: schedule_demo_button
   */
  scheduleDemoButton: Elements.LinkedItemsElement<SharedContentModel>;
}>;
