import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Footer Disclaimer
 * Id: eb07abe2-f085-4738-a80b-9902976d3a5b
 * Codename: umlp___footer_disclaimer
 */
export type UmlpFooterDisclaimerModel = IContentItem<{
  /**
   * Disclaimer (rich_text)
   * Required: false
   * Id: 8d900781-ddae-44ed-b3fe-04590484f6a3
   * Codename: disclaimer
   */
  disclaimer: Elements.RichTextElement;
}>;
