import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { SecurityFeatureItemModel } from './SecurityFeatureItemModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Security Feature
 * Id: efa8696c-4e61-4a82-9751-66798293b060
 * Codename: umlp_element___security_feature
 */
export type UmlpElementSecurityFeatureModel = IContentItem<{
  /**
   * Headline (rich_text)
   * Required: false
   * Id: c0a85bb7-836f-4c1a-a783-41154ef0d736
   * Codename: headline
   */
  headline: Elements.RichTextElement;

  /**
   * Lead Paragraph (rich_text)
   * Required: false
   * Id: a70e3225-30c2-445c-9d71-b554c23a8027
   * Codename: lead_paragraph
   */
  leadParagraph: Elements.RichTextElement;

  /**
   * Items (modular_content)
   * Required: false
   * Id: c284b35e-2923-4978-99f7-22a9b571c285
   * Codename: items
   */
  items: Elements.LinkedItemsElement<SecurityFeatureItemModel>;
}>;
