import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { CompareWithXTableModel } from './CompareWithXTableModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Compare table
 * Id: 6bd72187-99ca-40f4-b165-4718e5128215
 * Codename: umlp_element___compare_table
 */
export type UmlpElementCompareTableModel = IContentItem<{
  /**
   * Heading (rich_text)
   * Required: false
   * Id: 00cd158a-5706-4dcb-8792-217f7bea9d39
   * Codename: heading
   */
  heading: Elements.RichTextElement;

  /**
   * Table (modular_content)
   * Required: true
   * Id: c5c69194-2bff-4af4-8507-f81fead70588
   * Codename: table
   */
  table: Elements.LinkedItemsElement<CompareWithXTableModel>;
}>;
