import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { ComponentTimelineSliderSlideModel } from './ComponentTimelineSliderSlideModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Timeline slider
 * Id: c28a3a3e-5c02-4aad-a3d9-aff130e218cd
 * Codename: umlp_element___timeline_slider
 */
export type UmlpElementTimelineSliderModel = IContentItem<{
  /**
   * Heading (text)
   * Required: false
   * Id: d578d9f8-7259-4335-8e7f-28fbbee254b6
   * Codename: heading
   *
   * Optional section heading
   */
  heading: Elements.TextElement;

  /**
   * Slides (modular_content)
   * Required: true
   * Id: e187d1a0-e29b-4a0e-95d5-5a9b0cc2e5ac
   * Codename: slides
   *
   * Slide cards. If you need less than 4 slides, maybe reconsider whether or not this element is the best solution for your use case.
   */
  slides: Elements.LinkedItemsElement<ComponentTimelineSliderSlideModel>;
}>;
