/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Blog topics
 * Id: 8e416f31-6008-5879-3dd8-eb1f078d7ba8
 * Codename: blog_topics
 */
export type BlogTopics =
  | 'announcements'
  | 'content_management'
  | 'developers'
  | 'digital_agencies';
