/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Funnel stage
 * Id: a4985e46-a486-46ca-8f8c-366c1624acc0
 * Codename: funnel_stage
 */
export type FunnelStage =
  | 'setting_expectations'
  | 'shortlisting'
  | 'evaluation'
  | 'adoption'
  | 'retention'
  | 'cancellation';
