/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Job role
 * Id: 92f22e11-2705-422d-a835-39e08c7d7903
 * Codename: job_role
 */
export type JobRole =
  | 'marketing__general_'
  | 'business_operations__general_'
  | 'content__general_'
  | 'developer__full_stack_';
