/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Page type
 * Id: 0facc2ef-d4bb-482a-9805-076d5e07b6ca
 * Codename: page_type
 */
export type PageType = 'special' | 'landing_page' | 'resource';
