/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Product features
 * Id: 701f9a6c-40fe-475c-847d-9fb2791af9c7
 * Codename: product_features
 */
export type ProductFeatures = 'business_features' | 'it_features';
