import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Hero KK
 * Id: 7201497d-02f5-4827-9649-37042bdeb64b
 * Codename: hero_kk
 */
export type HeroKK = IContentItem<{
  /**
   * Hero headline (text)
   * Required: false
   * Id: 1ac6fd1b-468a-4236-ba5d-a31d739f62fd
   * Codename: hero_kk__hero_headline
   */
  heroKkHeroHeadline: Elements.TextElement;

  /**
   * Hero headline rich (rich_text)
   * Required: false
   * Id: 44aadeba-ff49-4d07-944a-d28e1ae38b6d
   * Codename: hero_kk__hero_headline_rich
   *
   * In case you need richtext support for the headline. Otherwise, use the standard headline
   */
  heroKkHeroHeadlineRich: Elements.RichTextElement;

  /**
   * Hero lead paragraph (rich_text)
   * Required: false
   * Id: 9518d495-81b5-46da-a03e-07793bbd0d56
   * Codename: hero_kk__hero_lead_paragraph
   *
   * Ideally max. 1 paragraph of text
   */
  heroKkHeroLeadParagraph: Elements.RichTextElement;

  /**
   * Hero image (asset)
   * Required: false
   * Id: 34846794-da2a-4615-8bc4-af67b7ee407d
   * Codename: hero_kk__hero_image
   */
  heroKkHeroImage: Elements.AssetsElement;
}>;
