import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Metadata
 * Id: 3284954e-a1fa-4be9-bc19-53a05da9b205
 * Codename: metadata
 */
export type Metadata = IContentItem<{
  /**
   * Metadata title (text)
   * Required: false
   * Id: 62d40c2b-b281-a2e8-52d2-ca0b9e6dc214
   * Codename: metadata__metadata_title
   */
  metadataMetadataTitle: Elements.TextElement;

  /**
   * Metadata description (text)
   * Required: false
   * Id: 17b40763-3aec-698c-9e34-0d1ca0a28b80
   * Codename: metadata__metadata_description
   */
  metadataMetadataDescription: Elements.TextElement;

  /**
   * Metadata image (asset)
   * Required: false
   * Id: 0b019c26-b4ea-4c27-aa2f-57df7c2974f1
   * Codename: metadata__metadata_image
   *
   * Ideally 1200px wide
   */
  metadataMetadataImage: Elements.AssetsElement;
}>;
