import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Sitemap metadata
 * Id: 4c7796e1-14f5-4122-9653-f697d6c84856
 * Codename: sitemap_metadata
 */
export type SitemapMetadata = IContentItem<{
  /**
   * Visibility (multiple_choice)
   * Required: false
   * Id: 51fb5bf3-1956-4750-9f62-db5d5b6273ba
   * Codename: sitemap_metadata__visibility
   *
   * Default value is Included.
   */
  sitemapMetadataVisibility: Elements.MultipleChoiceElement;

  /**
   * Priority (text)
   * Required: false
   * Id: 9b88c6e4-aad3-458f-adc2-daada108bad2
   * Codename: sitemap_metadata__priority
   *
   * Enter values between 0 and 1.  Example: 0.7. If not set or invalid, default value of 0.5 is going to be set.
   */
  sitemapMetadataPriority: Elements.TextElement;
}>;
