/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Project name: Kontent.ai
 * Environment: Blog post purge
 * Project Id: ced5fb45-38cb-005e-07ea-82dbfafd45cf
 */
export const collections = {};
