/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Project name: Kontent.ai
 * Environment: Industry pages
 * Project Id: 674a66a6-8af4-00e5-b304-ae93b7bf31d7
 */
export const workflows = {};
