import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { ContentBoxModel } from './ContentBoxModel';
import { CtaBannerComponentModel } from './CtaBannerComponentModel';
import { SharedContentModel } from './SharedContentModel';
import { SitemapMetadata } from '../content-type-snippets/sitemap_metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * About us
 * Id: 892eafb9-6183-4fbf-b4fc-91d46fac710a
 * Codename: about_us
 */
export type AboutUsModel = IContentItem<{
  /**
   * Headline (text)
   * Required: false
   * Id: 7358f677-6b58-6fc2-6f77-7931cd0f0029
   * Codename: headline
   */
  headline: Elements.TextElement;

  /**
   * Subheadline (text)
   * Required: false
   * Id: 534c23ca-8bfa-e3bb-a7b2-eaddfdd7fd94
   * Codename: subheadline
   */
  subheadline: Elements.TextElement;

  /**
   * Data points (modular_content)
   * Required: false
   * Id: d49d7ad1-2162-8b2e-0cc2-3184904136ce
   * Codename: data_points
   */
  dataPoints: Elements.LinkedItemsElement<ContentBoxModel>;

  /**
   * Image (asset)
   * Required: false
   * Id: afe218ff-98e8-2486-3630-bcdfcdb828aa
   * Codename: image
   */
  image: Elements.AssetsElement;

  /**
   * Image ALT (text)
   * Required: false
   * Id: 6c8f87e6-3ef9-434c-21c2-846534b562a1
   * Codename: image_alt
   */
  imageAlt: Elements.TextElement;

  /**
   * Paragraph 1 - heading (text)
   * Required: false
   * Id: e37f143f-4fc7-4bb2-8f30-5605de28526d
   * Codename: paragraph_1___heading
   */
  paragraph1Heading: Elements.TextElement;

  /**
   * Paragraph 1 (rich_text)
   * Required: false
   * Id: 0f17632a-9320-6421-8cd5-dff576befd08
   * Codename: paragraph_1
   */
  paragraph1: Elements.RichTextElement;

  /**
   * Paragraph 2 - heading (text)
   * Required: false
   * Id: eaf3bf16-fd0f-4240-81e6-07108df2e6a7
   * Codename: paragraph_2___heading
   */
  paragraph2Heading: Elements.TextElement;

  /**
   * Paragraph 2 (rich_text)
   * Required: false
   * Id: 37397c85-8b42-0e5c-b4ab-d933ee589464
   * Codename: paragraph_2
   */
  paragraph2: Elements.RichTextElement;

  /**
   * Paragraph 3 - heading (text)
   * Required: false
   * Id: d675ac9a-58f0-482e-9216-4e74ae7fa9fe
   * Codename: paragraph_3___heading
   */
  paragraph3Heading: Elements.TextElement;

  /**
   * Paragraph 3 (rich_text)
   * Required: false
   * Id: eddfcb58-fd9a-c7fe-a74b-14cbfea00aa7
   * Codename: paragraph_3
   */
  paragraph3: Elements.RichTextElement;

  /**
   * CTA banner (modular_content)
   * Required: true
   * Id: 43f4472c-e8fe-4428-ba52-3900587edefa
   * Codename: cta_banner
   */
  ctaBanner: Elements.LinkedItemsElement<CtaBannerComponentModel>;

  /**
   * CTA (rich_text)
   * Required: false
   * Id: db46f0ec-865d-b12d-321e-d8cbfbc10e96
   * Codename: cta
   */
  cta: Elements.RichTextElement;

  /**
   * Button text (text)
   * Required: false
   * Id: 42762f2e-4d51-3c10-8d67-defc0e82fe99
   * Codename: button_text
   */
  buttonText: Elements.TextElement;

  /**
   * Button (modular_content)
   * Required: false
   * Id: b6676a91-4cc8-b401-2767-a11aafb55529
   * Codename: button
   */
  button: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Note (text)
   * Required: false
   * Id: c420569a-c205-9772-253a-395411f22b63
   * Codename: note
   */
  note: Elements.TextElement;

  /**
   * Note link (text)
   * Required: false
   * Id: 14144335-6398-1877-4984-e81585a2a0b3
   * Codename: note_link
   */
  noteLink: Elements.TextElement;

  /**
   * Metadata title (text)
   * Required: false
   * Id: 92c32851-a21e-4fcd-f96b-7e1cab2a0b33
   * Codename: metadata_title
   */
  metadataTitle: Elements.TextElement;

  /**
   * Metadata description (text)
   * Required: false
   * Id: 11a71d3f-1bcb-2a70-84e3-e6efe70c4905
   * Codename: metadata_description
   */
  metadataDescription: Elements.TextElement;

  /**
   * Metadata image (asset)
   * Required: true
   * Id: 73f82c19-6662-463b-98dd-2c1ccb986a57
   * Codename: metadata_image
   */
  metadataImage: Elements.AssetsElement;
}> &
  SitemapMetadata;
