import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { UmlpModel } from './UmlpModel';
import { AbTestVariantModel } from './AbTestVariantModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * AB test
 * Id: 0908876a-5c20-4fa1-814d-b3771f4e2bda
 * Codename: ab_test
 */
export type AbTestModel = IContentItem<{
  /**
   * UMLP page (modular_content)
   * Required: true
   * Id: 7b90b128-f58f-49e3-bdf9-677122812fd3
   * Codename: umlp_page
   *
   * The page you want to test
   */
  umlpPage: Elements.LinkedItemsElement<UmlpModel>;

  /**
   * Variants (modular_content)
   * Required: true
   * Id: 529092fa-3820-443c-bbba-479147adf390
   * Codename: variants
   *
   * Alternative tested content variants
   */
  variants: Elements.LinkedItemsElement<AbTestVariantModel>;

  /**
   * Google Optimize ID (text)
   * Required: true
   * Id: e20f459e-3cf7-4ba8-bdf2-a6d95eb63e00
   * Codename: google_optimize_id
   */
  googleOptimizeId: Elements.TextElement;

  /**
   * Start date (date_time)
   * Required: true
   * Id: da50094a-9061-451c-a101-fb3c0050604f
   * Codename: start_date
   */
  startDate: Elements.DateTimeElement;

  /**
   * End date (date_time)
   * Required: true
   * Id: ff5ac838-4651-49b0-b02f-6900c38b0647
   * Codename: end_date
   */
  endDate: Elements.DateTimeElement;
}>;
