import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { CountryAndStateModel } from './CountryAndStateModel';
import { CountryModel } from './CountryModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Address
 * Id: 321692a1-c258-4b91-8d9e-86f891e6339b
 * Codename: address
 */
export type AddressModel = IContentItem<{
  /**
   * Name (text)
   * Required: true
   * Id: 89e68b66-7e17-4a30-a406-5c648471116f
   * Codename: name
   *
   * Company name, e.g. Kentico software s.ro.
   */
  name: Elements.TextElement;

  /**
   * Street (text)
   * Required: true
   * Id: 60f106d7-c7dc-45ef-aa47-7d58d8ab1e0b
   * Codename: street
   */
  street: Elements.TextElement;

  /**
   * Building (text)
   * Required: false
   * Id: 1cdebdc5-24ec-4fc3-9fe6-26745a81addb
   * Codename: building
   *
   * If street number is not enough and we want to be more specific e.g. Suite 2G, Chrystler building etc.
   */
  building: Elements.TextElement;

  /**
   * Floor (text)
   * Required: false
   * Id: e9b29294-a327-4f28-9ca9-06d70f657435
   * Codename: floor
   *
   * Floor or other building specific information
   */
  floor: Elements.TextElement;

  /**
   * Postal code (text)
   * Required: true
   * Id: c5f17c87-ca50-454b-a882-02fd5475c613
   * Codename: postal_code
   *
   * E.g. 60200
   */
  postalCode: Elements.TextElement;

  /**
   * City (text)
   * Required: true
   * Id: 6174ffbc-e0d4-380d-01c4-58e92f6869d6
   * Codename: city
   */
  city: Elements.TextElement;

  /**
   * Country and State (modular_content)
   * Required: false
   * Id: 340787ff-6719-7df7-af86-6ef30881f082
   * Codename: country_and_state
   *
   * You can assign either 'Country and State' or 'Country' content item
   */
  countryAndState: Elements.LinkedItemsElement<
    CountryAndStateModel | CountryModel
  >;

  /**
   * VAT number (text)
   * Required: false
   * Id: f17febfc-744f-4718-a3ab-806250579dcf
   * Codename: vat_number
   */
  vatNumber: Elements.TextElement;

  /**
   * Photo (asset)
   * Required: false
   * Id: 8f58348e-ea7e-440c-8f74-01cd3a1a7742
   * Codename: photo
   *
   * Used on Horizons page:Card image (424x337) used as the card image in the 'location' section on /horizons
   */
  photo: Elements.AssetsElement;

  /**
   * Description (rich_text)
   * Required: false
   * Id: ecd25383-64ba-4c8d-a814-03b9e196096e
   * Codename: description
   *
   * Short description of the venue (used on the Horizons subpage for example)
   */
  description: Elements.RichTextElement;
}>;
