import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { CountryAndStateModel } from './CountryAndStateModel';
import { CountryModel } from './CountryModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Address
 * Id: 321692a1-c258-4b91-8d9e-86f891e6339b
 * Codename: address
 */
export type AddressModel = IContentItem<{
  /**
   * Name (text)
   * Required: true
   * Id: 89e68b66-7e17-4a30-a406-5c648471116f
   * Codename: name
   *
   * Company name, e.g. Kentico software s.ro.
   */
  name: Elements.TextElement;

  /**
   * Street (text)
   * Required: true
   * Id: 60f106d7-c7dc-45ef-aa47-7d58d8ab1e0b
   * Codename: street
   *
   * Street and optionally additional info, e.g:15 Constitution Dr.Suite 2G
   */
  street: Elements.TextElement;

  /**
   * Postal code (text)
   * Required: true
   * Id: c5f17c87-ca50-454b-a882-02fd5475c613
   * Codename: postal_code
   *
   * E.g. 60200
   */
  postalCode: Elements.TextElement;

  /**
   * City (text)
   * Required: false
   * Id: 6174ffbc-e0d4-380d-01c4-58e92f6869d6
   * Codename: city
   */
  city: Elements.TextElement;

  /**
   * Country and State (modular_content)
   * Required: false
   * Id: 340787ff-6719-7df7-af86-6ef30881f082
   * Codename: country_and_state
   *
   * You can assign either 'Country and State' or 'Country' content item
   */
  countryAndState: Elements.LinkedItemsElement<
    CountryAndStateModel | CountryModel
  >;
}>;
