import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { Metadata } from '../content-type-snippets/metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Article topic
 * Id: 94e036b4-05ae-48e4-8462-c201178762ca
 * Codename: article_topic
 */
export type ArticleTopicModel = IContentItem<{
  /**
   * Title (text)
   * Required: false
   * Id: f60160c8-e1a0-4dc6-a68b-bd0d1271a374
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * URL Slug (url_slug)
   * Required: false
   * Id: cbf8f578-84cd-49ee-8f76-a7f615dba64e
   * Codename: url_slug
   */
  urlSlug: Elements.UrlSlugElement;
}> &
  Metadata;
