import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { SolutionsPageRelatedAssetModel } from './SolutionsPageRelatedAssetModel';
import { BlogPostModel } from './BlogPostModel';
import { AuthorModel } from './AuthorModel';
import { ArticleTopicModel } from './ArticleTopicModel';
import { ArticleLevelModel } from './ArticleLevelModel';
import { Metadata } from '../content-type-snippets/metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Article
 * Id: eeed0e56-7d31-488b-8296-2ce8b4936284
 * Codename: article
 */
export type ArticleModel = IContentItem<{
  /**
   * Title (text)
   * Required: false
   * Id: b1bd5829-30e1-44a7-b1c0-91a76395f402
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Lead paragraph (rich_text)
   * Required: false
   * Id: 619113f7-d088-44b9-97e0-145563bd7cd9
   * Codename: lead_paragraph
   */
  leadParagraph: Elements.RichTextElement;

  /**
   * Body (rich_text)
   * Required: false
   * Id: 5b77a5a6-513c-4652-bf18-e353b9d08fa4
   * Codename: body
   */
  body: Elements.RichTextElement;

  /**
   * Heading (rich_text)
   * Required: false
   * Id: 023c4ef5-f3d7-491d-a9cf-c3fbcbd84716
   * Codename: heading_resources
   */
  headingResources: Elements.RichTextElement;

  /**
   * Related assets (modular_content)
   * Required: false
   * Id: 3d67e48e-2aa8-4fb5-b417-f21c861c7b12
   * Codename: related_assets
   */
  relatedAssets: Elements.LinkedItemsElement<SolutionsPageRelatedAssetModel>;

  /**
   * What to read next (modular_content)
   * Required: false
   * Id: 75aec5ef-82e4-4607-8bc4-3784f011fe59
   * Codename: what_to_read_next
   */
  whatToReadNext: Elements.LinkedItemsElement<ArticleModel | BlogPostModel>;

  /**
   * Card image (asset)
   * Required: false
   * Id: 54444532-3758-4889-979b-ee47fcadd24d
   * Codename: card_image
   */
  cardImage: Elements.AssetsElement;

  /**
   * Card lead paragraph (rich_text)
   * Required: false
   * Id: 987959a9-e26d-4f5c-86ea-cb023a927304
   * Codename: card_lead_paragraph
   */
  cardLeadParagraph: Elements.RichTextElement;

  /**
   * Date (date_time)
   * Required: false
   * Id: 98c8dbeb-a07c-4458-a885-67a45ce9c57c
   * Codename: date
   */
  date: Elements.DateTimeElement;

  /**
   * Author (modular_content)
   * Required: false
   * Id: 19b8412f-dc6e-4b31-83b3-1522f309c265
   * Codename: author
   */
  author: Elements.LinkedItemsElement<AuthorModel>;

  /**
   * Topic (modular_content)
   * Required: false
   * Id: d917fc45-75cb-4eee-9d26-7feff40560ae
   * Codename: topic
   */
  topic: Elements.LinkedItemsElement<ArticleTopicModel>;

  /**
   * Level (modular_content)
   * Required: false
   * Id: d3bedf49-0f1c-43ca-b867-143b22d43fe1
   * Codename: level
   */
  level: Elements.LinkedItemsElement<ArticleLevelModel>;

  /**
   * Header image (asset)
   * Required: false
   * Id: 639f33f3-25ea-4948-9a58-043e320000c8
   * Codename: header_image
   */
  headerImage: Elements.AssetsElement;

  /**
   * URL slug (url_slug)
   * Required: false
   * Id: 1f741c2e-66ed-4690-9d12-29fb1913ecc2
   * Codename: url_slug
   */
  urlSlug: Elements.UrlSlugElement;
}> &
  Metadata;
