import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { ContentItemYoutubeVideoModel } from './ContentItemYoutubeVideoModel';
import { UmlpElementPartnerSuccessStoriesShowcaseModel } from './UmlpElementPartnerSuccessStoriesShowcaseModel';
import { ModularItemCardElementModel } from './ModularItemCardElementModel';
import { PartnerPlanModel } from './PartnerPlanModel';
import { TestimonialModel } from './TestimonialModel';
import { RichTestimonialModel } from './RichTestimonialModel';
import { ConsentElementModel } from './ConsentElementModel';
import { Metadata } from '../content-type-snippets/metadata';
import { ReleaseProjects } from '../taxonomies/release_projects';
import { SitemapMetadata } from '../content-type-snippets/sitemap_metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Become a Partner page
 * Id: e3ffad4f-5300-428f-bd9a-716ea28c5944
 * Codename: become_a_partner_page
 */
export type BecomeAPartnerPageModel = IContentItem<{
  /**
   * Title (text)
   * Required: true
   * Id: 63182cdf-949d-f87e-ee2f-317dcc5caee0
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Lead paragraph (text)
   * Required: true
   * Id: 56ae64ca-bb52-6659-e668-c6f5509f962f
   * Codename: lead_paragraph
   */
  leadParagraph: Elements.TextElement;

  /**
   * Video (modular_content)
   * Required: false
   * Id: be8ae6cd-97e9-4e08-9777-6a8d0326d89b
   * Codename: video
   */
  video: Elements.LinkedItemsElement<ContentItemYoutubeVideoModel>;

  /**
   * Success stories (modular_content)
   * Required: false
   * Id: a86e95ca-56ad-4c45-b714-4f3497fb84fd
   * Codename: success_stories
   */
  successStories: Elements.LinkedItemsElement<UmlpElementPartnerSuccessStoriesShowcaseModel>;

  /**
   * Benefits (modular_content)
   * Required: true
   * Id: e5289cdb-d06f-5a6e-7919-7f18e13f5baf
   * Codename: benefits
   */
  benefits: Elements.LinkedItemsElement<ModularItemCardElementModel>;

  /**
   * Good company heading (rich_text)
   * Required: false
   * Id: 7a4e0c7a-e9e6-4324-b8b6-3be84cffea41
   * Codename: good_company_heading
   */
  goodCompanyHeading: Elements.RichTextElement;

  /**
   * Partner levels heading (rich_text)
   * Required: false
   * Id: 386e1eee-74bf-4923-af46-bea40857c674
   * Codename: partner_levels_heading
   */
  partnerLevelsHeading: Elements.RichTextElement;

  /**
   * Partner levels section items (modular_content)
   * Required: false
   * Id: f68c63a3-21dd-4bef-9bae-c9802f057bcd
   * Codename: partner_levels_section_items
   */
  partnerLevelsSectionItems: Elements.LinkedItemsElement<PartnerPlanModel>;

  /**
   * Partners (rich_text)
   * Required: false
   * Id: 57ddc5a8-ed4f-b184-d948-5d7c2f113996
   * Codename: partners
   *
   * [OBSOLETE]
   */
  partners: Elements.RichTextElement;

  /**
   * Partner logos (asset)
   * Required: false
   * Id: a7188e2e-2023-43fe-a51b-1847475859b1
   * Codename: partner_logos
   */
  partnerLogos: Elements.AssetsElement;

  /**
   * Partnership heading (rich_text)
   * Required: false
   * Id: 2e57c56d-27b7-4c52-a630-031ecd9e9d76
   * Codename: partnership_heading
   */
  partnershipHeading: Elements.RichTextElement;

  /**
   * Partnership (modular_content)
   * Required: true
   * Id: 71215cb3-b731-5b28-9bc0-21d076165ceb
   * Codename: partnership
   */
  partnership: Elements.LinkedItemsElement<ModularItemCardElementModel>;

  /**
   * Testimonials title (text)
   * Required: true
   * Id: d2094669-78e4-bfa2-651c-138a17a8c420
   * Codename: testimonials_title
   */
  testimonialsTitle: Elements.TextElement;

  /**
   * Testimonials (modular_content)
   * Required: true
   * Id: 5f1ce34b-255b-09c6-a789-16c4e6e059c1
   * Codename: testimonials
   */
  testimonials: Elements.LinkedItemsElement<
    TestimonialModel | RichTestimonialModel
  >;

  /**
   * Form title (text)
   * Required: false
   * Id: db7ea949-eba7-990a-9aa3-2913e81d8169
   * Codename: form_title
   */
  formTitle: Elements.TextElement;

  /**
   * Form info (text)
   * Required: false
   * Id: 39d533c5-5bc4-0fce-b9ee-97303065f25b
   * Codename: form_info
   */
  formInfo: Elements.TextElement;

  /**
   * Form Above Submit Button Text (text)
   * Required: false
   * Id: a8d29cbf-7388-41a1-a443-5aa49ad48830
   * Codename: form_above_submit_button_text
   */
  formAboveSubmitButtonText: Elements.TextElement;

  /**
   * Submit Button Text (text)
   * Required: false
   * Id: a83b0dad-23f7-481f-1b86-d93527cf741c
   * Codename: submit_button_text
   */
  submitButtonText: Elements.TextElement;

  /**
   * Thank you title (text)
   * Required: false
   * Id: 5db50c72-cb44-8b40-5582-de316c708a4f
   * Codename: thank_you_title
   */
  thankYouTitle: Elements.TextElement;

  /**
   * Thank you message (text)
   * Required: false
   * Id: b8d9bd35-d363-8104-ef8d-65cb71d1fb1a
   * Codename: thank_you_message
   */
  thankYouMessage: Elements.TextElement;

  /**
   * Consent Elements (modular_content)
   * Required: false
   * Id: 9e26fa90-3bc3-46ee-8cf7-5f66cea1bcba
   * Codename: consent_elements
   */
  consentElements: Elements.LinkedItemsElement<ConsentElementModel>;

  /**
   * Form next step info (rich_text)
   * Required: false
   * Id: 3659efc9-7e3a-4880-beb9-91f4c7222e6a
   * Codename: form_next_step_info
   */
  formNextStepInfo: Elements.RichTextElement;

  /**
   * Premium partner badge (asset)
   * Required: false
   * Id: 34de3303-ccd7-45a1-8124-a05ca80752c5
   * Codename: premium_partner_badge
   *
   * [OBSOLETE]
   */
  premiumPartnerBadge: Elements.AssetsElement;

  /**
   * Advanced partner badge (asset)
   * Required: false
   * Id: 260a691c-3811-41a4-8ea0-427c8835edad
   * Codename: advanced_partner_badge
   *
   * [OBSOLETE]
   */
  advancedPartnerBadge: Elements.AssetsElement;

  /**
   * Qualified partner badge (asset)
   * Required: false
   * Id: e39024c9-2a24-4af8-b686-c74807a216ae
   * Codename: qualified_partner_badge
   *
   * [OBSOLETE]
   */
  qualifiedPartnerBadge: Elements.AssetsElement;

  /**
   * Subscribe to newsletter (text)
   * Required: false
   * Id: aa1f79a8-ba3f-4803-b8d8-c50fecb94736
   * Codename: subscribe_to_newsletter
   */
  subscribeToNewsletter: Elements.TextElement;

  /**
   * Release projects (taxonomy)
   * Required: false
   * Id: 509269fb-6fe7-444b-a1a5-2fb7d1cff534
   * Codename: release_projects
   */
  releaseProjects: Elements.TaxonomyElement<ReleaseProjects>;
}> &
  Metadata &
  SitemapMetadata;
