import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Bingo Item
 * Id: dc20195e-6bc3-4c8d-9fd1-de3f985fcd65
 * Codename: bingo_item
 */
export type BingoItemModel = IContentItem<{
  /**
   * Text (rich_text)
   * Required: false
   * Id: 6bc67844-6a22-4b15-ba0e-6d18105f574f
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * Primary Icon (asset)
   * Required: false
   * Id: 16b30f9f-a76a-4343-a202-5db8890f7e24
   * Codename: primary_icon
   */
  primaryIcon: Elements.AssetsElement;

  /**
   * Secondary Icon (asset)
   * Required: false
   * Id: dddfb578-8c4f-49f2-9a80-6905a0568e26
   * Codename: secondary_icon
   */
  secondaryIcon: Elements.AssetsElement;
}>;
