import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { Hero } from '../content-type-snippets/hero';
import { CampaignsParagraphModel } from './CampaignsParagraphModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Campaigns - universal template
 * Id: efa8e602-d49d-482c-91ce-25bb591f25ed
 * Codename: campaigns___universal_template
 */
export type CampaignsUniversalTemplateModel = IContentItem<{
  /**
   * url slug (url_slug)
   * Required: false
   * Id: 69a1bc43-7899-4a94-ab2f-44166046cff3
   * Codename: url_slug_69a1bc4
   */
  urlSlug69a1bc4: Elements.UrlSlugElement;

  /**
   * url slug source (text)
   * Required: true
   * Id: 3812a98e-d03d-44c6-84b9-38542979f54c
   * Codename: url_slug_source
   */
  urlSlugSource: Elements.TextElement;

  /**
   * Header image (asset)
   * Required: false
   * Id: e8cda8fe-17ad-45bd-b205-a47967281139
   * Codename: header_image
   */
  headerImage: Elements.AssetsElement;

  /**
   * Paragraphs (modular_content)
   * Required: true
   * Id: 5a8fa8f5-c9c3-4299-8638-50ef9400be15
   * Codename: paragraphs
   */
  paragraphs: Elements.LinkedItemsElement<CampaignsParagraphModel>;

  /**
   * Benefits (rich_text)
   * Required: false
   * Id: f2437dac-9a22-472e-a23d-b2c247444660
   * Codename: benefits
   */
  benefits: Elements.RichTextElement;
}> &
  Hero;
