import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { SharedContentModel } from './SharedContentModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Campaigns - paragraph
 * Id: f43b9edc-5477-4483-8cc3-f1c5a4baee16
 * Codename: campaigns___paragraph
 */
export type CampaignsParagraphModel = IContentItem<{
  /**
   * Title (text)
   * Required: false
   * Id: ad2c34e5-c6cd-4b12-8b9f-7c7d28c73953
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Content (rich_text)
   * Required: true
   * Id: 09f7a54f-7ace-4ae1-9bae-2f61630114f2
   * Codename: content
   */
  content: Elements.RichTextElement;

  /**
   * CTA (modular_content)
   * Required: false
   * Id: 2dc07f2f-32bf-48f3-80a7-d732c3058a02
   * Codename: cta
   */
  cta: Elements.LinkedItemsElement<SharedContentModel>;
}>;
