import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Careers - Job Opportunities
 * Id: 36d1874c-af32-4149-bb69-2cbe8ac0e498
 * Codename: careers___job_opportunities
 */
export type CareersJobOpportunitiesModel = IContentItem<{
  /**
   * Heading (text)
   * Required: true
   * Id: de32b5ea-0127-4cd4-bcb1-d28320654cf5
   * Codename: heading
   */
  heading: Elements.TextElement;

  /**
   * Appendix (rich_text)
   * Required: false
   * Id: 73bc5884-7d96-419c-b91b-83ad6c8657fb
   * Codename: appendix
   *
   * Optional appendix that is displayed below the job list
   */
  appendix: Elements.RichTextElement;
}>;
