import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { ReleaseProjects } from '../taxonomies/release_projects';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Code example
 * Id: 4612a3bd-17cf-4cf4-a829-6346c7bbedc3
 * Codename: code_example
 */
export type CodeExampleModel = IContentItem<{
  /**
   * Logo (asset)
   * Required: false
   * Id: a3d2242d-1743-4f79-86a0-2e707b284fac
   * Codename: logo
   */
  logo: Elements.AssetsElement;

  /**
   * Image (asset)
   * Required: true
   * Id: b74e6fd7-8f3c-4c92-86d3-86277919d378
   * Codename: image
   */
  image: Elements.AssetsElement;

  /**
   * Category (multiple_choice)
   * Required: true
   * Id: 6b6d5df2-c3b7-47f9-af9c-f48d34378cf1
   * Codename: category
   */
  category: Elements.MultipleChoiceElement;

  /**
   * Resources (rich_text)
   * Required: false
   * Id: 8033984f-df72-4303-a456-4bfddfa2f42a
   * Codename: resources
   */
  resources: Elements.RichTextElement;

  /**
   * Documentation Link (text)
   * Required: false
   * Id: f4386ea9-6e02-4237-9959-e764d8075480
   * Codename: documentation_link
   *
   * Link to related part in documentation. Please enter full URL including http prefix
   */
  documentationLink: Elements.TextElement;

  /**
   * Release projects (taxonomy)
   * Required: false
   * Id: 32313ba2-5e8c-4e00-a27a-bb9430faa2b4
   * Codename: release_projects
   */
  releaseProjects: Elements.TaxonomyElement<ReleaseProjects>;
}>;
