import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Community - Resource
 * Id: c7979a49-d775-4f16-99c6-5f07c6911a94
 * Codename: community___resource
 */
export type CommunityResourceModel = IContentItem<{
  /**
   * Logo (asset)
   * Required: false
   * Id: 98299bf6-9cf8-4535-97a0-192dd5d8b5d0
   * Codename: logo
   */
  logo: Elements.AssetsElement;

  /**
   * Highlight text (text)
   * Required: false
   * Id: c926739d-800e-4c29-a188-ea948a63723c
   * Codename: highlight_text
   */
  highlightText: Elements.TextElement;

  /**
   * Main URL (text)
   * Required: false
   * Id: 3016bf16-0084-429f-93a5-27f2c8afb371
   * Codename: main_url
   */
  mainUrl: Elements.TextElement;

  /**
   * Title (text)
   * Required: false
   * Id: 3baf655e-daab-4bd5-9459-0e12c76d0327
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Main text (rich_text)
   * Required: false
   * Id: a0d2b0ea-b415-408c-bf0e-a6c4c7cddf4c
   * Codename: main_text
   */
  mainText: Elements.RichTextElement;

  /**
   * Details (rich_text)
   * Required: false
   * Id: 61e1ac8b-df3a-41fe-8b6a-c69172ff7119
   * Codename: details
   */
  details: Elements.RichTextElement;

  /**
   * Color code (text)
   * Required: false
   * Id: baf17ba6-bb86-4421-9e74-5c67efdf124b
   * Codename: color_code
   */
  colorCode: Elements.TextElement;
}>;
