import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Community - Gitter section
 * Id: 96d3b1c8-270c-441a-99cb-7f0815e07949
 * Codename: community___gitter_section
 */
export type CommunityGitterSectionModel = IContentItem<{
  /**
   * Headline (text)
   * Required: false
   * Id: 4602a757-e3d6-4ad0-a953-bd7ca4f6cb7f
   * Codename: headline
   */
  headline: Elements.TextElement;

  /**
   * Lead paragraph (rich_text)
   * Required: false
   * Id: aae32603-c7a9-4494-a711-f16cb6a4830d
   * Codename: lead_paragraph
   */
  leadParagraph: Elements.RichTextElement;

  /**
   * Logo (asset)
   * Required: false
   * Id: 84c9413c-f79e-454d-b4ee-058d2167eac8
   * Codename: logo
   */
  logo: Elements.AssetsElement;
}>;
