import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Company Value
 * Id: c47f751b-8b77-4e14-846e-ebcb61616c11
 * Codename: company_value
 */
export type CompanyValueModel = IContentItem<{
  /**
   * Value (text)
   * Required: true
   * Id: 9ec5d4ee-913c-4150-968e-a16542801dc2
   * Codename: value
   */
  value: Elements.TextElement;

  /**
   * Description (text)
   * Required: true
   * Id: 97e5ffcb-2b9f-4056-a9dc-8a6e33170114
   * Codename: description
   */
  description: Elements.TextElement;

  /**
   * Icon (custom)
   * Required: false
   * Id: 17037d56-64a4-437b-af10-f34722a2d197
   * Codename: icon
   */
  icon: Elements.CustomElement;
}>;
