import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { HeroKK } from '../content-type-snippets/hero_kk';
import { KontentUniqueFeatureModel } from './KontentUniqueFeatureModel';
import { TableModel } from './TableModel';
import { BubbleModel } from './BubbleModel';
import { ModularItemCardElementModel } from './ModularItemCardElementModel';
import { CtaBannerComponentModel } from './CtaBannerComponentModel';
import { Metadata } from '../content-type-snippets/metadata';
import { SitemapMetadata } from '../content-type-snippets/sitemap_metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Compare Page - Root
 * Id: 1702b803-f389-464c-90be-e548f20b343f
 * Codename: compare_page_root
 */
export type ComparePageRootModel = IContentItem<{
  /**
   * Heading (text)
   * Required: false
   * Id: 15bbc043-7839-469b-9bcf-939528836d80
   * Codename: intro_heading
   */
  introHeading: Elements.TextElement;

  /**
   * Text (rich_text)
   * Required: false
   * Id: f3a47994-fce4-46dd-a574-ea8b9659c5a9
   * Codename: intro_text
   */
  introText: Elements.RichTextElement;

  /**
   * Heading (text)
   * Required: false
   * Id: c4f56411-232b-4a69-ba1e-5cf8ebd04c6b
   * Codename: compare_heading
   */
  compareHeading: Elements.TextElement;

  /**
   * Text (rich_text)
   * Required: false
   * Id: f3e51c32-077e-4276-bb5e-b4c2d51314f4
   * Codename: compare_text
   */
  compareText: Elements.RichTextElement;

  /**
   * Features subheading (text)
   * Required: false
   * Id: f3b679f4-ca78-4be2-a19f-c531005e8a18
   * Codename: features_subheading
   */
  featuresSubheading: Elements.TextElement;

  /**
   * Features (modular_content)
   * Required: false
   * Id: dfa4c147-698e-4c61-9b12-6d2698bc1e27
   * Codename: features
   */
  features: Elements.LinkedItemsElement<KontentUniqueFeatureModel>;

  /**
   * Compare table heading (text)
   * Required: false
   * Id: dcba2108-7085-4ef9-8523-0a7836a386a5
   * Codename: compare_table_heading
   */
  compareTableHeading: Elements.TextElement;

  /**
   * Compare table (modular_content)
   * Required: false
   * Id: c009513f-c95d-4b2a-8e1a-9713b2a7cbb7
   * Codename: compare_table
   */
  compareTable: Elements.LinkedItemsElement<TableModel>;

  /**
   * Heading (text)
   * Required: false
   * Id: 1f73a4a5-73f7-4828-8e2e-8c55cf9cc13f
   * Codename: why_heading
   */
  whyHeading: Elements.TextElement;

  /**
   * Reasons (modular_content)
   * Required: false
   * Id: e9f5dba7-b4b8-4e3b-8673-f2c4e498137a
   * Codename: reasons
   */
  reasons: Elements.LinkedItemsElement<BubbleModel>;

  /**
   * Table heading (text)
   * Required: false
   * Id: 3fca59cd-4bcd-4701-9939-1f858204cada
   * Codename: table_heading
   */
  tableHeading: Elements.TextElement;

  /**
   * Table (modular_content)
   * Required: false
   * Id: d3477fe7-6501-4963-b34c-b3f50d27d211
   * Codename: table
   */
  table: Elements.LinkedItemsElement<TableModel>;

  /**
   * Heading (text)
   * Required: false
   * Id: acbe576f-cf94-492f-8760-b79e4d0ef311
   * Codename: heading_links
   */
  headingLinks: Elements.TextElement;

  /**
   * Text (rich_text)
   * Required: false
   * Id: 38b82c8d-8cf4-4112-bddf-cba15a45ac48
   * Codename: text_links
   */
  textLinks: Elements.RichTextElement;

  /**
   * Links (modular_content)
   * Required: false
   * Id: 10a9b5f5-6fdc-4ed2-8c36-b76ce7626019
   * Codename: links___new
   */
  linksNew: Elements.LinkedItemsElement<ModularItemCardElementModel>;

  /**
   * Heading (text)
   * Required: false
   * Id: 43bd552e-9cb8-41b6-8f8b-625e53094ad9
   * Codename: recognitions_heading
   */
  recognitionsHeading: Elements.TextElement;

  /**
   * Recognitions (modular_content)
   * Required: false
   * Id: 94859673-7580-433f-87b5-b51245fa1485
   * Codename: recognitions
   */
  recognitions: Elements.LinkedItemsElement<IContentItem>;

  /**
   * CTA Banner (modular_content)
   * Required: false
   * Id: 0cf9163a-8743-4e61-bbcb-3fa8ab6aec57
   * Codename: cta_banner
   */
  ctaBanner: Elements.LinkedItemsElement<CtaBannerComponentModel>;
}> &
  HeroKK &
  Metadata &
  SitemapMetadata;
