import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Company
 * Id: aec624c8-ec95-41a5-80b5-4f0d847ae74e
 * Codename: company
 */
export type CompanyModel = IContentItem<{
  /**
   * Name (text)
   * Required: true
   * Id: 77a0e15c-e323-4571-bed6-add740384dd4
   * Codename: name
   */
  name: Elements.TextElement;

  /**
   * About (rich_text)
   * Required: true
   * Id: 649fda4b-73fe-43cf-b99c-7dfb1eba467d
   * Codename: about
   */
  about: Elements.RichTextElement;

  /**
   * Logo (asset)
   * Required: true
   * Id: a31a48da-021f-4c6e-9d25-9b0abaf94828
   * Codename: logo
   */
  logo: Elements.AssetsElement;
}>;
