import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { UMLPContent } from '../content-type-snippets/umlp_content';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Component Group
 * Id: 3db49a4f-f41c-4a03-9993-fd5bc02edf4b
 * Codename: component_group
 */
export type ComponentGroupModel = IContentItem<{
  /**
   * Name (text)
   * Required: true
   * Id: 002e7d2f-6f75-44ac-9f42-c5d28d3f19c5
   * Codename: name
   */
  name: Elements.TextElement;

  /**
   * Icon (custom)
   * Required: false
   * Id: 42795af9-450c-4ace-a5e6-bd573b2e718d
   * Codename: icon
   */
  icon: Elements.CustomElement;
}> &
  UMLPContent;
