import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Content Block
 * Id: 03409c7b-6519-46a2-a5ee-7483a8e6f24f
 * Codename: content_piece
 */
export type ContentPieceModel = IContentItem<{
  /**
   * Heading (rich_text)
   * Required: false
   * Id: d8b14b04-b542-487e-8910-b7b7c4850b6a
   * Codename: heading
   */
  heading: Elements.RichTextElement;

  /**
   * Text (rich_text)
   * Required: false
   * Id: a8c5146c-35b8-40c9-a233-32e6ed75781f
   * Codename: text
   */
  text: Elements.RichTextElement;
}>;
