import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Content Item - Key Points
 * Id: 14675008-3eaa-4485-8a79-b8369f41d16a
 * Codename: content_item___key_points
 */
export type ContentItemKeyPointsModel = IContentItem<{
  /**
   * Text (rich_text)
   * Required: false
   * Id: 0034514d-e46a-4fe4-bdc2-c233e818918d
   * Codename: text
   */
  text: Elements.RichTextElement;
}>;
