import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { ContentCollaborationFeatureModel } from './ContentCollaborationFeatureModel';
import { ReleaseProjects } from '../taxonomies/release_projects';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Content Collaboration Floor
 * Id: d4dfcd7c-df81-4e46-9358-5b104a9fb9c6
 * Codename: content_collaboration_floor
 */
export type ContentCollaborationFloorModel = IContentItem<{
  /**
   * Codename (text)
   * Required: true
   * Id: 801224db-c609-44f4-a1b3-162e58229d80
   * Codename: codename
   *
   * Lowercase without spaces
   */
  codename: Elements.TextElement;

  /**
   * Heading (rich_text)
   * Required: true
   * Id: 58a51fa1-5d2e-4d44-8530-1364eead865c
   * Codename: heading
   */
  heading: Elements.RichTextElement;

  /**
   * Description (rich_text)
   * Required: false
   * Id: abb6938f-87e4-4a84-bc93-4eb1c046c9ae
   * Codename: description
   */
  description: Elements.RichTextElement;

  /**
   * Image (asset)
   * Required: false
   * Id: 2dc4b5c5-367b-46fb-9c1e-fc56cfdb2345
   * Codename: image
   */
  image: Elements.AssetsElement;

  /**
   * Image 2x (asset)
   * Required: false
   * Id: f0a8bf1a-ca4d-4913-8f09-c592791b8071
   * Codename: image_2x
   */
  image2x: Elements.AssetsElement;

  /**
   * Content Collaboration Features (modular_content)
   * Required: false
   * Id: 34373356-eea3-48ff-80af-f52e72b73ecb
   * Codename: content_collaboration_features
   */
  contentCollaborationFeatures: Elements.LinkedItemsElement<ContentCollaborationFeatureModel>;

  /**
   * Type (multiple_choice)
   * Required: false
   * Id: a1117587-4f3b-47b9-87eb-77700ab75064
   * Codename: type
   */
  type: Elements.MultipleChoiceElement;

  /**
   * Release projects (taxonomy)
   * Required: false
   * Id: cc2ebeca-3a86-4cb5-b325-d8a5a565b570
   * Codename: release_projects
   */
  releaseProjects: Elements.TaxonomyElement<ReleaseProjects>;
}>;
