import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Content creation - feature
 * Id: de610a8b-e55d-4304-80fa-d10e48739d3f
 * Codename: content_creation___feature
 */
export type ContentCreationFeatureModel = IContentItem<{
  /**
   * Image (asset)
   * Required: false
   * Id: b815daf9-b1f6-4849-a35a-15b0c887be84
   * Codename: image
   */
  image: Elements.AssetsElement;

  /**
   * Category (multiple_choice)
   * Required: true
   * Id: 93e4e883-a8d3-41b9-8387-47494a436af1
   * Codename: category
   */
  category: Elements.MultipleChoiceElement;

  /**
   * Text (text)
   * Required: false
   * Id: 1923c5fb-6812-4063-a2bb-59c23a8c54af
   * Codename: text
   */
  text: Elements.TextElement;
}>;
