import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Content Item - Image
 * Id: 6b24fc83-7911-4118-9441-871419b4480c
 * Codename: content_item___image
 */
export type ContentItemImageModel = IContentItem<{
  /**
   * Image (asset)
   * Required: true
   * Id: 897accdd-09b6-8bc7-db2e-9a9155672eed
   * Codename: image
   */
  image: Elements.AssetsElement;

  /**
   * Caption (text)
   * Required: false
   * Id: d47c0c32-4ad9-8346-d58f-233e40cd052a
   * Codename: caption
   */
  caption: Elements.TextElement;

  /**
   * Open image (multiple_choice)
   * Required: false
   * Id: e17ee408-0d2b-c17f-8b94-b7416e975866
   * Codename: open_image
   */
  openImage: Elements.MultipleChoiceElement;

  /**
   * Force original size (multiple_choice)
   * Required: false
   * Id: a89bc672-bbf1-43f1-bf46-a579f07992e5
   * Codename: force_original_size
   *
   * Images are by default resized to 100% of width of their container. Setting this value to "Yes" prevent this behavior and show images in original size (usefull for small images so they are not too stretched)
   */
  forceOriginalSize: Elements.MultipleChoiceElement;
}>;
