import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Content Item - YouTube Video
 * Id: 4eba87ea-aebb-4cbb-97b5-8c3d61c9aa74
 * Codename: content_item___youtube_video
 */
export type ContentItemYoutubeVideoModel = IContentItem<{
  /**
   * Video ID (text)
   * Required: false
   * Id: 2df33c2b-7147-3afd-a1fb-bad962d2dc24
   * Codename: video_id
   *
   * ID of video. Can be extracted from URL - e.g. in https://youtu.be/sUHA5EbUJ3g the ID is "sUHA5EbUJ3g"
   */
  videoId: Elements.TextElement;

  /**
   * Caption (text)
   * Required: false
   * Id: 129cbe76-0dab-dd8d-5323-758e39250ff5
   * Codename: caption
   *
   * Caption for the video which appears just below the video. Only use in embedded elements!
   */
  caption: Elements.TextElement;

  /**
   * Video Poster (asset)
   * Required: false
   * Id: b185ec33-e6fe-4865-9744-a8740c04a6b5
   * Codename: video_poster
   *
   * Optional overlay image displayed over the video iframe before the user presses play
   */
  videoPoster: Elements.AssetsElement;

  /**
   * Video Schema.org (custom)
   * Required: false
   * Id: 7bc6af72-daa6-4a4e-9fca-602eb9572be3
   * Codename: video_schema_org
   */
  videoSchemaOrg: Elements.CustomElement;
}>;
