import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { SharedContentModel } from './SharedContentModel';
import { ReleaseProjects } from '../taxonomies/release_projects';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * CTA Section
 * Id: ee3300d6-d957-4a31-ba87-d445d21e5921
 * Codename: cta_banner_component
 */
export type CtaBannerComponentModel = IContentItem<{
  /**
   * Headline (rich_text)
   * Required: true
   * Id: eb47ee7f-7b32-4f8a-ac50-3b3b21f7f535
   * Codename: headline
   *
   * Headline. Always make sure to highlight the text and mark it as H2 in order to get desired styling. Add a dot and mark it as bold (inside the h2) to get white highlighting
   */
  headline: Elements.RichTextElement;

  /**
   * Lead paragraph (rich_text)
   * Required: false
   * Id: 9a276b31-261c-4f31-8309-bd53c360c595
   * Codename: lead_paragraph
   */
  leadParagraph: Elements.RichTextElement;

  /**
   * Primary CTA (modular_content)
   * Required: false
   * Id: bba5b730-f8c7-4f6d-bc2e-b76cc764b20e
   * Codename: primary_cta
   */
  primaryCta: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Secondary CTA (modular_content)
   * Required: false
   * Id: bbb7af6c-843e-491e-b4f1-c3813adf5413
   * Codename: secondary_cta
   */
  secondaryCta: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Text between CTAs (text)
   * Required: false
   * Id: 804275f9-62d0-4aab-8cfb-f151751d3a9f
   * Codename: text_between_ctas
   */
  textBetweenCtas: Elements.TextElement;

  /**
   * Display type (multiple_choice)
   * Required: false
   * Id: 4fd77944-73e3-4bbd-b969-a2e71945a1a4
   * Codename: display_type
   */
  displayType: Elements.MultipleChoiceElement;

  /**
   * Top level class name (text)
   * Required: false
   * Id: dc23b4d6-2210-4acb-a575-23aa174bd9f5
   * Codename: top_level_class_name
   */
  topLevelClassName: Elements.TextElement;

  /**
   * Image (asset)
   * Required: false
   * Id: 4cc536f2-f544-47ac-a96d-1345338cd895
   * Codename: image
   *
   * Use with "Light gray" option
   */
  image: Elements.AssetsElement;

  /**
   * Release projects (taxonomy)
   * Required: false
   * Id: e3914695-c22b-41ac-b921-0916355b6c8d
   * Codename: release_projects
   */
  releaseProjects: Elements.TaxonomyElement<ReleaseProjects>;
}>;
