import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { ReleaseProjects } from '../taxonomies/release_projects';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Development Feature KK
 * Id: 6ab865b2-2a2a-470d-8f19-e2c50e6c3af1
 * Codename: development_feature_kk
 */
export type DevelopmentFeatureKkModel = IContentItem<{
  /**
   * Image (asset)
   * Required: false
   * Id: 0760639c-7b9b-4b11-83f1-dc347e547c6f
   * Codename: image
   */
  image: Elements.AssetsElement;

  /**
   * Headline (text)
   * Required: false
   * Id: c276e6aa-3618-4cbf-acf3-435c383daefe
   * Codename: headline
   *
   * OBSOLETE!
   */
  headline: Elements.TextElement;

  /**
   * Heading (rich_text)
   * Required: false
   * Id: f71bc644-4809-4811-91c3-c18d4102e637
   * Codename: heading
   */
  heading: Elements.RichTextElement;

  /**
   * Description (rich_text)
   * Required: false
   * Id: 99e380f9-f32d-4c34-9e5b-008e0289207c
   * Codename: description
   */
  description: Elements.RichTextElement;

  /**
   * Release projects (taxonomy)
   * Required: false
   * Id: dc05d231-43f1-41c9-b325-646d31cb5625
   * Codename: release_projects
   */
  releaseProjects: Elements.TaxonomyElement<ReleaseProjects>;
}>;
