import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Developers KK - Graphic Bubbles
 * Id: 19c44a42-22f0-4886-8fe1-f6971fdfcf80
 * Codename: developers_kk___graphic_bubbles
 */
export type DevelopersKkGraphicBubblesModel = IContentItem<{
  /**
   * Green bubble text (text)
   * Required: false
   * Id: 893ed8ce-d60a-468b-912a-796276daf058
   * Codename: green_bubble_text
   */
  greenBubbleText: Elements.TextElement;

  /**
   * Green bubble icon (asset)
   * Required: false
   * Id: ceaafc7c-2c83-49fe-b5a0-9ad820bf59aa
   * Codename: green_bubble_icon
   */
  greenBubbleIcon: Elements.AssetsElement;

  /**
   * Blue bubble text (text)
   * Required: false
   * Id: 77a88ef4-3f09-425a-8fef-008c7c33cc7d
   * Codename: blue_bubble_text
   */
  blueBubbleText: Elements.TextElement;

  /**
   * Blue bubble icon (asset)
   * Required: false
   * Id: 9c474868-e47b-4ffa-90f4-d2c04e3b683b
   * Codename: blue_bubble_icon
   */
  blueBubbleIcon: Elements.AssetsElement;

  /**
   * Purple bubble text (text)
   * Required: false
   * Id: 2a21033d-986f-4dcd-9c83-a3006c01c50c
   * Codename: purple_bubble_text
   */
  purpleBubbleText: Elements.TextElement;

  /**
   * Purple bubble icon (asset)
   * Required: false
   * Id: 5052c71f-e937-49cc-81dc-318a94dc4085
   * Codename: purple_bubble_icon
   */
  purpleBubbleIcon: Elements.AssetsElement;

  /**
   * White bubble image (asset)
   * Required: false
   * Id: 8a9dc78b-a8f6-425c-8e34-0de6ecc20910
   * Codename: white_bubble_image
   */
  whiteBubbleImage: Elements.AssetsElement;
}>;
