import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { HeroKK } from '../content-type-snippets/hero_kk';
import { SharedContentModel } from './SharedContentModel';
import { BingoItemModel } from './BingoItemModel';
import { TestimonialModel } from './TestimonialModel';
import { DevelopersKkIncludedCardModel } from './DevelopersKkIncludedCardModel';
import { DevelopersKkGraphicBubblesModel } from './DevelopersKkGraphicBubblesModel';
import { ContentItemCodeModel } from './ContentItemCodeModel';
import { CtaBannerComponentModel } from './CtaBannerComponentModel';
import { Metadata } from '../content-type-snippets/metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Developers KK
 * Id: 59e8af92-c2ba-441b-a609-a37a034d6456
 * Codename: developers_page_kk
 */
export type DevelopersPageKkModel = IContentItem<{
  /**
   * CTA Button (modular_content)
   * Required: false
   * Id: 310f014c-7d79-4674-8cbf-81cdd0fbb212
   * Codename: hero_cta_button
   */
  heroCtaButton: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Heading (text)
   * Required: false
   * Id: f7dbbb2f-6193-44ef-ba86-bfe6bb776b94
   * Codename: bingo_heading
   */
  bingoHeading: Elements.TextElement;

  /**
   * Bingo Items (modular_content)
   * Required: false
   * Id: 2c69bc82-ac76-4d5a-a0ae-88da0be16276
   * Codename: bingo_items
   */
  bingoItems: Elements.LinkedItemsElement<BingoItemModel>;

  /**
   * Testimonial (modular_content)
   * Required: false
   * Id: bc9386b5-2490-4300-a3f9-8eab24e96297
   * Codename: testimonial
   */
  testimonial: Elements.LinkedItemsElement<TestimonialModel>;

  /**
   * YouTube Poster (asset)
   * Required: false
   * Id: da48dbcc-912a-45d5-9181-22328a5bfab4
   * Codename: youtube_poster
   */
  youtubePoster: Elements.AssetsElement;

  /**
   * Video Id (text)
   * Required: false
   * Id: 4a873234-52a1-4720-9041-5cf67ec79835
   * Codename: video_id
   */
  videoId: Elements.TextElement;

  /**
   * Heading (text)
   * Required: false
   * Id: 48277108-6595-4f54-b56e-32d81b093fd6
   * Codename: included_heading
   */
  includedHeading: Elements.TextElement;

  /**
   * Cards (modular_content)
   * Required: false
   * Id: 92cfcb11-d0a9-4997-afdc-e9b1ab1e519e
   * Codename: included_cards
   */
  includedCards: Elements.LinkedItemsElement<DevelopersKkIncludedCardModel>;

  /**
   * Heading (text)
   * Required: false
   * Id: dbd1f556-fb84-4b67-8028-e696a4a46f5e
   * Codename: build_it_heading
   */
  buildItHeading: Elements.TextElement;

  /**
   * Text (rich_text)
   * Required: false
   * Id: 8ac9decb-bd44-4f46-b3b7-3d15922feea5
   * Codename: build_it_text
   */
  buildItText: Elements.RichTextElement;

  /**
   * Graphic (modular_content)
   * Required: false
   * Id: 11525f45-9917-45e6-afdf-27c09d05d059
   * Codename: build_it_graphic
   */
  buildItGraphic: Elements.LinkedItemsElement<DevelopersKkGraphicBubblesModel>;

  /**
   * Code Snippets (modular_content)
   * Required: false
   * Id: 3b666052-61fb-4278-86cd-3d01c725b073
   * Codename: code_snippets
   */
  codeSnippets: Elements.LinkedItemsElement<ContentItemCodeModel>;

  /**
   * CTA Banner (modular_content)
   * Required: false
   * Id: a5671781-9f81-4d1b-ae7d-fdfb99c413bc
   * Codename: cta_banner
   */
  ctaBanner: Elements.LinkedItemsElement<CtaBannerComponentModel>;
}> &
  HeroKK &
  Metadata;
