import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { HeroKK } from '../content-type-snippets/hero_kk';
import { SharedContentModel } from './SharedContentModel';
import { TestimonialModel } from './TestimonialModel';
import { BubbleModel } from './BubbleModel';
import { CtaBannerComponentModel } from './CtaBannerComponentModel';
import { Metadata } from '../content-type-snippets/metadata';
import { SitemapMetadata } from '../content-type-snippets/sitemap_metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * E-Learning Page
 * Id: 55093ce5-8b0f-44d9-9ee9-22f48e563a09
 * Codename: e_learning_page
 */
export type ELearningPageModel = IContentItem<{
  /**
   * CTA Button (modular_content)
   * Required: false
   * Id: 5d87b387-9ba9-4169-a1dd-19d86fccf4f7
   * Codename: cta_button
   */
  ctaButton: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Heading (text)
   * Required: true
   * Id: 3676bdff-acd8-40ac-94fb-09c4be8c279c
   * Codename: heading
   */
  heading: Elements.TextElement;

  /**
   * Testimonial bubbles (modular_content)
   * Required: true
   * Id: 47db0e41-e780-443d-bfad-cd2c9c5b6ac6
   * Codename: testimonial_bubbles
   */
  testimonialBubbles: Elements.LinkedItemsElement<TestimonialModel>;

  /**
   * Heading (text)
   * Required: false
   * Id: 8c95e924-ad5b-4279-9c0a-1c7a09efe02e
   * Codename: heading_bubbles_1
   */
  headingBubbles1: Elements.TextElement;

  /**
   * Text (rich_text)
   * Required: false
   * Id: 30c6f99d-5d30-4c12-b050-7a5557017d45
   * Codename: text_bubbles_1
   */
  textBubbles1: Elements.RichTextElement;

  /**
   * Bubbles (modular_content)
   * Required: false
   * Id: 20500ab3-5d21-4c0e-844b-19bc150a4bb3
   * Codename: bubbles_1
   */
  bubbles1: Elements.LinkedItemsElement<BubbleModel>;

  /**
   * Heading (text)
   * Required: false
   * Id: b91710c8-017b-4748-a7ce-d2e4130b1e45
   * Codename: heading_bubbles_2
   */
  headingBubbles2: Elements.TextElement;

  /**
   * Text (rich_text)
   * Required: false
   * Id: 6758b32c-90e1-428d-926a-131482d62890
   * Codename: text_bubbles_2
   */
  textBubbles2: Elements.RichTextElement;

  /**
   * Bubbles (modular_content)
   * Required: false
   * Id: 1911c623-19e9-4323-8f46-4cfec8c4e76a
   * Codename: bubbles_2
   */
  bubbles2: Elements.LinkedItemsElement<BubbleModel>;

  /**
   * Heading (text)
   * Required: false
   * Id: f4bd0fa4-137e-4e3e-b7cb-948bcc0b7f18
   * Codename: heading_bubbles_3
   */
  headingBubbles3: Elements.TextElement;

  /**
   * Bubbles (modular_content)
   * Required: false
   * Id: 338ccdd0-5438-4409-8de1-7b6885d6164d
   * Codename: bubbles_3
   */
  bubbles3: Elements.LinkedItemsElement<BubbleModel>;

  /**
   * Heading (text)
   * Required: true
   * Id: 42598604-047d-4cb1-8979-33fe1a6dfc52
   * Codename: heading_4259860
   */
  heading4259860: Elements.TextElement;

  /**
   * Text (rich_text)
   * Required: true
   * Id: 9fd2eb5f-d097-4d86-b2ae-e43e4551dbb7
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * CTA Banner (modular_content)
   * Required: false
   * Id: 5d948ca1-76c4-4b58-8b94-07c982d1987d
   * Codename: cta_banner
   */
  ctaBanner: Elements.LinkedItemsElement<CtaBannerComponentModel>;
}> &
  HeroKK &
  Metadata &
  SitemapMetadata;
