import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { SharedContentModel } from './SharedContentModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Enhanced Content Block
 * Id: 2807b1ff-f2bb-4dc1-be2e-8510ed812a1f
 * Codename: enhanced_content_block
 */
export type EnhancedContentBlockModel = IContentItem<{
  /**
   * Heading (rich_text)
   * Required: false
   * Id: 962f7821-da0d-42ac-a763-2df65a78c8dc
   * Codename: heading
   */
  heading: Elements.RichTextElement;

  /**
   * Description (rich_text)
   * Required: false
   * Id: 15b718f3-52e8-4065-99ea-db948dd30794
   * Codename: description
   */
  description: Elements.RichTextElement;

  /**
   * Image (asset)
   * Required: false
   * Id: 325d526e-18db-44d4-933d-aec6c8fc291a
   * Codename: image
   */
  image: Elements.AssetsElement;

  /**
   * CTA (modular_content)
   * Required: false
   * Id: bde1af7d-298b-4081-a4a0-1c9a1f346522
   * Codename: cta
   */
  cta: Elements.LinkedItemsElement<SharedContentModel>;
}>;
