import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { AuthorModel } from './AuthorModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Event Talk
 * Id: 4ffe27f3-3027-4b4d-8701-5583cc7bea76
 * Codename: event_talk
 */
export type EventTalkModel = IContentItem<{
  /**
   * Title (text)
   * Required: true
   * Id: 3e73bf2a-b2c6-4da8-afdc-d7834dbac9e5
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Author (modular_content)
   * Required: true
   * Id: 97ad906d-9850-487f-bc54-53cdc5a8d9ff
   * Codename: author
   */
  author: Elements.LinkedItemsElement<AuthorModel>;

  /**
   * Duration (number)
   * Required: true
   * Id: cf5dcc59-34bc-486d-80cf-9dcfeea3cba2
   * Codename: duration
   *
   * Duration of the talk in minutes.
   */
  duration: Elements.NumberElement;
}>;
