import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { EventDateModel } from './EventDateModel';
import { AuthorModel } from './AuthorModel';
import { PartnerModel } from './PartnerModel';
import { Metadata } from '../content-type-snippets/metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Event
 * Id: ae6cab38-500c-4fbd-a620-4456afd16e98
 * Codename: event
 */
export type EventModel = IContentItem<{
  /**
   * Title (text)
   * Required: true
   * Id: c2f39b6f-ec7c-4c80-847b-a481898ebd35
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Overview (rich_text)
   * Required: true
   * Id: e24ea59f-12e8-488b-ba7a-c2bc12e5fd35
   * Codename: overview
   *
   * Short summary of the event (displayed on the event card)
   */
  overview: Elements.RichTextElement;

  /**
   * Description (rich_text)
   * Required: false
   * Id: 2617b0ad-a391-42de-8bb3-41fbf22c0737
   * Codename: description
   */
  description: Elements.RichTextElement;

  /**
   * Dates (modular_content)
   * Required: true
   * Id: b0174a90-efce-416d-abb4-8fbad9d2fa1b
   * Codename: dates
   */
  dates: Elements.LinkedItemsElement<EventDateModel>;

  /**
   * Speakers (modular_content)
   * Required: false
   * Id: 11550580-9e14-4659-9c54-1a3c02bfe50d
   * Codename: speakers
   *
   * Speakers for this event
   */
  speakers: Elements.LinkedItemsElement<AuthorModel>;

  /**
   * Partnership (modular_content)
   * Required: false
   * Id: 66f6bea7-5d85-4e25-87bb-e0e40856b3d8
   * Codename: partnership
   *
   * Partner for this event
   */
  partnership: Elements.LinkedItemsElement<PartnerModel>;

  /**
   * Wrap Up (rich_text)
   * Required: false
   * Id: b10493c2-1822-44e7-ad29-c63138ff6955
   * Codename: wrap_up
   *
   * Post-event wrap-up
   */
  wrapUp: Elements.RichTextElement;

  /**
   * Registration URL (text)
   * Required: false
   * Id: b269ac44-2ca2-44a6-8497-2f9547b2dc7e
   * Codename: registration_url
   *
   * Used for external webinars
   */
  registrationUrl: Elements.TextElement;

  /**
   * Recording URL (text)
   * Required: false
   * Id: a14016b0-4592-4071-9209-864ad4686f4f
   * Codename: recording_url
   *
   * Recording/video from a past event. Use this format: https://www.youtube.com/watch?v=J3XRGtUeGXc
   */
  recordingUrl: Elements.TextElement;

  /**
   * URL Slug (url_slug)
   * Required: true
   * Id: f80bdae2-ad52-4a59-a4d7-882b77f7f53d
   * Codename: url_slug
   *
   * URL slug for this webinar (e.g. /horizons-2022)
   */
  urlSlug: Elements.UrlSlugElement;

  /**
   * Previously used URL slugs (custom)
   * Required: false
   * Id: fe03bffd-0f33-4503-bac6-836dad82d8b9
   * Codename: previously_used_url_slugs
   */
  previouslyUsedUrlSlugs: Elements.CustomElement;

  /**
   * Schema.org description (text)
   * Required: false
   * Id: 95c3fa63-2e41-48d1-a03c-6da4950bf93f
   * Codename: schema_org_description
   */
  schemaOrgDescription: Elements.TextElement;

  /**
   * Card image (asset)
   * Required: true
   * Id: c8227e44-8129-44b4-87e3-cafe9663bdde
   * Codename: card_image
   *
   * A smaller image used for the card on the webinars page.DISCLAIMER: If the event is used in the featured section at /events-and-webinars as the HORIZONTAL card - you need to use 2 images. 1st image will be used for a standard card (on smaller viewports and in the standard listing) and the 2nd image (narrower) will be used for the horizontal card.
   */
  cardImage: Elements.AssetsElement;

  /**
   * Image strip image (asset)
   * Required: false
   * Id: 51c67211-7995-41a4-b5bd-f3316c38acff
   * Codename: image_strip_image
   *
   * Optional full-width image black and white image used on the webinar detail page.
   */
  imageStripImage: Elements.AssetsElement;

  /**
   * Hero image (asset)
   * Required: false
   * Id: 52432d81-fdae-49fe-bc82-6b522e6da05a
   * Codename: hero_image
   *
   * Optional hero image used on the webinar detail page with a petal (if there's no image strip). If no image strip or hero image is provided, only the petal will be shown.
   */
  heroImage: Elements.AssetsElement;

  /**
   * Recording poster (asset)
   * Required: false
   * Id: 13b5858c-27bf-4418-b79e-f942ed777099
   * Codename: recording_poster
   */
  recordingPoster: Elements.AssetsElement;
}> &
  Metadata;
