import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { EventDateModel } from './EventDateModel';
import { Metadata } from '../content-type-snippets/metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Event
 * Id: ae6cab38-500c-4fbd-a620-4456afd16e98
 * Codename: event
 */
export type EventModel = IContentItem<{
  /**
   * Title (text)
   * Required: true
   * Id: c2f39b6f-ec7c-4c80-847b-a481898ebd35
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Description (rich_text)
   * Required: true
   * Id: 2617b0ad-a391-42de-8bb3-41fbf22c0737
   * Codename: description
   */
  description: Elements.RichTextElement;

  /**
   * Header Image (asset)
   * Required: false
   * Id: f82d8089-9b74-45c3-90e2-b7ce5836a2df
   * Codename: header_image
   *
   * Ideal size: 1165x280
   */
  headerImage: Elements.AssetsElement;

  /**
   * Dates (modular_content)
   * Required: true
   * Id: b0174a90-efce-416d-abb4-8fbad9d2fa1b
   * Codename: dates
   */
  dates: Elements.LinkedItemsElement<EventDateModel>;

  /**
   * Sticky (multiple_choice)
   * Required: true
   * Id: 3eb39339-d0d0-4d8e-8e1f-0383ce79e20f
   * Codename: sticky
   *
   * Moves this particular event to the top of the list at /webinars
   */
  sticky: Elements.MultipleChoiceElement;

  /**
   * Schema.org description (text)
   * Required: false
   * Id: 95c3fa63-2e41-48d1-a03c-6da4950bf93f
   * Codename: schema_org_description
   */
  schemaOrgDescription: Elements.TextElement;
}> &
  Metadata;
