import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { AddressModel } from './AddressModel';
import { TimeZoneModel } from './TimeZoneModel';
import { EventTalkModel } from './EventTalkModel';
import { UmlpModel } from './UmlpModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Event Date
 * Id: a15190d2-7921-4d63-a5fb-4f90ec3ec969
 * Codename: event_date
 */
export type EventDateModel = IContentItem<{
  /**
   * Location (text)
   * Required: true
   * Id: f1714b9b-791b-4bca-b13e-dc803dbffe40
   * Codename: location
   */
  location: Elements.TextElement;

  /**
   * Start Date and Time (date_time)
   * Required: false
   * Id: b2254252-bf98-4be2-990f-5863b5087c18
   * Codename: start_date_and_time
   */
  startDateAndTime: Elements.DateTimeElement;

  /**
   * End Date and Time (date_time)
   * Required: false
   * Id: beb0e806-f2f3-475e-8536-153a93e6b4a3
   * Codename: end_date_and_time
   */
  endDateAndTime: Elements.DateTimeElement;

  /**
   * Venue (modular_content)
   * Required: false
   * Id: 718142a6-be27-493d-916c-861e0f67eba8
   * Codename: venue
   */
  venue: Elements.LinkedItemsElement<AddressModel>;

  /**
   * Time zone (modular_content)
   * Required: true
   * Id: aa996888-5f45-4e5a-9c2b-082f34854928
   * Codename: time_zone
   */
  timeZone: Elements.LinkedItemsElement<TimeZoneModel>;

  /**
   * Agenda (modular_content)
   * Required: false
   * Id: 02010363-dac4-4854-be86-0682137ac8bb
   * Codename: agenda
   */
  agenda: Elements.LinkedItemsElement<EventTalkModel>;

  /**
   * Pardot URL (text)
   * Required: false
   * Id: 64f93c18-f857-4972-b348-78b12af9d778
   * Codename: pardot_url
   *
   * Pardot iframe URL, ie. https://tracker.kontent.ai/l/849473/2020-03-04/2kny
   */
  pardotUrl: Elements.TextElement;

  /**
   * Related UMLP page (modular_content)
   * Required: false
   * Id: 0868f83c-466c-4814-9caa-77c852b3260e
   * Codename: related_umlp_page
   *
   * UMLP page for a given event. Used on /horizons - generates "Choose location" section.
   */
  relatedUmlpPage: Elements.LinkedItemsElement<UmlpModel>;

  /**
   * Registration open (multiple_choice)
   * Required: true
   * Id: bf62face-9d75-4dc2-b17a-516e26cf8f80
   * Codename: registration_open
   */
  registrationOpen: Elements.MultipleChoiceElement;
}>;
