import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { AuthorModel } from './AuthorModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Event Talk
 * Id: 4ffe27f3-3027-4b4d-8701-5583cc7bea76
 * Codename: event_talk
 */
export type EventTalkModel = IContentItem<{
  /**
   * Title (text)
   * Required: true
   * Id: 3e73bf2a-b2c6-4da8-afdc-d7834dbac9e5
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Author (modular_content)
   * Required: false
   * Id: 97ad906d-9850-487f-bc54-53cdc5a8d9ff
   * Codename: author
   */
  author: Elements.LinkedItemsElement<AuthorModel>;

  /**
   * Duration (number)
   * Required: true
   * Id: cf5dcc59-34bc-486d-80cf-9dcfeea3cba2
   * Codename: duration
   *
   * Duration of the talk in minutes.
   */
  duration: Elements.NumberElement;

  /**
   * YouTube Video ID (text)
   * Required: false
   * Id: fa132e13-3ae2-4093-9252-90fb9a879a93
   * Codename: youtube_video_id
   *
   * Supported ID format - BZYuEniknLg
   */
  youtubeVideoId: Elements.TextElement;

  /**
   * Video poster (asset)
   * Required: false
   * Id: 34196a0c-bbdc-4428-bf8d-66ba047e92d5
   * Codename: video_poster
   */
  videoPoster: Elements.AssetsElement;

  /**
   * Expand button text (text)
   * Required: false
   * Id: aedb967b-0dee-40a8-b11c-68833e4a4c2b
   * Codename: expand_button_text
   */
  expandButtonText: Elements.TextElement;
}>;
