import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { SharedContentModel } from './SharedContentModel';
import { ReleaseProjects } from '../taxonomies/release_projects';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Experience
 * Id: 0f12e313-0582-411f-a75c-67e6a5d9fc6b
 * Codename: experience
 */
export type ExperienceModel = IContentItem<{
  /**
   * Title (text)
   * Required: true
   * Id: bbeb5aa2-c5f1-43c3-a4f2-d1a0709e04a9
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Description (rich_text)
   * Required: true
   * Id: bcb0dba5-ad6c-449c-844f-fbb67f78210b
   * Codename: description
   */
  description: Elements.RichTextElement;

  /**
   * CTA (modular_content)
   * Required: true
   * Id: f7b7c012-8fa2-4ea0-b787-d03a0a3586e6
   * Codename: cta
   */
  cta: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Logo (asset)
   * Required: false
   * Id: 3ed66e27-30bc-4443-9eb0-dac6d651c885
   * Codename: logo
   */
  logo: Elements.AssetsElement;

  /**
   * Logo 2x (asset)
   * Required: false
   * Id: 8233f62a-c357-42e8-a0dd-b23736495fe7
   * Codename: logo_2x
   */
  logo2x: Elements.AssetsElement;

  /**
   * Preview desktop (asset)
   * Required: false
   * Id: c783365f-9c6e-4f44-98f1-4e43122a6249
   * Codename: preview_desktop
   */
  previewDesktop: Elements.AssetsElement;

  /**
   * Preview desktop 2x (asset)
   * Required: false
   * Id: 285556fb-89b6-4ad2-ac45-44416ca8ea82
   * Codename: preview_desktop_2x
   */
  previewDesktop2x: Elements.AssetsElement;

  /**
   * Preview mobile (asset)
   * Required: false
   * Id: 5780c29f-1651-408d-8853-e61ae1fbe3bc
   * Codename: preview_mobile
   */
  previewMobile: Elements.AssetsElement;

  /**
   * Preview mobile 2x (asset)
   * Required: false
   * Id: d147259f-e77d-43fb-b64b-970d9061e49e
   * Codename: preview_mobile_2x
   */
  previewMobile2x: Elements.AssetsElement;

  /**
   * Background type (multiple_choice)
   * Required: true
   * Id: 2f5c7dc4-08db-4e89-8742-c673331e8ed5
   * Codename: background_type
   */
  backgroundType: Elements.MultipleChoiceElement;

  /**
   * Release projects (taxonomy)
   * Required: false
   * Id: 002ca098-c1ac-480c-9157-41649cd1be45
   * Codename: release_projects
   */
  releaseProjects: Elements.TaxonomyElement<ReleaseProjects>;

  /**
   * Anchor id (url_slug)
   * Required: false
   * Id: 4f6f46c2-0d6b-4748-b2d2-63d04f12653b
   * Codename: anchor_id
   */
  anchorId: Elements.UrlSlugElement;
}>;
