import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * File
 * Id: 011d5bb4-b484-4829-9d2a-e6d6085e794a
 * Codename: file
 */
export type FileModel = IContentItem<{
  /**
   * Logo (asset)
   * Required: false
   * Id: b24f17e3-e5d3-42d3-b5f3-74433df0756d
   * Codename: logo
   */
  logo: Elements.AssetsElement;

  /**
   * Downloadable file (asset)
   * Required: true
   * Id: 47448a90-4aaf-e68a-2ddc-89c94f80f6c1
   * Codename: downloadable_file
   */
  downloadableFile: Elements.AssetsElement;

  /**
   * Caption (text)
   * Required: false
   * Id: c441643c-7114-a3d5-a0aa-d7e35700ba47
   * Codename: caption
   *
   * Caption will be used as a link text when using as modular content within rich text.
   */
  caption: Elements.TextElement;
}>;
