import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { SharedContentModel } from './SharedContentModel';
import { FooterItemModel } from './FooterItemModel';
import { ReleaseProjects } from '../taxonomies/release_projects';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Footer Dynamic
 * Id: 12fbec98-3d27-4e24-85be-2f577b25bf85
 * Codename: footer_kk
 */
export type FooterKkModel = IContentItem<{
  /**
   * Hello headline (rich_text)
   * Required: false
   * Id: f3100219-d0fd-4e59-a864-27c84e7dd835
   * Codename: hello_headline
   */
  helloHeadline: Elements.RichTextElement;

  /**
   * Hello CTA (modular_content)
   * Required: false
   * Id: 229bd232-b3ae-4452-a8d6-631efc3fde1f
   * Codename: hello_cta
   */
  helloCta: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Copyright items 1 (modular_content)
   * Required: false
   * Id: 5c4d2272-6159-412b-839e-0b836db871db
   * Codename: copyright_items_1
   */
  copyrightItems1: Elements.LinkedItemsElement<FooterItemModel>;

  /**
   * Copyright items 2 (modular_content)
   * Required: false
   * Id: af2c38b7-388a-4a96-998d-0416bf33c6db
   * Codename: copyright_items_2
   */
  copyrightItems2: Elements.LinkedItemsElement<FooterItemModel>;

  /**
   * Release projects (taxonomy)
   * Required: false
   * Id: 83d979e6-201b-423f-b539-78172633a8a3
   * Codename: release_projects
   */
  releaseProjects: Elements.TaxonomyElement<ReleaseProjects>;
}>;
