import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Free authoring
 * Id: 0fa98bba-2d28-42dc-a281-5e1a67d34bb3
 * Codename: free_authoring
 */
export type FreeAuthoringModel = IContentItem<{
  /**
   * Be bold, be creative (rich_text)
   * Required: false
   * Id: 74642205-af0f-4839-a9a4-1d2b52897189
   * Codename: be_bold__be_creative
   */
  beBoldBeCreative: Elements.RichTextElement;
}>;
