import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { ConsentElementModel } from './ConsentElementModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Get a quote form
 * Id: 58f3f5a4-4489-4953-bf3c-8d6b1cee0818
 * Codename: get_a_quote_form
 */
export type GetAQuoteFormModel = IContentItem<{
  /**
   * Form next step info (rich_text)
   * Required: false
   * Id: 1bf63010-0afd-4800-989a-0df0178aa2d4
   * Codename: form_next_step_info
   */
  formNextStepInfo: Elements.RichTextElement;

  /**
   * Consent elements (modular_content)
   * Required: false
   * Id: 2d9bdaec-2029-4126-823f-a69763e96ad4
   * Codename: consent_elements
   */
  consentElements: Elements.LinkedItemsElement<ConsentElementModel>;
}>;
