import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { ConsentElementModel } from './ConsentElementModel';
import { OptInUnlessOptOutFormElementModel } from './OptInUnlessOptOutFormElementModel';
import { Metadata } from '../content-type-snippets/metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Headless CMS Survey landing page B
 * Id: d7a6e3cc-ac70-41fa-8cde-1fd4fcf533fd
 * Codename: headless_cms_survey_landing_page_b
 */
export type HeadlessCmsSurveyLandingPageBModel = IContentItem<{
  /**
   * Main title first part (text)
   * Required: false
   * Id: 07e0f4d1-5451-4673-9096-9da966193b64
   * Codename: main_title_first_part
   */
  mainTitleFirstPart: Elements.TextElement;

  /**
   * Main title second part (text)
   * Required: false
   * Id: 92e934f9-5545-4526-a9ec-3b52252cc8db
   * Codename: main_title_second_part
   */
  mainTitleSecondPart: Elements.TextElement;

  /**
   * Main subtitle (text)
   * Required: false
   * Id: 91498662-ac12-45e7-9591-0b60106124e8
   * Codename: main_subtitle
   */
  mainSubtitle: Elements.TextElement;

  /**
   * Teaser image (asset)
   * Required: false
   * Id: 3f69edd9-a8c0-4ae2-8648-8c1f24dee32f
   * Codename: teaser_image
   */
  teaserImage: Elements.AssetsElement;

  /**
   * Teaser text (rich_text)
   * Required: false
   * Id: 8ceb1a1f-082c-4020-ad90-fcf9d80ca208
   * Codename: teaser_text
   */
  teaserText: Elements.RichTextElement;

  /**
   * Form title (text)
   * Required: false
   * Id: 2372e283-1358-40fa-b73b-b5f06808c9fa
   * Codename: form_title
   */
  formTitle: Elements.TextElement;

  /**
   * Subscribe to newsletter (text)
   * Required: false
   * Id: 79345243-0023-4d6c-bf39-a0c8a3d7a7c6
   * Codename: subscribe_to_newsletter
   */
  subscribeToNewsletter: Elements.TextElement;

  /**
   * Consent elements (modular_content)
   * Required: false
   * Id: df6607a5-a8b6-45d8-ab2c-a834536f36e6
   * Codename: consent_elements
   */
  consentElements: Elements.LinkedItemsElement<ConsentElementModel>;

  /**
   * Opt in unless opt out form element (modular_content)
   * Required: false
   * Id: 457df174-33fc-475a-b4c4-f15ea2d2b062
   * Codename: opt_in_unless_opt_out_form_element
   */
  optInUnlessOptOutFormElement: Elements.LinkedItemsElement<OptInUnlessOptOutFormElementModel>;

  /**
   * Report PDF (asset)
   * Required: false
   * Id: c4523543-7fca-49fb-a4e1-76766244561d
   * Codename: report_pdf
   */
  reportPdf: Elements.AssetsElement;

  /**
   * Report PPT (asset)
   * Required: false
   * Id: bb74824e-f99b-4e83-8c58-a023e054edaa
   * Codename: report_ppt
   */
  reportPpt: Elements.AssetsElement;

  /**
   * Report Thank You title (text)
   * Required: false
   * Id: 08142ca2-8b51-4549-b740-c5dfe58c3d99
   * Codename: report_thank_you_title
   */
  reportThankYouTitle: Elements.TextElement;

  /**
   * Report Thank You text (rich_text)
   * Required: false
   * Id: 8877af84-d8e9-4762-9df5-57e82ed83bf4
   * Codename: report_thank_you_text
   */
  reportThankYouText: Elements.RichTextElement;

  /**
   * Open Graph Image (asset)
   * Required: false
   * Id: 508dbd09-6301-4007-8df2-7b499d5fb477
   * Codename: open_graph_image
   */
  openGraphImage: Elements.AssetsElement;
}> &
  Metadata;
