import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { SharedContentModel } from './SharedContentModel';
import { LogoModel } from './LogoModel';
import { HighlightedFeatureModel } from './HighlightedFeatureModel';
import { FeatureModel } from './FeatureModel';
import { TestimonialModel } from './TestimonialModel';
import { ModularItemCardElementModel } from './ModularItemCardElementModel';
import { TabItemModel } from './TabItemModel';
import { UmlpElementAchievementsModel } from './UmlpElementAchievementsModel';
import { ResourceModel } from './ResourceModel';
import { Metadata } from '../content-type-snippets/metadata';
import { Opengraph } from '../content-type-snippets/opengraph';
import { ReleaseProjects } from '../taxonomies/release_projects';
import { SitemapMetadata } from '../content-type-snippets/sitemap_metadata';
import { CtaBannerComponentModel } from './CtaBannerComponentModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Home page
 * Id: f54e0c26-84ba-41eb-8144-6189f81e1e68
 * Codename: home_page
 */
export type HomePageModel = IContentItem<{
  /**
   * Hero headline (rich_text)
   * Required: false
   * Id: d9da5688-1c8f-4a78-b956-c718c2170f3b
   * Codename: hero_headline
   */
  heroHeadline: Elements.RichTextElement;

  /**
   * Hero lead paragraph (rich_text)
   * Required: false
   * Id: a922f43a-9ca4-4d4f-9b32-921457c09b02
   * Codename: hero_lead_paragraph
   */
  heroLeadParagraph: Elements.RichTextElement;

  /**
   * Hero primary CTA (modular_content)
   * Required: true
   * Id: 753028c8-8f6c-4ff9-aee8-3165f4c3e6a8
   * Codename: hero_primary_cta
   */
  heroPrimaryCta: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Hero secondary CTA (modular_content)
   * Required: true
   * Id: 2daba563-9280-4c1a-9936-d123e371dd92
   * Codename: hero_secondary_cta
   */
  heroSecondaryCta: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Hero CTA separator (text)
   * Required: false
   * Id: 1c5892d9-264e-4905-aa51-50be44d63e89
   * Codename: hero_cta_separator
   */
  heroCtaSeparator: Elements.TextElement;

  /**
   * Hero image (asset)
   * Required: true
   * Id: ce270d0a-210c-4b39-9704-291683c0914e
   * Codename: hero_image
   */
  heroImage: Elements.AssetsElement;

  /**
   * Logos (modular_content)
   * Required: false
   * Id: f61ec176-dc43-4c62-a0b4-f8847bdf996c
   * Codename: logos
   */
  logos: Elements.LinkedItemsElement<LogoModel>;

  /**
   * Highlighted Feature (modular_content)
   * Required: false
   * Id: 4e9f0163-892a-4387-8ec4-5e14e3d74cc2
   * Codename: highlighted_feature
   */
  highlightedFeature: Elements.LinkedItemsElement<HighlightedFeatureModel>;

  /**
   * Features - Content-as-a-Service (modular_content)
   * Required: false
   * Id: 0095c009-1680-4670-a759-0cd465c91b6c
   * Codename: features_caas
   */
  featuresCaas: Elements.LinkedItemsElement<FeatureModel>;

  /**
   * Features - Headless CMS (modular_content)
   * Required: false
   * Id: 081bc84b-2e14-4236-a46e-2f93ddef4e9e
   * Codename: features_headless_cms
   */
  featuresHeadlessCms: Elements.LinkedItemsElement<FeatureModel>;

  /**
   * Testimonials (modular_content)
   * Required: false
   * Id: 326b00c3-bf5e-4ff6-889f-6026d088ccfa
   * Codename: testimonials
   */
  testimonials: Elements.LinkedItemsElement<TestimonialModel>;

  /**
   * Cards (modular_content)
   * Required: false
   * Id: 0ee1a074-9d21-497c-9037-87b2b0f58b9b
   * Codename: cards
   */
  cards: Elements.LinkedItemsElement<ModularItemCardElementModel>;

  /**
   * Schema headline (rich_text)
   * Required: false
   * Id: b0f5324b-9b9f-43b1-b8d2-3573f0de369c
   * Codename: schema_headline
   */
  schemaHeadline: Elements.RichTextElement;

  /**
   * Schema lead paragraph (rich_text)
   * Required: false
   * Id: 6450d24a-ded0-4f82-a43d-14472b29d23f
   * Codename: schema_lead_paragraph
   */
  schemaLeadParagraph: Elements.RichTextElement;

  /**
   * Heading (text)
   * Required: false
   * Id: a2b120b3-661c-4620-b5e8-b50d9118b9a6
   * Codename: heading_solutions
   */
  headingSolutions: Elements.TextElement;

  /**
   * Tabs (modular_content)
   * Required: false
   * Id: 9df582ec-fec5-4b8b-add8-1e6c74e04f10
   * Codename: tabs
   */
  tabs: Elements.LinkedItemsElement<TabItemModel>;

  /**
   * Achievements (modular_content)
   * Required: false
   * Id: 30aa4d3c-8b35-430c-989b-d96ec3b93da2
   * Codename: achievements
   */
  achievements: Elements.LinkedItemsElement<UmlpElementAchievementsModel>;

  /**
   * Heading (text)
   * Required: false
   * Id: d55d34b8-ee66-4b56-bcd8-ab52ac418fd5
   * Codename: heading_resources
   */
  headingResources: Elements.TextElement;

  /**
   * Resources (modular_content)
   * Required: false
   * Id: 62b40b1c-226b-4ce3-badf-dfeebf993d7d
   * Codename: resources
   */
  resources: Elements.LinkedItemsElement<ResourceModel>;

  /**
   * Release projects (taxonomy)
   * Required: false
   * Id: 007b6fe2-c71e-49b5-a115-2219c4a0771a
   * Codename: release_projects
   */
  releaseProjects: Elements.TaxonomyElement<ReleaseProjects>;

  /**
   * CTA Section (modular_content)
   * Required: false
   * Id: 86dbf4da-1365-484d-a863-5899e48b4d45
   * Codename: cta_section
   */
  ctaSection: Elements.LinkedItemsElement<CtaBannerComponentModel>;
}> &
  Metadata &
  Opengraph &
  SitemapMetadata;
