import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { AddressModel } from './AddressModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Horizons - Venue Section
 * Id: 362f25dc-6578-4f70-80b3-db6c2eac9b6a
 * Codename: horizons___venue_section
 */
export type HorizonsVenueSectionModel = IContentItem<{
  /**
   * Section alias (text)
   * Required: true
   * Id: caa3ca58-0032-4ab1-8470-74e97446bc61
   * Codename: section_alias
   *
   * e.g. "About", "Flashback" or "Sponsors" - will be used to dynamically create navigation
   */
  sectionAlias: Elements.TextElement;

  /**
   * URL anchor (text)
   * Required: true
   * Id: d6ad9750-714c-4132-b8ef-4c7e4fbf88a2
   * Codename: url_anchor
   *
   * Section ID which will be visible in the URL upon clicking the nav link. E.g. "sponsors" will resolve to https://kontent.ai/horizons/#sponsors
   */
  urlAnchor: Elements.TextElement;

  /**
   * Venue (modular_content)
   * Required: true
   * Id: 229ffbb6-da27-465c-8234-81ca62d72d1b
   * Codename: venue
   */
  venue: Elements.LinkedItemsElement<AddressModel>;

  /**
   * Venue image (asset)
   * Required: true
   * Id: 86f57a57-1e4d-40ff-93f4-f8626286d396
   * Codename: venue_image
   *
   * Landscape image 1920x800
   */
  venueImage: Elements.AssetsElement;
}>;
