import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { PartnerModel } from './PartnerModel';
import { AuthorModel } from './AuthorModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Horizons Page
 * Id: c987b700-9f1b-4b93-a44b-df9cd614e173
 * Codename: horizons_page
 */
export type HorizonsPageModel = IContentItem<{
  /**
   * Gold sponsors (modular_content)
   * Required: false
   * Id: 3d0183b1-88c9-4738-ae83-0accc384af65
   * Codename: gold_sponsors
   */
  goldSponsors: Elements.LinkedItemsElement<PartnerModel>;

  /**
   * Silver sponsors (modular_content)
   * Required: false
   * Id: af722521-bd77-41b6-8408-0aceddf21069
   * Codename: silver_sponsors
   */
  silverSponsors: Elements.LinkedItemsElement<PartnerModel>;

  /**
   * Bronze sponsors (modular_content)
   * Required: false
   * Id: 6133aa04-12fc-4447-8ec4-4e8d2753c361
   * Codename: bronze_sponsors
   */
  bronzeSponsors: Elements.LinkedItemsElement<PartnerModel>;

  /**
   * Speakers (modular_content)
   * Required: false
   * Id: e203f39e-6b55-43ae-b519-85121c8d6d0b
   * Codename: speakers
   */
  speakers: Elements.LinkedItemsElement<AuthorModel>;

  /**
   * Heading (text)
   * Required: true
   * Id: 46d18ecd-8b04-4928-99f7-b59ae8d3ca26
   * Codename: venues_heading
   */
  venuesHeading: Elements.TextElement;

  /**
   * Description (rich_text)
   * Required: true
   * Id: a45a2d64-4a3a-4644-92fa-abc5c5a46b35
   * Codename: venues_description
   */
  venuesDescription: Elements.RichTextElement;

  /**
   * Image (asset)
   * Required: true
   * Id: b47fa252-c00d-4239-9b30-7e64a0318e78
   * Codename: venues_image
   */
  venuesImage: Elements.AssetsElement;
}>;
