import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { PlainTextModel } from './PlainTextModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Horizons - Social Feed
 * Id: 58143ab6-15b4-45b3-bafe-f9e6fb58108d
 * Codename: horizons___social_feed
 */
export type HorizonsSocialFeedModel = IContentItem<{
  /**
   * Section alias (text)
   * Required: true
   * Id: f313deb0-b6e8-4c00-be41-b4a952dc635d
   * Codename: section_alias
   *
   * e.g. "About", "Flashback" or "Sponsors" - will be used to dynamically create navigation
   */
  sectionAlias: Elements.TextElement;

  /**
   * URL anchor (text)
   * Required: true
   * Id: a094fc1b-e556-4604-8e8b-2a8821dd4628
   * Codename: url_anchor
   *
   * Section ID which will be visible in the URL upon clicking the nav link. E.g. "sponsors" will resolve to https://kontent.ai/horizons/#sponsors
   */
  urlAnchor: Elements.TextElement;

  /**
   * Heading (text)
   * Required: true
   * Id: 014dd52a-9654-4248-a2a8-78738cb5bb8b
   * Codename: heading
   */
  heading: Elements.TextElement;

  /**
   * Tweet IDs (modular_content)
   * Required: true
   * Id: 746729d6-871e-43ca-b5ee-025498247146
   * Codename: tweet_ids
   */
  tweetIds: Elements.LinkedItemsElement<PlainTextModel>;
}>;
