import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { PartnerModel } from './PartnerModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Horizons - Sponsors
 * Id: 4ca71e53-ee6f-431f-8a08-0d8f58e9bc79
 * Codename: horizons___sponsors
 */
export type HorizonsSponsorsModel = IContentItem<{
  /**
   * Section alias (text)
   * Required: true
   * Id: 0ad50cb0-2fff-467a-87e9-25c2ce076e02
   * Codename: section_alias
   *
   * e.g. "About", "Flashback" or "Sponsors" - will be used to dynamically create navigation
   */
  sectionAlias: Elements.TextElement;

  /**
   * URL anchor (text)
   * Required: true
   * Id: 30deeeb0-f0b7-484e-bf4b-06f50e098646
   * Codename: url_anchor
   *
   * Section ID which will be visible in the URL upon clicking the nav link. E.g. "sponsors" will resolve to https://kontent.ai/horizons/#sponsors
   */
  urlAnchor: Elements.TextElement;

  /**
   * Heading (text)
   * Required: true
   * Id: 144899de-016a-42b5-8117-0cb1eb6ab29b
   * Codename: heading
   */
  heading: Elements.TextElement;

  /**
   * Gold (modular_content)
   * Required: false
   * Id: f4e85390-eab9-463d-9aa4-bd432b5cde30
   * Codename: gold
   */
  gold: Elements.LinkedItemsElement<PartnerModel>;

  /**
   * Silver (modular_content)
   * Required: false
   * Id: bb189d42-a022-4f05-b562-d94aab048660
   * Codename: silver
   */
  silver: Elements.LinkedItemsElement<PartnerModel>;

  /**
   * Bronze (modular_content)
   * Required: false
   * Id: 6d8bda03-6791-4245-a098-e7c026ff7a30
   * Codename: bronze
   */
  bronze: Elements.LinkedItemsElement<PartnerModel>;
}>;
