import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { EventModel } from './EventModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Horizons - Agenda
 * Id: 989dc476-a67f-4f30-9e51-a4678a525a7e
 * Codename: horizons___agenda
 */
export type HorizonsAgendaModel = IContentItem<{
  /**
   * Section alias (text)
   * Required: true
   * Id: 37d7748f-e883-43a0-b07b-aef7e6c5cd4e
   * Codename: section_alias
   *
   * e.g. "About", "Flashback" or "Sponsors" - will be used to dynamically create navigation
   */
  sectionAlias: Elements.TextElement;

  /**
   * URL anchor (text)
   * Required: true
   * Id: 42a6b626-bfa6-4886-ba4b-0ee868758192
   * Codename: url_anchor
   *
   * Section ID which will be visible in the URL upon clicking the nav link. E.g. "sponsors" will resolve to https://kontent.ai/horizons/#sponsors
   */
  urlAnchor: Elements.TextElement;

  /**
   * Heading (text)
   * Required: true
   * Id: 71b59923-438f-4db2-a285-d457a2683349
   * Codename: heading
   */
  heading: Elements.TextElement;

  /**
   * Event (modular_content)
   * Required: false
   * Id: cf13091f-24b9-430f-924e-ed42e8ccd7d6
   * Codename: event
   */
  event: Elements.LinkedItemsElement<EventModel>;
}>;
