import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { EventDateModel } from './EventDateModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Horizons - Hero Section
 * Id: 5cb05e77-9962-4300-9298-f0882350f14c
 * Codename: horizons___hero_section
 */
export type HorizonsHeroSectionModel = IContentItem<{
  /**
   * Section alias (text)
   * Required: true
   * Id: 74ab716a-6870-432a-9a27-e2cc53b5c727
   * Codename: section_alias
   *
   * e.g. "About", "Flashback" or "Sponsors" - will be used to dynamically create navigation
   */
  sectionAlias: Elements.TextElement;

  /**
   * URL anchor (text)
   * Required: true
   * Id: 85174554-4d2b-4105-96a6-4d1bfe5a5c8d
   * Codename: url_anchor
   *
   * Section ID which will be visible in the URL upon clicking the nav link. E.g. "sponsors" will resolve to https://kontent.ai/horizons/#sponsors
   */
  urlAnchor: Elements.TextElement;

  /**
   * Heading (text)
   * Required: true
   * Id: 72b73cf6-41ab-4ac1-bea1-8a70d140133e
   * Codename: heading
   */
  heading: Elements.TextElement;

  /**
   * Text (rich_text)
   * Required: true
   * Id: 6f0d48e4-7cff-4aae-bd96-23d93311d736
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * CTA button text (text)
   * Required: true
   * Id: 85674e20-953a-4121-9e69-42e4b38be0c6
   * Codename: cta_button_text
   */
  ctaButtonText: Elements.TextElement;

  /**
   * Image (asset)
   * Required: true
   * Id: ba27a59e-f092-4ff2-91ea-0b93e9cf19dc
   * Codename: image
   */
  image: Elements.AssetsElement;

  /**
   * Event date (modular_content)
   * Required: false
   * Id: d80c8ec3-232d-4b69-a862-9b21bcba5199
   * Codename: event_date
   */
  eventDate: Elements.LinkedItemsElement<EventDateModel>;
}>;
