import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { AuthorModel } from './AuthorModel';
import { Metadata } from '../content-type-snippets/metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Internal Press Release
 * Id: 846d456f-1113-4cf9-b9f0-c62a7976d9b4
 * Codename: internal_press_release
 */
export type InternalPressReleaseModel = IContentItem<{
  /**
   * Title (text)
   * Required: true
   * Id: 894f34a5-9914-4191-ad7d-55af020fb5f5
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Lead Paragraph (rich_text)
   * Required: true
   * Id: 8da33f48-de5e-4067-a764-fcf424ff496b
   * Codename: lead_paragraph
   */
  leadParagraph: Elements.RichTextElement;

  /**
   * Body (rich_text)
   * Required: true
   * Id: c200daca-28a0-46f0-9fc2-abdc2fd54cc4
   * Codename: body
   */
  body: Elements.RichTextElement;

  /**
   * Image (asset)
   * Required: true
   * Id: 4fe01ffc-2de1-4343-839d-77edece91ead
   * Codename: image
   */
  image: Elements.AssetsElement;

  /**
   * Author (modular_content)
   * Required: true
   * Id: 7ba4ba12-8d9e-4939-aed3-a68aff4b907f
   * Codename: author
   */
  author: Elements.LinkedItemsElement<AuthorModel>;

  /**
   * Publish date (date_time)
   * Required: true
   * Id: b281a60a-51fd-4437-9d07-75ff611e4852
   * Codename: publish_date
   */
  publishDate: Elements.DateTimeElement;

  /**
   * Update date (date_time)
   * Required: false
   * Id: 7d129ea0-e0a2-429e-be8d-85c2679032be
   * Codename: update_date
   */
  updateDate: Elements.DateTimeElement;

  /**
   * URL slug (url_slug)
   * Required: true
   * Id: fc22a3f7-df7b-4efb-8b2f-78b004e6bcfd
   * Codename: url_slug
   */
  urlSlug: Elements.UrlSlugElement;
}> &
  Metadata;
