import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Link
 * Id: b1ed90d1-b1f9-4cd2-a120-1556c8328e0e
 * Codename: link
 */
export type LinkModel = IContentItem<{
  /**
   * Title (text)
   * Required: false
   * Id: 12300a65-9ad0-49a9-b738-e682db794a4e
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Asset (asset)
   * Required: false
   * Id: 0e42c1ac-fb05-4863-b75b-473452776834
   * Codename: asset
   */
  asset: Elements.AssetsElement;

  /**
   * URL (text)
   * Required: false
   * Id: 0046b9b5-ea3b-4c4d-87ba-3d6b9dc3ce3f
   * Codename: url
   *
   * If it is a relative url (on kontent.ai) just paste a relative path e.g. /specials/collections and not the full link https://kontent.ai/specials/collections
   */
  url: Elements.TextElement;
}>;
