import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { CtaBannerComponentModel } from './CtaBannerComponentModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * List Item - Robust
 * Id: 94dce67c-cc67-4aaa-a479-c532064adad8
 * Codename: list_item_robust
 */
export type ListItemRobustModel = IContentItem<{
  /**
   * Heading (text)
   * Required: false
   * Id: b1e50b41-fec3-465a-af30-adba66839f3b
   * Codename: heading
   */
  heading: Elements.TextElement;

  /**
   * Text (rich_text)
   * Required: false
   * Id: 39e90a68-ad05-420e-9458-bbd58bc8f943
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * Banner (modular_content)
   * Required: false
   * Id: 5a8db048-8161-43b5-9bbe-5686d265bdb2
   * Codename: banner
   *
   * An optional banner element
   */
  banner: Elements.LinkedItemsElement<CtaBannerComponentModel>;
}>;
