import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { LogoModel } from './LogoModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Logos box
 * Id: 9858a834-ccd1-4cd6-b9c3-9c0de91d2cc1
 * Codename: logos_box
 */
export type LogosBoxModel = IContentItem<{
  /**
   * Title (text)
   * Required: false
   * Id: ac1835fc-6a59-4306-9bc9-18289504c828
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Logos (modular_content)
   * Required: false
   * Id: e87ff89c-6a92-4df1-9615-1b7940130fcd
   * Codename: logos
   */
  logos: Elements.LinkedItemsElement<LogoModel>;
}>;
