import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { MainMenuDynamicItemModel } from './MainMenuDynamicItemModel';
import { SharedContentModel } from './SharedContentModel';
import { ReleaseProjects } from '../taxonomies/release_projects';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Main menu Dynamic
 * Id: 32512b24-11e5-4ee2-b503-ad67a16fc497
 * Codename: main_menu_dynamic
 */
export type MainMenuDynamicModel = IContentItem<{
  /**
   * Items (modular_content)
   * Required: false
   * Id: f3fa2e84-17cc-4dd9-9756-e6e009d4f0bf
   * Codename: items
   */
  items: Elements.LinkedItemsElement<MainMenuDynamicItemModel>;

  /**
   * Side Items (modular_content)
   * Required: false
   * Id: d281115d-0a5f-40b0-98fb-798bf951d1ce
   * Codename: side_items
   */
  sideItems: Elements.LinkedItemsElement<MainMenuDynamicItemModel>;

  /**
   * CTAs (modular_content)
   * Required: false
   * Id: 70ea5e3a-ef54-455e-8c57-0a4cbf9f43b0
   * Codename: ctas
   */
  ctas: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Release projects (taxonomy)
   * Required: false
   * Id: 0e56badf-0222-4eb6-bd62-223dc7574b11
   * Codename: release_projects
   */
  releaseProjects: Elements.TaxonomyElement<ReleaseProjects>;
}>;
