import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { MainMenuDynamicBannerModel } from './MainMenuDynamicBannerModel';
import { ReleaseProjects } from '../taxonomies/release_projects';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Main menu Dynamic item
 * Id: abe83ade-f0b7-4eb4-a3c9-6f33c880599c
 * Codename: main_menu_dynamic_item
 */
export type MainMenuDynamicItemModel = IContentItem<{
  /**
   * Title (text)
   * Required: true
   * Id: 309dc41c-228e-426c-96fc-d9315a969fe6
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Text (rich_text)
   * Required: false
   * Id: 1c6287a4-ae2f-47d6-acb3-87167038993c
   * Codename: text
   *
   * Optional text
   */
  text: Elements.RichTextElement;

  /**
   * Icons (asset)
   * Required: false
   * Id: 0b274973-789e-419c-961e-5b3fc6529f0d
   * Codename: icons
   *
   * Icons. ORDER MATTERS. Put the GREY icon first.
   */
  icons: Elements.AssetsElement;

  /**
   * Tracking code (text)
   * Required: false
   * Id: ab040939-30db-4db2-9f7d-cb5986ec642f
   * Codename: tracking_code
   *
   * Tracking (onclick) code for Google Ananlytics. e.g.: {'event': 'Menu_Features_Developers'}
   */
  trackingCode: Elements.TextElement;

  /**
   * URL (text)
   * Required: false
   * Id: 33923e4b-758d-473b-8d5f-a3b3c9a4217a
   * Codename: url
   *
   * Use relative. Absolute URL will be opened in new window.
   */
  url: Elements.TextElement;

  /**
   * Child items (modular_content)
   * Required: false
   * Id: 14d4cf83-85b1-4f7c-aa1d-d277dd9c9209
   * Codename: child_items
   */
  childItems: Elements.LinkedItemsElement<MainMenuDynamicItemModel>;

  /**
   * Banner (modular_content)
   * Required: false
   * Id: 63f7acf4-aa46-4ab2-8274-da213a6b0b3c
   * Codename: banner
   *
   * Will be dipslayed in case at least one item is present in the "Child items" element.
   */
  banner: Elements.LinkedItemsElement<MainMenuDynamicBannerModel>;

  /**
   * Flag (text)
   * Required: false
   * Id: 1a888243-197c-4302-b82f-9201b2a4cfbf
   * Codename: flag
   *
   * Use a short phrase. Gets dipslayed next to the manu item in the main menu.
   */
  flag: Elements.TextElement;

  /**
   * Release projects (taxonomy)
   * Required: false
   * Id: de81292f-0fbf-4870-b6ac-58945ed72965
   * Codename: release_projects
   */
  releaseProjects: Elements.TaxonomyElement<ReleaseProjects>;
}>;
