import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { MainMenuDynamicBannerModel } from './MainMenuDynamicBannerModel';
import { MenuSubcategoryModel } from './MenuSubcategoryModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Menu Item
 * Id: 6af70139-fc0e-46e5-84a1-59dd7ce883d0
 * Codename: menu_item
 */
export type MenuItemModel = IContentItem<{
  /**
   * Tracking Code (text)
   * Required: false
   * Id: 16910c88-41f2-45f0-b145-d956a2dacbb1
   * Codename: tracking_code
   *
   * Tracking (onclick) code for Google Ananlytics. e.g.: {'event': 'Menu_Features_Developers'}
   */
  trackingCode: Elements.TextElement;

  /**
   * Icon (custom)
   * Required: false
   * Id: 958b4943-2f43-41e3-a08c-fbb8318290a8
   * Codename: icon
   *
   * Optional icon (usually used for child menu items e.g. Solutions children items)
   */
  icon: Elements.CustomElement;

  /**
   * Text (text)
   * Required: false
   * Id: 5f5c8dd5-fa97-4715-9a6c-30e02635662c
   * Codename: text
   */
  text: Elements.TextElement;

  /**
   * Secondary text (rich_text)
   * Required: false
   * Id: 7a735a25-2755-4f59-964a-4cd36dedbc00
   * Codename: secondary_text
   */
  secondaryText: Elements.RichTextElement;

  /**
   * URL (text)
   * Required: false
   * Id: 9aac94b0-6bd7-446f-b077-0a809340d1a5
   * Codename: url
   */
  url: Elements.TextElement;

  /**
   * Tag (text)
   * Required: false
   * Id: 92ec9c95-5f3a-4546-91e7-4bdd50e82afd
   * Codename: tag
   */
  tag: Elements.TextElement;

  /**
   * Child items (modular_content)
   * Required: false
   * Id: 8feab27b-7379-4fd9-9dba-e98c3101f6cd
   * Codename: child_items
   */
  childItems: Elements.LinkedItemsElement<MenuItemModel>;

  /**
   * Banner (modular_content)
   * Required: false
   * Id: b83fa388-caa6-4ab5-8a6f-bb2730e9005d
   * Codename: banner
   */
  banner: Elements.LinkedItemsElement<MainMenuDynamicBannerModel>;

  /**
   * Categories (modular_content)
   * Required: false
   * Id: 07def793-7505-4fde-824d-97855a95260b
   * Codename: categories
   */
  categories: Elements.LinkedItemsElement<MenuSubcategoryModel>;
}>;
