import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { LinkModel } from './LinkModel';
import { SharedContentModel } from './SharedContentModel';
import { ReleaseProjects } from '../taxonomies/release_projects';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Modular Item - Card Element
 * Id: 11651643-f8f0-4e7a-8baf-e52afa794f73
 * Codename: modular_item___card_element
 */
export type ModularItemCardElementModel = IContentItem<{
  /**
   * Image (asset)
   * Required: false
   * Id: 25b06593-483a-439e-726e-a059f664929e
   * Codename: image
   */
  image: Elements.AssetsElement;

  /**
   * Icon (custom)
   * Required: false
   * Id: 01e54810-4e19-4e83-acc2-fcff13078fea
   * Codename: icon
   */
  icon: Elements.CustomElement;

  /**
   * Title (text)
   * Required: false
   * Id: 9a000be3-e90a-eb4d-f627-17511bdb5fcf
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Text (rich_text)
   * Required: false
   * Id: 146adf97-22e3-4b65-ac6c-7253b53207d1
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * Additional text (rich_text)
   * Required: false
   * Id: 38ab1ba9-6071-4881-aa58-677c604146a1
   * Codename: additional_text
   *
   * Text used for disclaimers, notes etc.
   */
  additionalText: Elements.RichTextElement;

  /**
   * Image alt (text)
   * Required: false
   * Id: 0764a26f-23c1-489c-846b-071a00291c8e
   * Codename: image_alt
   */
  imageAlt: Elements.TextElement;

  /**
   * Tag (text)
   * Required: false
   * Id: bedb1b0a-cfd0-4b86-896c-9646c3e25962
   * Codename: tag
   *
   * Optional tag displayed in the top right corner.
   */
  tag: Elements.TextElement;

  /**
   * Link (modular_content)
   * Required: false
   * Id: 3e4a6cd5-96c2-4bf9-8e14-e324c3674dd8
   * Codename: link
   */
  link: Elements.LinkedItemsElement<LinkModel>;

  /**
   * CTA (modular_content)
   * Required: false
   * Id: 6fde468d-b610-4f31-b5f0-9f974dac17fb
   * Codename: cta
   */
  cta: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Release projects (taxonomy)
   * Required: false
   * Id: 34e420ea-c2dd-4fc4-8392-ca1adfaf198f
   * Codename: release_projects
   */
  releaseProjects: Elements.TaxonomyElement<ReleaseProjects>;
}>;
