import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { InternalPressReleaseModel } from './InternalPressReleaseModel';
import { ExternalPressReleaseModel } from './ExternalPressReleaseModel';
import { BlogPostModel } from './BlogPostModel';
import { Metadata } from '../content-type-snippets/metadata';
import { UmlpElementTextImageBlockModel } from './UmlpElementTextImageBlockModel';
import { CtaBannerComponentModel } from './CtaBannerComponentModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Newsroom LP
 * Id: 7b464244-03ff-4176-b035-84d8cd778bc4
 * Codename: newsroom_lp
 */
export type NewsroomLpModel = IContentItem<{
  /**
   * Heading (text)
   * Required: true
   * Id: 4f6f9fa7-a81c-4d78-a712-351ccd5ba78a
   * Codename: heading
   */
  heading: Elements.TextElement;

  /**
   * Lead text (text)
   * Required: true
   * Id: a7eae322-35a7-40df-b4e5-b1738b79a95c
   * Codename: lead_text
   */
  leadText: Elements.TextElement;

  /**
   * Featured news (modular_content)
   * Required: true
   * Id: f32a3e94-0a9a-436e-944d-070be3f6a00b
   * Codename: featured_news
   */
  featuredNews: Elements.LinkedItemsElement<
    InternalPressReleaseModel | ExternalPressReleaseModel | BlogPostModel
  >;

  /**
   * Text and Image section (modular_content)
   * Required: false
   * Id: c42eceb3-8b3a-4768-8f17-a829b9f75c22
   * Codename: text_and_image_section
   */
  textAndImageSection: Elements.LinkedItemsElement<UmlpElementTextImageBlockModel>;

  /**
   * CTA Section (modular_content)
   * Required: true
   * Id: 9be00c51-32f0-4442-91c9-959e68f545dd
   * Codename: cta_section
   */
  ctaSection: Elements.LinkedItemsElement<CtaBannerComponentModel>;
}> &
  Metadata;
