import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { SharedContentModel } from './SharedContentModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Newsletter subscription
 * Id: 3b31f2fc-e4e3-4557-9b6a-fc66d7a17846
 * Codename: newsletter_subscription
 */
export type NewsletterSubscriptionModel = IContentItem<{
  /**
   * Headline (text)
   * Required: false
   * Id: 9dd36db6-ce6e-343a-6889-9087559c4174
   * Codename: headline
   */
  headline: Elements.TextElement;

  /**
   * Subheadline (text)
   * Required: false
   * Id: e2320211-a5fc-5e4a-1737-709f7837b34c
   * Codename: subheadline
   */
  subheadline: Elements.TextElement;

  /**
   * Placeholder for email input (text)
   * Required: false
   * Id: f7a21e9a-f76e-e7e9-337c-da6351e8742c
   * Codename: placeholder_for_email_input
   */
  placeholderForEmailInput: Elements.TextElement;

  /**
   * Button (modular_content)
   * Required: false
   * Id: 00ecb6b8-ddc8-0951-9e7d-098d5a8e02df
   * Codename: button
   */
  button: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Checkbox Label Text (text)
   * Required: true
   * Id: 301ed478-219c-4865-9501-2a05857b27b6
   * Codename: checkbox_label_text
   */
  checkboxLabelText: Elements.TextElement;
}>;
