import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { HeroKK } from '../content-type-snippets/hero_kk';
import { SharedContentModel } from './SharedContentModel';
import { CtaBannerComponentModel } from './CtaBannerComponentModel';
import { Metadata } from '../content-type-snippets/metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * New UI Microsite
 * Id: ebf96a78-5a06-4db2-9d28-a5a5b5cda376
 * Codename: new_ui_microsite
 */
export type NewUiMicrositeModel = IContentItem<{
  /**
   * CTA Button (modular_content)
   * Required: false
   * Id: e4c0a676-8646-4ebc-b95b-fe0cb68a44b5
   * Codename: cta_button
   */
  ctaButton: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Old UI Image (asset)
   * Required: false
   * Id: e1549eb9-495c-452b-a7bb-6e53c4e5f914
   * Codename: old_ui_image
   */
  oldUiImage: Elements.AssetsElement;

  /**
   * New UI Image (asset)
   * Required: false
   * Id: 09b08e75-d438-40b8-92ee-439972320cee
   * Codename: new_ui_image
   */
  newUiImage: Elements.AssetsElement;

  /**
   * Logo (asset)
   * Required: false
   * Id: b35d5c47-c066-45a3-befe-82f13c6be1bc
   * Codename: logo
   */
  logo: Elements.AssetsElement;

  /**
   * Menu Item 1 (text)
   * Required: false
   * Id: ad7c2de6-d719-42c3-8593-6d6c15e73f90
   * Codename: menu_item_1
   */
  menuItem1: Elements.TextElement;

  /**
   * Menu Item 2 (text)
   * Required: false
   * Id: 2982dbae-d9ce-4995-be02-ebc8af80c267
   * Codename: menu_item_2
   */
  menuItem2: Elements.TextElement;

  /**
   * Menu Item 3 (text)
   * Required: false
   * Id: 3fd873e7-4c00-4124-a91c-f2ad7b36b36e
   * Codename: menu_item_3
   */
  menuItem3: Elements.TextElement;

  /**
   * Menu Item 4 (text)
   * Required: false
   * Id: 6a22db8e-ef63-4bd6-a061-7659f3770ace
   * Codename: menu_item_4
   */
  menuItem4: Elements.TextElement;

  /**
   * Heading 1 (text)
   * Required: false
   * Id: f4ab8e4c-aae1-47fc-93d0-18dfffd8513f
   * Codename: heading_1
   */
  heading1: Elements.TextElement;

  /**
   * Text 1 (rich_text)
   * Required: false
   * Id: 26992784-061e-4195-bfd3-892643784035
   * Codename: text_1
   */
  text1: Elements.RichTextElement;

  /**
   * Image 1 (asset)
   * Required: false
   * Id: 157e7c8d-efd9-4c2b-9af0-a6333f0e9548
   * Codename: image_1
   */
  image1: Elements.AssetsElement;

  /**
   * Heading 2 (text)
   * Required: false
   * Id: 1bfd6bf8-6cf2-463e-9031-1cf444592aa6
   * Codename: heading_2
   */
  heading2: Elements.TextElement;

  /**
   * Text 2 (rich_text)
   * Required: false
   * Id: bb9e8e32-a0b5-4cb2-831d-663ab6e5f293
   * Codename: text_2
   */
  text2: Elements.RichTextElement;

  /**
   * Image 2 (asset)
   * Required: false
   * Id: f1854221-028c-4780-bf25-bae163b7d4e2
   * Codename: image_2
   */
  image2: Elements.AssetsElement;

  /**
   * Heading 3 (text)
   * Required: false
   * Id: cd7be5f8-5dff-4175-9546-009b7dcd3e84
   * Codename: heading_3
   */
  heading3: Elements.TextElement;

  /**
   * Text 3 (rich_text)
   * Required: false
   * Id: dc015aa0-64d4-4d79-8578-afb62bb849a3
   * Codename: text_3
   */
  text3: Elements.RichTextElement;

  /**
   * Image 3 (asset)
   * Required: false
   * Id: f4b2dd7c-b27b-4c63-a51e-611bd0a10e7f
   * Codename: image_3
   */
  image3: Elements.AssetsElement;

  /**
   * Heading 4 (text)
   * Required: false
   * Id: 43d7125d-58ac-4303-90b3-be080890d8ef
   * Codename: heading_4
   */
  heading4: Elements.TextElement;

  /**
   * Text 4 (rich_text)
   * Required: false
   * Id: 4f710dc4-7190-452e-bd9d-6badb4ee8d67
   * Codename: text_4
   */
  text4: Elements.RichTextElement;

  /**
   * Image 4 (asset)
   * Required: false
   * Id: acb12640-f500-4127-a0e9-cff5202293c3
   * Codename: image_4
   */
  image4: Elements.AssetsElement;

  /**
   * Heading 5 (text)
   * Required: false
   * Id: b4d2c8df-2de2-4fd4-807e-c775b6a70423
   * Codename: heading_5
   */
  heading5: Elements.TextElement;

  /**
   * Text 5 (rich_text)
   * Required: false
   * Id: f49001a0-d5f1-4a6a-8bfa-9db126f9cf89
   * Codename: text_5
   */
  text5: Elements.RichTextElement;

  /**
   * Image 5 (asset)
   * Required: false
   * Id: 3afd627c-5ef6-4c27-ae81-f46f1812a6ad
   * Codename: image_5
   */
  image5: Elements.AssetsElement;

  /**
   * CTA Banner (modular_content)
   * Required: false
   * Id: 52613dfd-9d40-4469-bb74-b84eca805186
   * Codename: cta_banner
   */
  ctaBanner: Elements.LinkedItemsElement<CtaBannerComponentModel>;

  /**
   * Preview Button (custom)
   * Required: false
   * Id: 8f9762e2-97b6-4e47-a2c0-52172c8b8db5
   * Codename: preview_button
   */
  previewButton: Elements.CustomElement;
}> &
  HeroKK &
  Metadata;
