import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { HeroKK } from '../content-type-snippets/hero_kk';
import { SharedContentModel } from './SharedContentModel';
import { BubbleModel } from './BubbleModel';
import { TestimonialModel } from './TestimonialModel';
import { SolutionsPageRelatedAssetModel } from './SolutionsPageRelatedAssetModel';
import { CtaBannerComponentModel } from './CtaBannerComponentModel';
import { Metadata } from '../content-type-snippets/metadata';
import { SitemapMetadata } from '../content-type-snippets/sitemap_metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Next.js Page
 * Id: da8a605e-a9ef-4c98-a212-c9cffd8e9c21
 * Codename: next_js_page
 */
export type NextJsPageModel = IContentItem<{
  /**
   * CTA Button (modular_content)
   * Required: false
   * Id: 60dacbfd-52b0-49e7-9b7d-a9ba09ef1e1d
   * Codename: cta_button
   */
  ctaButton: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Heading (text)
   * Required: false
   * Id: fda0bf0f-e064-41ba-8b6b-159ff4b09364
   * Codename: heading_features
   */
  headingFeatures: Elements.TextElement;

  /**
   * Bubbles (modular_content)
   * Required: false
   * Id: 7f5da0a0-45c9-4249-8af0-bc393de3686d
   * Codename: bubbles_features
   */
  bubblesFeatures: Elements.LinkedItemsElement<BubbleModel>;

  /**
   * Heading (text)
   * Required: false
   * Id: 47ccb2f1-3fe2-414f-90d1-cc22641d7b2a
   * Codename: heading_builds
   */
  headingBuilds: Elements.TextElement;

  /**
   * Text (rich_text)
   * Required: false
   * Id: 7bf9bab9-52b7-4dae-8e15-db60dbd43462
   * Codename: text_builds
   */
  textBuilds: Elements.RichTextElement;

  /**
   * Image (asset)
   * Required: false
   * Id: bf8f50d4-56fc-4e95-9468-d341159cf488
   * Codename: image_builds
   */
  imageBuilds: Elements.AssetsElement;

  /**
   * Heading (text)
   * Required: false
   * Id: d12002b5-87b8-4004-ba99-af00a6ade532
   * Codename: heading_starter
   */
  headingStarter: Elements.TextElement;

  /**
   * Text (rich_text)
   * Required: false
   * Id: 2921c0e2-d2af-4020-b452-d08d5564f04e
   * Codename: text_starter
   */
  textStarter: Elements.RichTextElement;

  /**
   * Image (asset)
   * Required: false
   * Id: 1cb00b91-03a0-4c83-82fb-7a507435659b
   * Codename: image_starter
   */
  imageStarter: Elements.AssetsElement;

  /**
   * Link (text)
   * Required: false
   * Id: 4eaf323a-70ea-47f9-996e-8f844915edc1
   * Codename: link_starter
   */
  linkStarter: Elements.TextElement;

  /**
   * Button Text (text)
   * Required: false
   * Id: f548d92e-0afe-4d1e-b491-9a7d61f4719a
   * Codename: button_text_starter
   */
  buttonTextStarter: Elements.TextElement;

  /**
   * Heading (text)
   * Required: false
   * Id: 613e4434-41b3-443d-8074-96f2c64e8725
   * Codename: heading_hosting
   */
  headingHosting: Elements.TextElement;

  /**
   * Logos (asset)
   * Required: false
   * Id: bdab7200-ff38-44f0-9919-e650df271e59
   * Codename: logos_hosting
   */
  logosHosting: Elements.AssetsElement;

  /**
   * Heading (text)
   * Required: false
   * Id: 9e4200b3-891c-4782-af21-91c648831da2
   * Codename: heading_cms
   */
  headingCms: Elements.TextElement;

  /**
   * Text (rich_text)
   * Required: false
   * Id: 9d1d6a94-8aaa-4e0a-be0a-be424cb8def0
   * Codename: text_cms
   */
  textCms: Elements.RichTextElement;

  /**
   * Bubbles (modular_content)
   * Required: false
   * Id: 14ea5696-18f3-4183-9897-c0b37efb38fc
   * Codename: bubbles_cms
   */
  bubblesCms: Elements.LinkedItemsElement<BubbleModel>;

  /**
   * Image (asset)
   * Required: false
   * Id: 5593e3fb-3073-48c8-904e-1155d3660847
   * Codename: image_cms
   */
  imageCms: Elements.AssetsElement;

  /**
   * Heading (text)
   * Required: false
   * Id: c9dcba46-8817-4528-aab9-6dea1d5f3dec
   * Codename: heading_testimonial
   */
  headingTestimonial: Elements.TextElement;

  /**
   * Testimonial (modular_content)
   * Required: false
   * Id: e8c0758b-5c51-4964-8b75-10a5bd803339
   * Codename: testimonial
   */
  testimonial: Elements.LinkedItemsElement<TestimonialModel>;

  /**
   * Heading (text)
   * Required: false
   * Id: 0a8dd894-265b-4cf1-ac94-a1fe038da3f7
   * Codename: heading_related_assets
   */
  headingRelatedAssets: Elements.TextElement;

  /**
   * Related Assets (modular_content)
   * Required: false
   * Id: 712d820e-ea08-431e-aea3-add26bf26df6
   * Codename: related_assets
   */
  relatedAssets: Elements.LinkedItemsElement<SolutionsPageRelatedAssetModel>;

  /**
   * CTA Banner (modular_content)
   * Required: false
   * Id: 7c4bcb6c-75b1-4403-9ad1-5831cf41508c
   * Codename: cta_banner
   */
  ctaBanner: Elements.LinkedItemsElement<CtaBannerComponentModel>;
}> &
  HeroKK &
  Metadata &
  SitemapMetadata;
