import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { SharedContentModel } from './SharedContentModel';
import { Metadata } from '../content-type-snippets/metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * One help links
 * Id: 0399193e-74a7-4ca1-b81c-c4648e5f8102
 * Codename: one_help_links
 */
export type OneHelpLinksModel = IContentItem<{
  /**
   * Get familiar (modular_content)
   * Required: false
   * Id: c6037cda-ef57-45a1-bcfb-651f09ae7b80
   * Codename: get_familiar
   */
  getFamiliar: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Develop apps (modular_content)
   * Required: false
   * Id: 45eff6fa-c317-4fb3-a24d-08ae1bff0b3d
   * Codename: develop_apps
   */
  developApps: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Create content (modular_content)
   * Required: false
   * Id: 8bdd84ad-3fe7-4a44-9406-9e56c94f4086
   * Codename: create_content
   */
  createContent: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Future proof (modular_content)
   * Required: false
   * Id: 007d3fb3-6766-427f-bc82-9e384315e3f2
   * Codename: future_proof
   */
  futureProof: Elements.LinkedItemsElement<SharedContentModel>;
}> &
  Metadata;
