import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { CaseStudyHighlightedResultModel } from './CaseStudyHighlightedResultModel';
import { RichTestimonialModel } from './RichTestimonialModel';
import { Regions } from '../taxonomies/regions';
import { SitemapMetadata } from '../content-type-snippets/sitemap_metadata';
import { TestimonialModel } from './TestimonialModel';
import { PartnerModel } from './PartnerModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Partner Success Story
 * Id: f966abbb-3620-4ded-a383-c0ee7f18f368
 * Codename: partner_success_story
 */
export type PartnerSuccessStoryModel = IContentItem<{
  /**
   * Header image (asset)
   * Required: true
   * Id: 69841859-ef15-4483-aad3-f9a4895c970c
   * Codename: header_image
   *
   * Image displayed at top of the page1920 x 680px
   */
  headerImage: Elements.AssetsElement;

  /**
   * Logo (asset)
   * Required: false
   * Id: 34feab23-209d-4eda-94e8-bea5bf5b3732
   * Codename: logo
   */
  logo: Elements.AssetsElement;

  /**
   * Website URL (text)
   * Required: true
   * Id: 9418e60f-9bd4-4ee2-92e4-14dc2680cedc
   * Codename: website_url
   *
   * URL of website including protocol http:// or https://
   */
  websiteUrl: Elements.TextElement;

  /**
   * Direct to the Website URL (multiple_choice)
   * Required: true
   * Id: 1ea0a0dc-cef4-4193-8454-c82959bf4b5c
   * Codename: direct_to_the_website_url
   *
   * No - The case study has a standard detail page. Yes - The case study has no standard detail page. When clicked in a case study list, user is directed to the Website URL.
   */
  directToTheWebsiteUrl: Elements.MultipleChoiceElement;

  /**
   * Title Full (rich_text)
   * Required: true
   * Id: 7dda8a18-4d2e-4416-b35e-b25c9a8cc191
   * Codename: title_full
   *
   * Title/Main heading used in detail page (max. 120 characters). Add a period to the end and mark it bold.
   */
  titleFull: Elements.RichTextElement;

  /**
   * Title Short (text)
   * Required: true
   * Id: 90bc737c-d3ac-48ee-b1ee-f06871ffa7e6
   * Codename: title
   *
   * Used e.g. in listing page.
   */
  title: Elements.TextElement;

  /**
   * Card image text (text)
   * Required: false
   * Id: ccf48272-888b-416f-b8e2-b324b9ea8d3b
   * Codename: card_image_text
   *
   * Optional card image text strip (max. 120 characters)
   */
  cardImageText: Elements.TextElement;

  /**
   * Goal (rich_text)
   * Required: true
   * Id: 7db8c035-836b-46f8-b309-a0ffe44d0bc6
   * Codename: goal
   *
   * Goal or reason of case study. Used as perex. Max 400 characters. Mark the first sentence as an H2 and make the first period bold.
   */
  goal: Elements.RichTextElement;

  /**
   * Body (rich_text)
   * Required: false
   * Id: 7f5bdb8e-53ca-49c9-b193-64c7e0e626c2
   * Codename: body
   *
   * Body of the case study
   */
  body: Elements.RichTextElement;

  /**
   * Highlighted results (modular_content)
   * Required: false
   * Id: 43e020dc-9e31-445b-91ba-6500ed2daeed
   * Codename: highlighted_results
   *
   * Select 1 or more items of type "Highlighted Results"
   */
  highlightedResults: Elements.LinkedItemsElement<CaseStudyHighlightedResultModel>;

  /**
   * Highlighted results - After Solution (modular_content)
   * Required: false
   * Id: 37787714-8280-4868-b8f1-07bb7a5d8e8b
   * Codename: highlighted_results___after_solution
   */
  highlightedResultsAfterSolution: Elements.LinkedItemsElement<CaseStudyHighlightedResultModel>;

  /**
   * Rich Testimonial (modular_content)
   * Required: false
   * Id: 3dd3c74e-f360-4e74-90b9-483f27956e34
   * Codename: rich_testimonial
   *
   * Select 1 item
   */
  richTestimonial: Elements.LinkedItemsElement<RichTestimonialModel>;

  /**
   * Publish date (date_time)
   * Required: false
   * Id: eb44cba2-aa2e-448e-9565-1ba2aed50f0b
   * Codename: publish_date
   *
   * Date when page is published on our web site.  Used for ordering in case studies listing.
   */
  publishDate: Elements.DateTimeElement;

  /**
   * Metadata - title (text)
   * Required: false
   * Id: 0e6dbe5a-6117-4dec-8e48-d007943365df
   * Codename: metadata___title
   *
   * Format: Customer name - Customer Success Story & Review
   */
  metadataTitle: Elements.TextElement;

  /**
   * Metadata - description (text)
   * Required: false
   * Id: f864dc31-d7c3-4478-84ca-a591d933d884
   * Codename: metadata___description
   *
   * 2 sentences: a brief description of what was achieved, and "Read the customer success story".
   */
  metadataDescription: Elements.TextElement;

  /**
   * URL slug (url_slug)
   * Required: false
   * Id: af520262-24fb-45d4-b272-664878246cc9
   * Codename: url_slug
   */
  urlSlug: Elements.UrlSlugElement;

  /**
   * Region (taxonomy)
   * Required: false
   * Id: c90b5315-bf2c-49fe-815f-cafe1617dc77
   * Codename: region
   */
  region: Elements.TaxonomyElement<Regions>;

  /**
   * Type (text)
   * Required: false
   * Id: 5eb21be3-d1e0-491e-babb-529fd328f487
   * Codename: type
   *
   * Orange text on the case study card. Defaults to "Case Study"
   */
  type: Elements.TextElement;

  /**
   * Opengraph Image (asset)
   * Required: false
   * Id: 8e37a40c-f7e3-4284-b7da-1b79df9e2b36
   * Codename: opengraph_image
   *
   * Ideally 1200px wide
   */
  opengraphImage: Elements.AssetsElement;

  /**
   * Social Media Text (rich_text)
   * Required: false
   * Id: f587e743-fffd-48fc-9ccc-88a288bb0ef5
   * Codename: social_media_text
   *
   * For manual processing only - not used on the website
   */
  socialMediaText: Elements.RichTextElement;

  /**
   * Social Media Banner Copy (rich_text)
   * Required: false
   * Id: 1bd888cb-2397-4e18-858a-c4db5924867b
   * Codename: social_media_banner_copy
   *
   * For manual processing only - not used on the website
   */
  socialMediaBannerCopy: Elements.RichTextElement;

  /**
   * Social Media Banners (asset)
   * Required: false
   * Id: 11ba5f29-2550-4d4b-8085-cd71000c98ac
   * Codename: social_media_banners
   *
   * For manual processing only - not used on the website
   */
  socialMediaBanners: Elements.AssetsElement;

  /**
   * Social Media Channels (multiple_choice)
   * Required: false
   * Id: 6d507afc-cabe-4578-b0cb-0a962a6b43a6
   * Codename: social_media_channels
   *
   * For manual processing only - not used on the website
   */
  socialMediaChannels: Elements.MultipleChoiceElement;

  /**
   * Year of implementation (text)
   * Required: false
   * Id: 94d30084-36a4-4c16-8b1f-8624459e5656
   * Codename: year_of_implementation
   *
   * !OBSOLETE!  Date when case study was implemented - specified as string (only temporary, will be removed and replaced by 'Implemented Date' in few days)
   */
  yearOfImplementation: Elements.TextElement;

  /**
   * Introduction (text)
   * Required: false
   * Id: 451a86a3-08cf-485f-ac5b-73238bc3e3b8
   * Codename: introduction
   *
   * !OBSOLETE!  - can be still used by old items, but for new items use "Title full" field instead
   */
  introduction: Elements.TextElement;

  /**
   * Testimonial (modular_content)
   * Required: false
   * Id: 4e5bb908-bae9-4588-93e2-ce78d7bf61ca
   * Codename: testimonial
   *
   * !OBSOLETE! - use "Rich Testimonial" field for new case studies
   */
  testimonial: Elements.LinkedItemsElement<TestimonialModel>;

  /**
   * Technology Stack (multiple_choice)
   * Required: false
   * Id: 7fb897fa-6a1f-41eb-a6ed-023df6ed8500
   * Codename: technology_stack
   *
   * !OBSOLETE!
   */
  technologyStack: Elements.MultipleChoiceElement;

  /**
   * Mobile App Title (text)
   * Required: false
   * Id: 78cba0b9-e25a-4c46-acb6-f1b150c02fa4
   * Codename: mobile_app_title
   *
   * !OBSOLETE! Title of link to mobile app
   */
  mobileAppTitle: Elements.TextElement;

  /**
   * Mobile App URL (text)
   * Required: false
   * Id: e56ce273-15f6-4e3e-b30f-cce4e86c6646
   * Codename: mobile_app_url
   *
   * !OBSOLETE! URL where related mobile app can be downloaded (including protocol http:// or https://)
   */
  mobileAppUrl: Elements.TextElement;

  /**
   * Header image text (text)
   * Required: false
   * Id: 67eb227a-f07b-4672-9552-945e6518dd68
   * Codename: header_image_text
   *
   * !OBSOLETE! Alt text for header image
   */
  headerImageText: Elements.TextElement;

  /**
   * Partner page (modular_content)
   * Required: false
   * Id: 3d9d356d-3a68-4622-bba7-6d4f8de450f7
   * Codename: partner_page
   *
   * !OBSOLETE!  Choose the Partner content item of partner who implemented the case study. Unless there is a Partner page for the author, fill in the Implemented by field below.
   */
  partnerPage: Elements.LinkedItemsElement<PartnerModel>;

  /**
   * Implemented Date (date_time)
   * Required: false
   * Id: b01cb7aa-5fd0-4211-ae56-a0444a4c868c
   * Codename: implemented_date
   *
   * !OBSOLETE! Date when case study was implemented. You can enter 1st day of month if you don't know exact day, there is only month and year part used.
   */
  implementedDate: Elements.DateTimeElement;

  /**
   * Client information (rich_text)
   * Required: false
   * Id: 8f7fed21-143c-4f69-b1ff-a597f74630b8
   * Codename: client_information
   *
   * !OBSOLETE!  Information/Data about client. Don't use "bold" for title/client's name, just h4
   */
  clientInformation: Elements.RichTextElement;

  /**
   * Project information (rich_text)
   * Required: false
   * Id: a698c0d5-3d52-4b60-843d-05b10f3ccfa0
   * Codename: project_information
   *
   * !OBSOLETE!  Information about project.  Max 500 characters.
   */
  projectInformation: Elements.RichTextElement;

  /**
   * Results lead paragraph (rich_text)
   * Required: false
   * Id: 9d2ee9c1-2537-4ceb-b9dc-0647d80b2c13
   * Codename: results_lead_paragraph
   *
   * !OBSOLETE!  Results lead paragraph.  Max 200 characters
   */
  resultsLeadParagraph: Elements.RichTextElement;

  /**
   * Results classic paragraph (rich_text)
   * Required: false
   * Id: 184a85a2-c4a4-4cd7-a980-d2bfa8c1b678
   * Codename: results_classic_paragraph
   *
   * !OBSOLETE!  Results classic paragraph. Max 300 characters
   */
  resultsClassicParagraph: Elements.RichTextElement;

  /**
   * Screenshots (asset)
   * Required: false
   * Id: 7432849b-15ab-41f5-b42a-808be6010828
   * Codename: screenshots
   *
   * !OBSOLETE!
   */
  screenshots: Elements.AssetsElement;
}> &
  SitemapMetadata;
