import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { HeroKK } from '../content-type-snippets/hero_kk';
import { LinkGroupModel } from './LinkGroupModel';
import { LinkModel } from './LinkModel';
import { PersonModel } from './PersonModel';
import { Metadata } from '../content-type-snippets/metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Partner space
 * Id: 7afe060f-d89f-4921-9480-b8d5eff4185e
 * Codename: partner_space
 */
export type PartnerSpaceModel = IContentItem<{
  /**
   * Hero image - authenticated (asset)
   * Required: true
   * Id: 3610049b-cc07-4909-9cf2-abe775309acd
   * Codename: hero_image___authenticated
   */
  heroImageAuthenticated: Elements.AssetsElement;

  /**
   * Support heading (text)
   * Required: true
   * Id: 6a188b3c-e809-4d7c-bcee-ed73673193c1
   * Codename: support_heading
   */
  supportHeading: Elements.TextElement;

  /**
   * Resource groups (modular_content)
   * Required: true
   * Id: 3b6d8773-9899-46cb-a377-354ce8446cda
   * Codename: resource_groups
   */
  resourceGroups: Elements.LinkedItemsElement<LinkGroupModel>;

  /**
   * Heading (text)
   * Required: true
   * Id: 5a52878a-b6d6-4f6b-8f26-351a5bcb44b9
   * Codename: heading
   */
  heading: Elements.TextElement;

  /**
   * Text (rich_text)
   * Required: true
   * Id: 6a2c6c15-56e6-4e48-a7b8-8ea253f4849d
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * Image (asset)
   * Required: true
   * Id: 20b236d6-d739-4263-937f-3601bf70ea02
   * Codename: image
   */
  image: Elements.AssetsElement;

  /**
   * Links (modular_content)
   * Required: true
   * Id: 344acd60-9f17-4aba-93ca-ec032ba990e9
   * Codename: links
   */
  links: Elements.LinkedItemsElement<LinkModel>;

  /**
   * Heading (text)
   * Required: false
   * Id: d5eec579-a82a-473d-ad95-d8918b4f2217
   * Codename: heading_contacts
   */
  headingContacts: Elements.TextElement;

  /**
   * Partner program (text)
   * Required: true
   * Id: 494bd327-7aa9-4cc8-bb1f-daedb35a6bf6
   * Codename: partner_program
   *
   * Partner team email address
   */
  partnerProgram: Elements.TextElement;

  /**
   * Sales (modular_content)
   * Required: true
   * Id: c7bc5bdf-cccb-4fcc-9584-711ee9dcde1d
   * Codename: sales
   */
  sales: Elements.LinkedItemsElement<PersonModel>;

  /**
   * Login button text (text)
   * Required: false
   * Id: 4a79a2ac-ffa4-4397-9887-130ca00d5bc0
   * Codename: login_button_text
   */
  loginButtonText: Elements.TextElement;

  /**
   * Logout button text (text)
   * Required: false
   * Id: 59a3f854-1a77-4f74-8709-99a005a57e32
   * Codename: logout_button_text
   */
  logoutButtonText: Elements.TextElement;

  /**
   * Become partner button text (text)
   * Required: false
   * Id: 085eec74-d083-442d-a2ee-9a73044e3ca9
   * Codename: become_partner_button_text
   */
  becomePartnerButtonText: Elements.TextElement;

  /**
   * Hero headline (not authenticated) (text)
   * Required: false
   * Id: 0dbed8e5-adba-4d18-bcc7-4d23ac67cfed
   * Codename: hero_headline__not_authenticated_
   */
  heroHeadlineNotAuthenticated: Elements.TextElement;

  /**
   * Hero lead paragraph (not authenticated) (rich_text)
   * Required: false
   * Id: a4540a72-7b9b-4217-83fd-088eb1a7774d
   * Codename: hero_lead_paragraph__not_authenticated_
   */
  heroLeadParagraphNotAuthenticated: Elements.RichTextElement;

  /**
   * Hero headline (authenticated, not partner) (text)
   * Required: false
   * Id: 661f1c33-8441-423b-853f-1933be86a3fa
   * Codename: hero_headline__authenticated__not_partner_
   */
  heroHeadlineAuthenticatedNotPartner: Elements.TextElement;

  /**
   * Hero lead paragraph (authenticated, not partner) (rich_text)
   * Required: false
   * Id: 1e611fd6-d826-4bb6-a8c8-0e82b0efcf83
   * Codename: hero_lead_paragraph__authenticated__not_partner_
   */
  heroLeadParagraphAuthenticatedNotPartner: Elements.RichTextElement;
}> &
  HeroKK &
  Metadata;
