import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { PartnerModel } from './PartnerModel';
import { SharedContentModel } from './SharedContentModel';
import { SitemapMetadata } from '../content-type-snippets/sitemap_metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Partners page
 * Id: 73a52c2e-aab5-4f63-b011-db5ba51d0f78
 * Codename: partners_page
 */
export type PartnersPageModel = IContentItem<{
  /**
   * Title (text)
   * Required: true
   * Id: 559da862-186f-26b4-e43d-fc426523cb7c
   * Codename: title
   *
   * Title of page
   */
  title: Elements.TextElement;

  /**
   * Lead paragraph (text)
   * Required: false
   * Id: ff8f83c4-ef45-7b8e-081e-ec5e96815f06
   * Codename: lead_paragraph
   */
  leadParagraph: Elements.TextElement;

  /**
   * Metadata title (text)
   * Required: false
   * Id: b895245c-2b6a-5275-2440-05e152d306cb
   * Codename: metadata_title
   */
  metadataTitle: Elements.TextElement;

  /**
   * Metadata description (text)
   * Required: false
   * Id: f8b51d96-d765-4663-1082-1fceec1ba6e0
   * Codename: metadata_description
   */
  metadataDescription: Elements.TextElement;

  /**
   * Partners (modular_content)
   * Required: false
   * Id: c5fe6d03-c724-7c1c-d30d-db5e484f0e80
   * Codename: partners
   *
   * List of partners
   */
  partners: Elements.LinkedItemsElement<PartnerModel>;

  /**
   * Become partner button (modular_content)
   * Required: false
   * Id: 735b45de-35bf-1f31-7425-6d5d254093b8
   * Codename: become_partner_button
   */
  becomePartnerButton: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Ask us header (text)
   * Required: false
   * Id: 491d2720-144a-2dff-2c1c-9cc280b04b30
   * Codename: ask_us_header
   */
  askUsHeader: Elements.TextElement;

  /**
   * Ask us button (modular_content)
   * Required: false
   * Id: ebd1bbe3-23b9-d8a9-37d0-7fff5f95e296
   * Codename: ask_us_button
   */
  askUsButton: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Partner's metadata title (text)
   * Required: false
   * Id: 084745ae-6855-9889-47e9-f3d4a975c79a
   * Codename: partner_s_metadata_title
   *
   * Metadata title displayed in partner's detail page. You can use ##partnername## macro that will be replaced by actual partner name
   */
  partnerSMetadataTitle: Elements.TextElement;

  /**
   * Partner's metadata description (text)
   * Required: false
   * Id: 5baef1f6-11e6-e2c9-0fc5-30dcdce01dbe
   * Codename: partner_s_metadata_description
   *
   * Metadata description displayed in partner's detail page. You can use ##partnername## and ##location## macros that will be replaced by actual partner name/location(city, state, country]
   */
  partnerSMetadataDescription: Elements.TextElement;

  /**
   * Empty state button (modular_content)
   * Required: false
   * Id: ed320059-724d-4b88-959a-3395286b1c28
   * Codename: empty_state_button
   */
  emptyStateButton: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Empty state title (text)
   * Required: false
   * Id: 2193216f-6814-4b09-990c-12a65ee4dae2
   * Codename: empty_state_title
   */
  emptyStateTitle: Elements.TextElement;

  /**
   * Premium partner badge (asset)
   * Required: false
   * Id: 33d76f0d-b851-4e93-8473-2f7eeb86b885
   * Codename: premium_partner_badge
   */
  premiumPartnerBadge: Elements.AssetsElement;

  /**
   * Advanced partner badge (asset)
   * Required: false
   * Id: 54390d3b-1b7e-4406-a1fb-44451c0c010e
   * Codename: advanced_partner_badge
   */
  advancedPartnerBadge: Elements.AssetsElement;

  /**
   * Qualified partner badge (asset)
   * Required: false
   * Id: 32178e6a-5f8a-4be6-9be3-5b585a79ed2e
   * Codename: qualified_partner_badge
   */
  qualifiedPartnerBadge: Elements.AssetsElement;
}> &
  SitemapMetadata;
