import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { ContentItemYoutubeVideoModel } from './ContentItemYoutubeVideoModel';
import { PartnerSpaceItemModel } from './PartnerSpaceItemModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Partner space section
 * Id: a8db76eb-902c-4ec3-9caa-2d2b1a2ebc51
 * Codename: partner_space_section
 */
export type PartnerSpaceSectionModel = IContentItem<{
  /**
   * Title (text)
   * Required: false
   * Id: 700e4f4e-18d7-4010-a202-222adad6d755
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Video (modular_content)
   * Required: false
   * Id: 1b3b5ce9-06bc-4bfc-879a-64afd4c3c584
   * Codename: video
   *
   * OPTIONAL videos displayed underneath the title text
   */
  video: Elements.LinkedItemsElement<ContentItemYoutubeVideoModel>;

  /**
   * Items (modular_content)
   * Required: false
   * Id: dc72194c-a6fa-49cc-9ce8-c90ea7509a0f
   * Codename: items
   */
  items: Elements.LinkedItemsElement<PartnerSpaceItemModel>;
}>;
