import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { LogoModel } from './LogoModel';
import { TestimonialModel } from './TestimonialModel';
import { EnterpriseFeatureKkModel } from './EnterpriseFeatureKkModel';
import { SharedContentModel } from './SharedContentModel';
import { UmlpElementPartnerSuccessStoriesShowcaseModel } from './UmlpElementPartnerSuccessStoriesShowcaseModel';
import { Metadata } from '../content-type-snippets/metadata';
import { SitemapMetadata } from '../content-type-snippets/sitemap_metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Partners Main page
 * Id: 4177449c-1ceb-4a68-bf42-9489cd29ed71
 * Codename: partners_main_page
 */
export type PartnersMainPageModel = IContentItem<{
  /**
   * Title (text)
   * Required: false
   * Id: 129ec974-97b5-4cdd-8499-7a3c93b19da5
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Lead paragraph (text)
   * Required: false
   * Id: 05545c6c-fab7-4be0-a9cc-0df885f0f791
   * Codename: lead_paragraph
   */
  leadParagraph: Elements.TextElement;

  /**
   * Logos (modular_content)
   * Required: false
   * Id: 47305846-de61-4a0c-8edb-42cab579281f
   * Codename: logos
   */
  logos: Elements.LinkedItemsElement<LogoModel>;

  /**
   * Testimonials (modular_content)
   * Required: false
   * Id: ae0e4f03-450b-46a6-8f87-4f7639fc42a6
   * Codename: testimonials
   */
  testimonials: Elements.LinkedItemsElement<TestimonialModel>;

  /**
   * Heading (text)
   * Required: false
   * Id: 4f2ecbf6-a7eb-4f87-9940-f3e3cd2f4d8d
   * Codename: heading_4f2ecbf
   */
  heading4f2ecbf: Elements.TextElement;

  /**
   * Text (rich_text)
   * Required: false
   * Id: d983f366-0ae4-43c1-8354-90409b41476c
   * Codename: text_d983f36
   */
  textD983f36: Elements.RichTextElement;

  /**
   * Subheading (text)
   * Required: false
   * Id: 90501744-1464-4993-8e98-6a1702dde860
   * Codename: subheading
   */
  subheading: Elements.TextElement;

  /**
   * Features (modular_content)
   * Required: false
   * Id: e463350b-268c-45df-bc83-c6b2f54f7431
   * Codename: features
   */
  features: Elements.LinkedItemsElement<EnterpriseFeatureKkModel>;

  /**
   * CTA (modular_content)
   * Required: false
   * Id: 4d71a469-f825-44b0-b776-d2fb5d34710f
   * Codename: cta
   */
  cta: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Success stories component (modular_content)
   * Required: false
   * Id: 3c48a76e-3b91-4610-ae58-a64008cd5ac8
   * Codename: success_stories_component
   */
  successStoriesComponent: Elements.LinkedItemsElement<UmlpElementPartnerSuccessStoriesShowcaseModel>;

  /**
   * Heading (text)
   * Required: false
   * Id: 2d062bb5-8d81-4fcd-873d-5850af775d7f
   * Codename: heading
   */
  heading: Elements.TextElement;

  /**
   * Text (rich_text)
   * Required: false
   * Id: 965dde18-3b93-49a1-b6dd-8c32c0c8dec0
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * CTA (modular_content)
   * Required: false
   * Id: 4f1cbfc8-2c68-4e35-93d0-48bb073fee90
   * Codename: cta_4f1cbfc
   */
  cta4f1cbfc: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Heading (text)
   * Required: false
   * Id: 45f54086-e4f9-48fc-b176-046e07735693
   * Codename: heading_space
   */
  headingSpace: Elements.TextElement;

  /**
   * Text (rich_text)
   * Required: false
   * Id: 7fb18d38-39ad-47fb-b442-d097ec56d4cd
   * Codename: text_space
   */
  textSpace: Elements.RichTextElement;

  /**
   * CTA (modular_content)
   * Required: false
   * Id: bc09c912-53c9-4803-a872-4dd8dc9a45bd
   * Codename: cta_space
   */
  ctaSpace: Elements.LinkedItemsElement<SharedContentModel>;
}> &
  Metadata &
  SitemapMetadata;
