import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Partner Badge
 * Id: 7967fee3-cf6c-4fd6-be3b-27f72861f40c
 * Codename: partner_badge
 */
export type PartnerBadgeModel = IContentItem<{
  /**
   * Text (text)
   * Required: true
   * Id: 55d7eb78-4057-42a5-a1d7-03d8cb1a9381
   * Codename: text
   */
  text: Elements.TextElement;

  /**
   * Icon (asset)
   * Required: true
   * Id: 5a308e4b-5578-4e4d-8dca-86c9f66f5839
   * Codename: icon
   */
  icon: Elements.AssetsElement;
}>;
