import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { PartnerPlanModel } from './PartnerPlanModel';
import { ModularItemCardElementModel } from './ModularItemCardElementModel';
import { PricingPageFaqCategoryModel } from './PricingPageFaqCategoryModel';
import { ResourceLinkCategoryModel } from './ResourceLinkCategoryModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Partner Welcome page
 * Id: 757938ef-6fa3-438e-9eba-e51ab874c8b0
 * Codename: partner_welcome_page
 */
export type PartnerWelcomePageModel = IContentItem<{
  /**
   * Headline (text)
   * Required: false
   * Id: f4be77be-fdcf-44a0-bd82-9a8d221ef91c
   * Codename: headline
   */
  headline: Elements.TextElement;

  /**
   * Subheadline (text)
   * Required: false
   * Id: 2d5433e0-d001-41cc-80ad-8b4802a12896
   * Codename: subheadline
   */
  subheadline: Elements.TextElement;

  /**
   * Lead paragraph (rich_text)
   * Required: false
   * Id: 297619a2-36e4-4ccf-9f32-b98cff6d5856
   * Codename: lead_paragraph
   */
  leadParagraph: Elements.RichTextElement;

  /**
   * Hero image (asset)
   * Required: false
   * Id: e5117d86-4e93-481b-8c65-ad390c3084cb
   * Codename: hero_image
   */
  heroImage: Elements.AssetsElement;

  /**
   * Partner Plans title (text)
   * Required: false
   * Id: 9ce6ff5e-bae8-42c7-8530-68f260e05e86
   * Codename: partner_plans_title
   */
  partnerPlansTitle: Elements.TextElement;

  /**
   * Partner Plans items (modular_content)
   * Required: false
   * Id: 2c45b9c0-e7f4-484c-9f0f-7ee853e25cf3
   * Codename: partner_plans_items
   */
  partnerPlansItems: Elements.LinkedItemsElement<PartnerPlanModel>;

  /**
   * Get Started Steps title (text)
   * Required: false
   * Id: 592c34bd-ed69-40bc-946a-35269617917c
   * Codename: get_started_steps_title
   */
  getStartedStepsTitle: Elements.TextElement;

  /**
   * Get Started Steps items (modular_content)
   * Required: false
   * Id: d8198177-27f5-464a-8d52-a903383d4438
   * Codename: get_started_steps_items
   */
  getStartedStepsItems: Elements.LinkedItemsElement<ModularItemCardElementModel>;

  /**
   * FAQs title (text)
   * Required: false
   * Id: 09f7dcd5-a620-48d1-a9fa-fd5432b0a24c
   * Codename: faqs_title
   */
  faqsTitle: Elements.TextElement;

  /**
   * FAQs (modular_content)
   * Required: false
   * Id: 582f3b5d-9ee6-4076-adb7-ea9df110780b
   * Codename: faqs
   */
  faqs: Elements.LinkedItemsElement<PricingPageFaqCategoryModel>;

  /**
   * Useful Resources title (text)
   * Required: false
   * Id: 7915a567-9f58-4a5b-916a-c4dad0b49b1a
   * Codename: useful_resources_title
   */
  usefulResourcesTitle: Elements.TextElement;

  /**
   * Useful Resources categories (Left column) (modular_content)
   * Required: false
   * Id: 212d87bf-2f9d-4d06-a7a8-b3b515590683
   * Codename: useful_resources_categories__left_column_
   */
  usefulResourcesCategoriesLeftColumn: Elements.LinkedItemsElement<ResourceLinkCategoryModel>;

  /**
   * Useful Resources categories (Right column) (modular_content)
   * Required: false
   * Id: 9f99a7ea-83aa-4a8f-b26c-41bb407fc901
   * Codename: useful_resources_categories__right_column_
   *
   * OBSOLETE - Only "Left column" is used since redesign on 16th September 2019
   */
  usefulResourcesCategoriesRightColumn: Elements.LinkedItemsElement<ResourceLinkCategoryModel>;
}>;
