import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { PartnerPlanItemModel } from './PartnerPlanItemModel';
import { ReleaseProjects } from '../taxonomies/release_projects';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Partner Plan
 * Id: 797aba21-ed3b-4203-a576-a88efb80890e
 * Codename: partner_plan
 */
export type PartnerPlanModel = IContentItem<{
  /**
   * Partner level (multiple_choice)
   * Required: true
   * Id: f5a08f17-1774-4b2b-b752-9b5377ed45eb
   * Codename: partner_level
   */
  partnerLevel: Elements.MultipleChoiceElement;

  /**
   * Company title (text)
   * Required: false
   * Id: 21d4085e-b17a-4a18-96a8-585f33f8c00c
   * Codename: company_title
   */
  companyTitle: Elements.TextElement;

  /**
   * Plan title (text)
   * Required: false
   * Id: 768c0a69-60c9-488c-9e25-735ae2027614
   * Codename: plan_title
   */
  planTitle: Elements.TextElement;

  /**
   * Plan Features items (modular_content)
   * Required: false
   * Id: 04676d34-6755-47a3-9f8a-4f5ba8bf6372
   * Codename: plan_features_items
   */
  planFeaturesItems: Elements.LinkedItemsElement<PartnerPlanItemModel>;

  /**
   * Plan Requirements title (text)
   * Required: false
   * Id: 4e61ad7d-ad16-48cd-b347-aa776da9bf7b
   * Codename: plan_requirements_title
   */
  planRequirementsTitle: Elements.TextElement;

  /**
   * Plan Requirements items (modular_content)
   * Required: false
   * Id: d18c2b92-b146-45cd-aec8-a2b9a5bd2c57
   * Codename: plan_requirements_items
   */
  planRequirementsItems: Elements.LinkedItemsElement<PartnerPlanItemModel>;

  /**
   * Release projects (taxonomy)
   * Required: false
   * Id: 5a5957fa-b1c8-4c26-9382-f1fc0bff46cf
   * Codename: release_projects
   */
  releaseProjects: Elements.TaxonomyElement<ReleaseProjects>;
}>;
