import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Partner space contacts
 * Id: 639904c2-d753-4c88-8dc3-cc0c66b682f9
 * Codename: partner_space_contacts
 */
export type PartnerSpaceContactsModel = IContentItem<{
  /**
   * Title (text)
   * Required: false
   * Id: a04a1dcc-de0f-4ee5-a3d6-ecf338c183ff
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Contacts (rich_text)
   * Required: false
   * Id: d0335ba8-2cb9-4123-b5a5-2601b79faf3e
   * Codename: contacts
   */
  contacts: Elements.RichTextElement;
}>;
