import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { SitemapMetadata } from '../content-type-snippets/sitemap_metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Partner's Case Study
 * Id: 23d187e4-6678-4fec-a512-c74802490695
 * Codename: partner_s_case_study
 */
export type PartnerSCaseStudyModel = IContentItem<{
  /**
   * Title (text)
   * Required: true
   * Id: 259fc1c2-4ae5-4cac-906b-e5a23f412034
   * Codename: title
   *
   * Title of the project case study
   */
  title: Elements.TextElement;

  /**
   * URL (text)
   * Required: true
   * Id: b634a174-02ae-4f96-99fa-6c454d8ff76c
   * Codename: url
   *
   * URL of the case study on partner's website
   */
  url: Elements.TextElement;

  /**
   * Screenshot (asset)
   * Required: true
   * Id: af9cd497-8261-45d3-8c05-82c013e45300
   * Codename: screenshot
   *
   * Screenshot of the website / project to which the case study relates or case study screenshot representing the brand
   */
  screenshot: Elements.AssetsElement;

  /**
   * Date (date_time)
   * Required: true
   * Id: 5a83455f-8698-47a9-8af2-b0da76fa19ce
   * Codename: date
   *
   * Date when project to which the case study relates, was published
   */
  date: Elements.DateTimeElement;
}> &
  SitemapMetadata;
