import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Partner Plan Item
 * Id: 70519d6d-3d28-48d1-b4a4-3332c89095f1
 * Codename: partner_plan_item
 */
export type PartnerPlanItemModel = IContentItem<{
  /**
   * Title (text)
   * Required: false
   * Id: 97f4e5d6-e48e-43a7-be14-e28f8a6267b6
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Tooltip text (rich_text)
   * Required: false
   * Id: 7273bd91-3273-4fc7-aa4a-1dc398ede4d2
   * Codename: tooltip_text
   */
  tooltipText: Elements.RichTextElement;

  /**
   * Is highlighted (multiple_choice)
   * Required: false
   * Id: 4f859145-f779-4bc3-8c47-04eb15e24737
   * Codename: is_highlighted
   */
  isHighlighted: Elements.MultipleChoiceElement;
}>;
