import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Plain Text
 * Id: 7968a728-7ab1-43d4-81c2-447aa56b0672
 * Codename: plain_text
 */
export type PlainTextModel = IContentItem<{
  /**
   * Text (text)
   * Required: false
   * Id: 10b85cc9-bbd7-4d83-b58d-796468b1e3f9
   * Codename: text
   */
  text: Elements.TextElement;
}>;
