import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Pricing page - feature v3
 * Id: c7738e73-77b0-4147-a0c4-aa8502d6d42a
 * Codename: pricing_page___feature_v3
 */
export type PricingPageFeatureV3Model = IContentItem<{
  /**
   * Title (text)
   * Required: false
   * Id: 8849dd97-45ae-4546-8ee1-f7b68640e999
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Tooltip (rich_text)
   * Required: false
   * Id: 86a10c71-cf4d-4429-a139-e63e733b4125
   * Codename: tooltip
   */
  tooltip: Elements.RichTextElement;

  /**
   * Text (text)
   * Required: false
   * Id: 08c4c793-58ee-401c-a4b7-bd51887bb9d1
   * Codename: text_plan1
   */
  textPlan1: Elements.TextElement;

  /**
   * Note (text)
   * Required: false
   * Id: 372886c5-69a7-49cf-9143-87abb4fef4a9
   * Codename: note_plan1
   */
  notePlan1: Elements.TextElement;

  /**
   * Is checked (multiple_choice)
   * Required: false
   * Id: 5f62439e-8759-4646-97fb-17af2a3e17d9
   * Codename: is_checked_plan1
   */
  isCheckedPlan1: Elements.MultipleChoiceElement;

  /**
   * Text (text)
   * Required: false
   * Id: 80492820-d303-4e53-8560-9008c2302d0e
   * Codename: text_plan2
   */
  textPlan2: Elements.TextElement;

  /**
   * Note (text)
   * Required: false
   * Id: 77218a42-1dcb-497b-911f-7a49707d2767
   * Codename: note_plan2
   */
  notePlan2: Elements.TextElement;

  /**
   * Is checked (multiple_choice)
   * Required: false
   * Id: 011c1b94-f704-44e1-b845-3149844b7113
   * Codename: is_checked_plan2
   */
  isCheckedPlan2: Elements.MultipleChoiceElement;

  /**
   * Text (text)
   * Required: false
   * Id: 6d10262f-91e5-4015-b5a0-e5ac924b29a2
   * Codename: text_plan3
   */
  textPlan3: Elements.TextElement;

  /**
   * Note (text)
   * Required: false
   * Id: 99535dad-0e44-4716-a19b-0c2e21fea556
   * Codename: note_plan3
   */
  notePlan3: Elements.TextElement;

  /**
   * Is checked (multiple_choice)
   * Required: false
   * Id: 5ab0b10d-8bc0-4ebe-8184-e9afdaebc89f
   * Codename: is_checked_plan3
   */
  isCheckedPlan3: Elements.MultipleChoiceElement;
}>;
