import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Pricing Feature
 * Id: 9152886b-a5ff-48df-913a-43397ad92aa9
 * Codename: pricing_feature
 */
export type PricingFeatureModel = IContentItem<{
  /**
   * Title (text)
   * Required: false
   * Id: 33c9d63a-833f-4b40-92ec-5cbc0a7948cd
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * URL (text)
   * Required: false
   * Id: bfea181c-ca09-4dc5-89ab-660947bddd7e
   * Codename: url
   */
  url: Elements.TextElement;

  /**
   * Tracking code (text)
   * Required: false
   * Id: 0320bd4a-4f51-4d27-98d9-5f32f46b274b
   * Codename: tracking_code
   */
  trackingCode: Elements.TextElement;

  /**
   * Is optional (multiple_choice)
   * Required: false
   * Id: 16f0d050-1013-4fe8-8efe-915cc87f4d9c
   * Codename: is_optional
   */
  isOptional: Elements.MultipleChoiceElement;
}>;
