import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { ProductPageFeatureModel } from './ProductPageFeatureModel';
import { SharedContentModel } from './SharedContentModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Product page
 * Id: de5088ed-db33-48dc-880c-931b32f6c22c
 * Codename: product_page
 */
export type ProductPageModel = IContentItem<{
  /**
   * URL (url_slug)
   * Required: false
   * Id: d01eabd0-e182-3694-6d3f-01c268423691
   * Codename: url
   */
  url: Elements.UrlSlugElement;

  /**
   * Headline (text)
   * Required: false
   * Id: 0e99c69d-4faa-9c7a-f956-01929a79d821
   * Codename: headline
   */
  headline: Elements.TextElement;

  /**
   * Subheadline (text)
   * Required: false
   * Id: e5f4e1e2-30c9-3819-eb4f-8d477faa348c
   * Codename: subheadline
   */
  subheadline: Elements.TextElement;

  /**
   * Image (asset)
   * Required: false
   * Id: 40e45497-f2ce-0493-9deb-83df94ca7daa
   * Codename: image
   */
  image: Elements.AssetsElement;

  /**
   * Image frame (multiple_choice)
   * Required: false
   * Id: be6fda19-b88a-6cfa-27b4-a0656de573ff
   * Codename: image_frame
   *
   * Usually, screenshots have a frame (blue border around the image), illustrations by Matus with a transparent background not.
   */
  imageFrame: Elements.MultipleChoiceElement;

  /**
   * Image ALT (text)
   * Required: false
   * Id: 49554704-79c2-8caa-04a7-36aff51fe74d
   * Codename: image_alt
   */
  imageAlt: Elements.TextElement;

  /**
   * Features (modular_content)
   * Required: false
   * Id: 4d7ae673-d8d5-78c0-ec8a-89385f5f1f88
   * Codename: features
   */
  features: Elements.LinkedItemsElement<ProductPageFeatureModel>;

  /**
   * Roadmap link section (modular_content)
   * Required: false
   * Id: e8f408c2-0a04-f6f7-3089-47ef72970273
   * Codename: roadmap_link_section
   */
  roadmapLinkSection: Elements.LinkedItemsElement<IContentItem>;

  /**
   * CTA headline (modular_content)
   * Required: false
   * Id: 2957cad2-c681-533e-7b6c-30c10eabc358
   * Codename: cta_headline
   */
  ctaHeadline: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * CTA button (modular_content)
   * Required: false
   * Id: 9589311e-e704-b606-cfde-64f8574bbae5
   * Codename: cta_button
   */
  ctaButton: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Metadata title (text)
   * Required: false
   * Id: 7001dfe2-54e6-6444-ec53-8e31f6281140
   * Codename: metadata_title
   */
  metadataTitle: Elements.TextElement;

  /**
   * Metadata description (text)
   * Required: false
   * Id: 8affd3f8-9127-c465-6a19-e7bbbeff9c15
   * Codename: metadata_description
   */
  metadataDescription: Elements.TextElement;
}>;
