import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Product page - feature
 * Id: 9a37e2fe-74ed-4d15-a6cb-d3a922e8fa80
 * Codename: product_page___feature
 */
export type ProductPageFeatureModel = IContentItem<{
  /**
   * Name (text)
   * Required: false
   * Id: 4c11f2c2-db94-1036-5283-f07741737cb5
   * Codename: name
   */
  name: Elements.TextElement;

  /**
   * Description (rich_text)
   * Required: false
   * Id: 99724259-9cb1-5e67-5610-43b72053a944
   * Codename: description
   */
  description: Elements.RichTextElement;

  /**
   * Image (asset)
   * Required: false
   * Id: d53fb9f6-a64d-c1d1-2af5-e6a2261b0b39
   * Codename: image
   */
  image: Elements.AssetsElement;

  /**
   * Image 2x (asset)
   * Required: false
   * Id: 7eac9006-0368-4516-8697-6f59dc82ce13
   * Codename: image_2x
   */
  image2x: Elements.AssetsElement;

  /**
   * Image ALT (text)
   * Required: false
   * Id: e4346267-10e6-8a02-eaf7-aa4cd9fd4bf8
   * Codename: image_alt
   */
  imageAlt: Elements.TextElement;

  /**
   * Anchor (text)
   * Required: false
   * Id: 97b1c401-1f3c-7f10-b1d9-f4355a5129a7
   * Codename: anchor
   */
  anchor: Elements.TextElement;
}>;
