import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { ProductHighlightStepModel } from './ProductHighlightStepModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Product highlight
 * Id: 4fb0ef18-aaf4-46a6-b59f-b9995419452e
 * Codename: product_highlight
 */
export type ProductHighlightModel = IContentItem<{
  /**
   * Headline (rich_text)
   * Required: false
   * Id: ec4e9781-4368-4120-86f8-e51a90fe89bd
   * Codename: headline
   */
  headline: Elements.RichTextElement;

  /**
   * Description (rich_text)
   * Required: false
   * Id: 37a9c979-c6b0-4fbb-a657-c476ef87e2da
   * Codename: description
   */
  description: Elements.RichTextElement;

  /**
   * Image (asset)
   * Required: false
   * Id: c9ef843d-8eed-4b84-b0fe-0ab0e2830b31
   * Codename: image
   */
  image: Elements.AssetsElement;

  /**
   * Steps (modular_content)
   * Required: false
   * Id: e813fb90-4d4f-4643-80d4-0c4d714bdd24
   * Codename: steps
   *
   * If the highlight has additional sub-sections or steps, please add them here.
   */
  steps: Elements.LinkedItemsElement<ProductHighlightStepModel>;
}>;
