import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { ProductFeatureModel } from './ProductFeatureModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Product feature group
 * Id: cb2bdb92-fe07-4910-a9c5-961f1fe3f784
 * Codename: product_feature_group
 */
export type ProductFeatureGroupModel = IContentItem<{
  /**
   * Heading (text)
   * Required: true
   * Id: ce780510-bef4-4d44-bb41-61827d13e8d7
   * Codename: heading
   */
  heading: Elements.TextElement;

  /**
   * Description (rich_text)
   * Required: true
   * Id: 1a351297-338b-4b07-b4d5-fc986cc0fe40
   * Codename: description
   */
  description: Elements.RichTextElement;

  /**
   * Features (modular_content)
   * Required: false
   * Id: 7046994a-9f09-459a-9d3a-87f612b26ee3
   * Codename: features
   */
  features: Elements.LinkedItemsElement<ProductFeatureModel>;
}>;
