import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { LinkModel } from './LinkModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Product and Company info
 * Id: 0b621e87-7f46-4614-8419-93705a10ec4d
 * Codename: product_and_company_info
 */
export type ProductAndCompanyInfoModel = IContentItem<{
  /**
   * Product name (text)
   * Required: false
   * Id: 0007cf45-f467-4d3c-9260-4ec38946c94d
   * Codename: product_name
   */
  productName: Elements.TextElement;

  /**
   * Product URL (text)
   * Required: false
   * Id: 382fc29a-305d-44e2-978d-34bcadfeb891
   * Codename: product_url
   */
  productUrl: Elements.TextElement;

  /**
   * Product logo (asset)
   * Required: false
   * Id: 33312d8e-2774-413e-ac3e-7a872608046c
   * Codename: product_logo
   */
  productLogo: Elements.AssetsElement;

  /**
   * Product social media (modular_content)
   * Required: false
   * Id: bd6df618-7571-4d62-9ea6-dbeb70bcae1e
   * Codename: product_social_media
   */
  productSocialMedia: Elements.LinkedItemsElement<LinkModel>;

  /**
   * Company name (text)
   * Required: false
   * Id: 2af05a56-7ea0-481f-a580-1050e339b263
   * Codename: company_name
   */
  companyName: Elements.TextElement;
}>;
