import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { Metadata } from '../content-type-snippets/metadata';
import { CtaBannerComponentModel } from './CtaBannerComponentModel';
import { ReleaseProjects } from '../taxonomies/release_projects';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Product - Community page
 * Id: c7b30dbb-f6e9-4a5e-8dc0-bbfd8b64822a
 * Codename: product___community_page
 */
export type ProductCommunityPageModel = IContentItem<{
  /**
   * Hero Section (rich_text)
   * Required: false
   * Id: 3469d930-5010-4597-881d-7de27a3814f0
   * Codename: hero_section
   */
  heroSection: Elements.RichTextElement;

  /**
   * Thumbnail title (text)
   * Required: false
   * Id: 42b090bc-4fd1-400a-bd0d-6bf2a6cef8b3
   * Codename: thumbnail_title
   */
  thumbnailTitle: Elements.TextElement;

  /**
   * Thumbnail Section (rich_text)
   * Required: false
   * Id: 47258a86-e160-4dba-87f5-1b01eecc656d
   * Codename: thumbnail_section
   */
  thumbnailSection: Elements.RichTextElement;

  /**
   * Gitter title (text)
   * Required: false
   * Id: d0aaf352-62ae-40a0-a6c7-aadbae8f4cec
   * Codename: gitter_title
   */
  gitterTitle: Elements.TextElement;

  /**
   * Gitter section (rich_text)
   * Required: false
   * Id: a93c01fa-9ed3-4400-aa3c-dfbb82ac5484
   * Codename: gitter_section
   */
  gitterSection: Elements.RichTextElement;

  /**
   * CTA Banner (modular_content)
   * Required: false
   * Id: ce141589-c90d-4c09-8cd5-3dc5dfb76754
   * Codename: cta_banner
   */
  ctaBanner: Elements.LinkedItemsElement<CtaBannerComponentModel>;

  /**
   * Release projects (taxonomy)
   * Required: false
   * Id: c8a8a252-8731-45b9-a4ac-8347552ec22d
   * Codename: release_projects
   */
  releaseProjects: Elements.TaxonomyElement<ReleaseProjects>;
}> &
  Metadata;
