import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Product highlight step
 * Id: 2d3119ea-f8f8-4e82-bf3c-e21319a4f56a
 * Codename: product_highlight_step
 */
export type ProductHighlightStepModel = IContentItem<{
  /**
   * Headline (rich_text)
   * Required: false
   * Id: 3f5b659d-bf11-4b43-bd5d-d83c4c5f7ca0
   * Codename: headline
   */
  headline: Elements.RichTextElement;

  /**
   * Description (rich_text)
   * Required: false
   * Id: a4d6f706-16f0-44d7-a34e-077c1a639a8f
   * Codename: description
   */
  description: Elements.RichTextElement;

  /**
   * Image (asset)
   * Required: false
   * Id: dff096c6-a97e-4b21-8b27-e002b27d5033
   * Codename: image
   */
  image: Elements.AssetsElement;
}>;
