import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Resource Link
 * Id: 202417f1-20f5-4863-bc4d-2c06dec0f886
 * Codename: resource_link
 */
export type ResourceLinkModel = IContentItem<{
  /**
   * Title (text)
   * Required: false
   * Id: b82a67ef-561b-4aa5-83fe-29fafe1b426e
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Resource asset (asset)
   * Required: false
   * Id: 4ead289b-fe4d-4b8d-a978-536a76d9a36f
   * Codename: resource_asset
   */
  resourceAsset: Elements.AssetsElement;

  /**
   * URL (text)
   * Required: false
   * Id: 4c2d0190-080e-455a-9e0b-1fd11bd64d13
   * Codename: url
   */
  url: Elements.TextElement;

  /**
   * Type (text)
   * Required: false
   * Id: e71c168a-ca0a-4c71-9f5b-43d16c9e58e7
   * Codename: type
   *
   * Type of file (Like pdf, zip, .. or can be empty)
   */
  type: Elements.TextElement;
}>;
