import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Review
 * Id: 86fbe2b3-94ed-48cc-81a0-d1482a5d2476
 * Codename: review
 */
export type ReviewModel = IContentItem<{
  /**
   * Title (text)
   * Required: false
   * Id: 30d11cb3-cf88-47eb-bb0f-8944876173f4
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Rating (number)
   * Required: false
   * Id: a126aaa7-70c2-4362-bb75-c8f306ba2330
   * Codename: rating
   */
  rating: Elements.NumberElement;

  /**
   * Text (rich_text)
   * Required: false
   * Id: 8071c107-e630-4235-814f-9bf75fb03cd4
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * Full review URL (text)
   * Required: false
   * Id: 8ec54e96-f391-45da-881a-536377ee4e34
   * Codename: full_review_url
   */
  fullReviewUrl: Elements.TextElement;

  /**
   * Name (text)
   * Required: false
   * Id: dc4f3546-b860-426f-9326-d4d4691c49ed
   * Codename: name
   */
  name: Elements.TextElement;

  /**
   * Position (text)
   * Required: false
   * Id: 585012ac-fdd2-429e-9cfd-43656e109c54
   * Codename: position
   */
  position: Elements.TextElement;

  /**
   * Company (text)
   * Required: false
   * Id: 628e4743-f3b3-4e5d-a5b8-73717fcba885
   * Codename: company
   */
  company: Elements.TextElement;

  /**
   * Photo (asset)
   * Required: false
   * Id: 9f0a965f-9f7e-4e0d-8b5d-bf856766aa4b
   * Codename: photo
   */
  photo: Elements.AssetsElement;
}>;
