import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { Hero } from '../content-type-snippets/hero';
import { RoadmapFeatureStatusModel } from './RoadmapFeatureStatusModel';
import { SharedContentModel } from './SharedContentModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Roadmap page
 * Id: 311c4fd7-2287-41d3-b6c5-38db4226349d
 * Codename: roadmap_page
 */
export type RoadmapPageModel = IContentItem<{
  /**
   * Feedback link text (text)
   * Required: false
   * Id: f1083f9d-a93b-4868-91c9-97725b20cff9
   * Codename: feedback_link_text
   */
  feedbackLinkText: Elements.TextElement;

  /**
   * Category title (text)
   * Required: false
   * Id: 9c49b9b5-f488-85f5-4b9c-c9eac1389ad9
   * Codename: category_title
   */
  categoryTitle: Elements.TextElement;

  /**
   * Released title (text)
   * Required: false
   * Id: e44bbadc-f333-4e1c-f493-71ed789b2513
   * Codename: released_title
   */
  releasedTitle: Elements.TextElement;

  /**
   * Planned Release title (text)
   * Required: false
   * Id: f65be3b4-eb26-2a21-827b-3d1cf80fdd3b
   * Codename: planned_release_title
   */
  plannedReleaseTitle: Elements.TextElement;

  /**
   * Available in Plans title (text)
   * Required: false
   * Id: f95acf1f-b034-b1a3-dc4c-63967646858b
   * Codename: available_in_plans_title
   */
  availableInPlansTitle: Elements.TextElement;

  /**
   * Feature Statuses (modular_content)
   * Required: false
   * Id: d49bb09e-0fac-42a2-a175-fc80b4e3fe28
   * Codename: feature_statuses
   */
  featureStatuses: Elements.LinkedItemsElement<RoadmapFeatureStatusModel>;

  /**
   * Share title (text)
   * Required: false
   * Id: ae4165b2-16c3-dc45-e57a-853989a0e486
   * Codename: share_title
   */
  shareTitle: Elements.TextElement;

  /**
   * Update text (rich_text)
   * Required: false
   * Id: 9a0df9d4-84e9-4c29-80bd-caac7051b53f
   * Codename: update_text
   */
  updateText: Elements.RichTextElement;

  /**
   * Empty state text 2 (text)
   * Required: false
   * Id: 9ae8b23e-44d5-15fc-9312-5937969f4172
   * Codename: empty_state_text_2
   *
   * When there is no relevant feature in app, use this text.
   */
  emptyStateText2: Elements.TextElement;

  /**
   * Empty state text for filter (text)
   * Required: false
   * Id: 3565d1dd-4ad2-5d69-5ca6-327024d771c9
   * Codename: empty_state_text_for_filter
   *
   * When the user filters out all features using the filter, she will see this message.
   */
  emptyStateTextForFilter: Elements.TextElement;

  /**
   * Empty state text (modular_content)
   * Required: false
   * Id: cb2d8b9e-eeab-6cf6-08b7-bcb2a90cd0e4
   * Codename: empty_state_text
   */
  emptyStateText: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Empty state link (modular_content)
   * Required: false
   * Id: 637e82b2-c7b7-ca12-9803-f062172c5479
   * Codename: empty_state_link
   */
  emptyStateLink: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Metadata title (text)
   * Required: false
   * Id: 53eced83-07b3-4b52-b0b3-9ff62bca6b03
   * Codename: metadata_title
   */
  metadataTitle: Elements.TextElement;

  /**
   * Metadata description (text)
   * Required: false
   * Id: 0743cf20-bd0f-1a3b-094b-40606ad481be
   * Codename: metadata_description
   */
  metadataDescription: Elements.TextElement;

  /**
   * Metadata image (asset)
   * Required: false
   * Id: e12835f2-0322-6709-aac8-ecf21a50e461
   * Codename: metadata_image
   */
  metadataImage: Elements.AssetsElement;
}> &
  Hero;
