import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Security Feature Item
 * Id: 51107ec2-5f6b-4f46-acfe-05b440647205
 * Codename: security_feature_item
 */
export type SecurityFeatureItemModel = IContentItem<{
  /**
   * Image (asset)
   * Required: false
   * Id: d81f5e34-b6a1-4664-9666-12b721fd96be
   * Codename: image
   */
  image: Elements.AssetsElement;

  /**
   * Title (text)
   * Required: false
   * Id: 3e3a82cd-11cf-4c1a-a7ec-5645ddc3d681
   * Codename: title
   */
  title: Elements.TextElement;
}>;
