import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { Hero } from '../content-type-snippets/hero';
import { SitemapMetadata } from '../content-type-snippets/sitemap_metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Services page
 * Id: 6aed4ecf-e564-4c8d-97a0-58d92a8ae6cb
 * Codename: services_page
 */
export type ServicesPageModel = IContentItem<{
  /**
   * Metadata title (text)
   * Required: false
   * Id: 5f7d2f3b-551b-41e3-826c-6f24b424b36b
   * Codename: metadata_title
   */
  metadataTitle: Elements.TextElement;

  /**
   * Metadata description (text)
   * Required: false
   * Id: 41a2cf4f-7f3e-4d67-ab00-c1f4f2875305
   * Codename: metadata_description
   */
  metadataDescription: Elements.TextElement;

  /**
   * Lead heading (text)
   * Required: false
   * Id: cd64c84c-2864-442d-8057-c345a52d02a1
   * Codename: lead_heading
   */
  leadHeading: Elements.TextElement;

  /**
   * Lead paragraph (rich_text)
   * Required: false
   * Id: c8fce082-2040-45d8-999b-117548df3c96
   * Codename: lead_paragraph
   */
  leadParagraph: Elements.RichTextElement;

  /**
   * Text (rich_text)
   * Required: false
   * Id: 9219093a-14aa-4b7f-8b4a-b5ac2c81fca7
   * Codename: text
   */
  text: Elements.RichTextElement;
}> &
  Hero &
  SitemapMetadata;
