import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Services - Premium Plan
 * Id: 421bb941-3cea-4f33-bb23-42b6c2173edb
 * Codename: services___premium_plan
 */
export type ServicesPremiumPlanModel = IContentItem<{
  /**
   * Plan name (rich_text)
   * Required: false
   * Id: b48bf89d-cb5f-4c8f-9079-527bc129ecb7
   * Codename: plan_name
   */
  planName: Elements.RichTextElement;

  /**
   * Price per month (text)
   * Required: false
   * Id: 12955d30-8e8c-4fcb-b0ea-3a5663c1fc60
   * Codename: price_per_month
   */
  pricePerMonth: Elements.TextElement;

  /**
   * Description (rich_text)
   * Required: false
   * Id: 844bb6e6-c1ba-47f8-9bd8-96eddf57ddda
   * Codename: description
   */
  description: Elements.RichTextElement;

  /**
   * Response time (rich_text)
   * Required: false
   * Id: 26728b50-ad26-442b-9130-b55fde75ca06
   * Codename: response_time
   */
  responseTime: Elements.RichTextElement;
}>;
