import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Services KK - Unordered List Item
 * Id: 058c275d-f2eb-46d9-ad72-121f01ce3599
 * Codename: services_kk___unordered_list_item
 */
export type ServicesKkUnorderedListItemModel = IContentItem<{
  /**
   * Text (text)
   * Required: false
   * Id: 92b6ec78-0b5c-4706-a987-93e02deaed8a
   * Codename: text
   *
   * text of the <li></li> element
   */
  text: Elements.TextElement;
}>;
