import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { ServicesKkUnorderedListItemModel } from './ServicesKkUnorderedListItemModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Services KK - Unordered List
 * Id: c442c219-c4b5-4a7b-af3e-1aadcd885bda
 * Codename: services_kk___unordered_list
 */
export type ServicesKkUnorderedListModel = IContentItem<{
  /**
   * Icon (asset)
   * Required: false
   * Id: de5992b8-1fae-4dd5-9ece-17e01ea663b1
   * Codename: icon
   *
   * Icon next to the heading
   */
  icon: Elements.AssetsElement;

  /**
   * Bullet (asset)
   * Required: false
   * Id: fa95bcdc-5c35-4191-a10a-916658870bd1
   * Codename: bullet
   *
   * Different bullet/dash next to li
   */
  bullet: Elements.AssetsElement;

  /**
   * Heading (text)
   * Required: false
   * Id: 6aa7b44f-b4d5-4464-a682-e16ee6e8f891
   * Codename: heading
   */
  heading: Elements.TextElement;

  /**
   * List (modular_content)
   * Required: false
   * Id: 204fdd08-1f50-4794-a97c-de0d6ee4bf14
   * Codename: list
   */
  list: Elements.LinkedItemsElement<ServicesKkUnorderedListItemModel>;
}>;
