import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Solutions page - Product Capability
 * Id: a73acb48-46c5-46d3-988c-94731ad5b677
 * Codename: solutions_page___product_capability
 */
export type SolutionsPageProductCapabilityModel = IContentItem<{
  /**
   * Title (text)
   * Required: false
   * Id: 8a8f3b0b-ee17-469e-8de1-a53f1726725f
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Description (rich_text)
   * Required: true
   * Id: 95ad8fcc-3f26-41a1-9c6a-e874f29fc82b
   * Codename: description_rich
   */
  descriptionRich: Elements.RichTextElement;

  /**
   * Description (obsolete) (text)
   * Required: false
   * Id: fd0bb92c-fa15-4af2-bc13-7885909772f3
   * Codename: description
   */
  description: Elements.TextElement;

  /**
   * Image (asset)
   * Required: false
   * Id: d74b768b-c9d9-4a4c-a572-e42566919650
   * Codename: image
   */
  image: Elements.AssetsElement;
}>;
