import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { HeroKK } from '../content-type-snippets/hero_kk';
import { LogoModel } from './LogoModel';
import { SolutionsPageProductCapabilityModel } from './SolutionsPageProductCapabilityModel';
import { SolutionsPageCustomerHighlightModel } from './SolutionsPageCustomerHighlightModel';
import { TestimonialModel } from './TestimonialModel';
import { SolutionsPageCtaModel } from './SolutionsPageCtaModel';
import { SolutionsPageRelatedAssetModel } from './SolutionsPageRelatedAssetModel';
import { EnterpriseFeatureKkModel } from './EnterpriseFeatureKkModel';
import { IntegrationModel } from './IntegrationModel';
import { SharedContentModel } from './SharedContentModel';
import { Metadata } from '../content-type-snippets/metadata';
import { SitemapMetadata } from '../content-type-snippets/sitemap_metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Solutions page 2: Digital Experience Stack
 * Id: 465b7b78-0348-42db-8a52-fa42db55e91e
 * Codename: solutions_page_digital_experience_stack
 */
export type SolutionsPageDigitalExperienceStackModel = IContentItem<{
  /**
   * Summary "Kontent helps you" (rich_text)
   * Required: true
   * Id: 937eea5e-c292-481a-80f4-b472d7e8ad07
   * Codename: summary_kontent_helps_you
   */
  summaryKontentHelpsYou: Elements.RichTextElement;

  /**
   * Logo sub-headline (text)
   * Required: true
   * Id: 0f1b0cc8-086e-4dfa-b9f4-a5892f2b8c70
   * Codename: logo_sub_headline
   */
  logoSubHeadline: Elements.TextElement;

  /**
   * Logo unit (modular_content)
   * Required: true
   * Id: 0edc08a9-9692-43b7-8a44-0b4bf5a676fa
   * Codename: logo_unit
   */
  logoUnit: Elements.LinkedItemsElement<LogoModel>;

  /**
   * Capability unit: Add content to microservices (modular_content)
   * Required: true
   * Id: eaaf7131-2e8e-4c95-a9b1-a99740656402
   * Codename: capability_unit_add_content_to_microservices
   *
   * For devs: display text on the left, image on the right
   */
  capabilityUnitAddContentToMicroservices: Elements.LinkedItemsElement<SolutionsPageProductCapabilityModel>;

  /**
   * Customer Highlight (modular_content)
   * Required: true
   * Id: 081b30e7-cfa6-4aeb-9aaf-ea6136a2242e
   * Codename: customer_highlight
   *
   * For devs: display text on the right, image on the left
   */
  customerHighlight: Elements.LinkedItemsElement<SolutionsPageCustomerHighlightModel>;

  /**
   * Capability unit: Deploy quickly (modular_content)
   * Required: true
   * Id: 560dc474-5919-45fa-86e7-ed0d9384bd70
   * Codename: capability_unit_deploy_quickly
   */
  capabilityUnitDeployQuickly: Elements.LinkedItemsElement<SolutionsPageProductCapabilityModel>;

  /**
   * Testimonial (modular_content)
   * Required: true
   * Id: 175ec82e-c458-4e11-beff-741aac89a24c
   * Codename: testimonial
   */
  testimonial: Elements.LinkedItemsElement<TestimonialModel>;

  /**
   * Capability unit: Extend to systems (modular_content)
   * Required: true
   * Id: 8fcd28c9-d8eb-4f54-bb69-442b82d434ab
   * Codename: capability_unit_extend_to_systems
   */
  capabilityUnitExtendToSystems: Elements.LinkedItemsElement<SolutionsPageProductCapabilityModel>;

  /**
   * Capability unit: Integrate with services (modular_content)
   * Required: true
   * Id: 092c1117-f9e8-4abf-8db6-f0e5aa11620f
   * Codename: capability_unit_integrate_with_services
   */
  capabilityUnitIntegrateWithServices: Elements.LinkedItemsElement<SolutionsPageProductCapabilityModel>;

  /**
   * CTA unit (modular_content)
   * Required: true
   * Id: 52e26e07-7233-49ce-95d9-353cc7fe03e7
   * Codename: cta
   */
  cta: Elements.LinkedItemsElement<SolutionsPageCtaModel>;

  /**
   * Related assets (modular_content)
   * Required: true
   * Id: c1ee7ebf-a1d5-4bcb-8b5c-69904148b0d4
   * Codename: related_assets
   */
  relatedAssets: Elements.LinkedItemsElement<SolutionsPageRelatedAssetModel>;

  /**
   * Integrations headline (text)
   * Required: false
   * Id: a2c57ac7-0f37-490a-898e-2e90a1e40676
   * Codename: integrations_headline
   */
  integrationsHeadline: Elements.TextElement;

  /**
   * Integrations lead paragraph (rich_text)
   * Required: false
   * Id: 26c4ef11-d48a-46cd-a84a-3d1378970313
   * Codename: integrations_lead_paragraph
   */
  integrationsLeadParagraph: Elements.RichTextElement;

  /**
   * Integration Highlights list (modular_content)
   * Required: false
   * Id: e01ec5cc-ea72-4841-ad1f-b1329cb89902
   * Codename: integration_highlights_list
   */
  integrationHighlightsList: Elements.LinkedItemsElement<EnterpriseFeatureKkModel>;

  /**
   * Integrations list (modular_content)
   * Required: false
   * Id: 7cbc12c0-fafd-4abd-bd84-7739b0d82b96
   * Codename: integrations_list
   */
  integrationsList: Elements.LinkedItemsElement<IntegrationModel>;

  /**
   * Integrations CTA (modular_content)
   * Required: false
   * Id: fd09426c-9300-4f6f-8cce-761bf143f48e
   * Codename: integrations_cta
   */
  integrationsCta: Elements.LinkedItemsElement<SharedContentModel>;
}> &
  HeroKK &
  Metadata &
  SitemapMetadata;
