import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { HeroKK } from '../content-type-snippets/hero_kk';
import { LogoModel } from './LogoModel';
import { SolutionsPageProductCapabilityModel } from './SolutionsPageProductCapabilityModel';
import { SolutionsPageCustomerHighlightModel } from './SolutionsPageCustomerHighlightModel';
import { TestimonialModel } from './TestimonialModel';
import { SolutionsPageCtaModel } from './SolutionsPageCtaModel';
import { SolutionsPageRelatedAssetModel } from './SolutionsPageRelatedAssetModel';
import { Metadata } from '../content-type-snippets/metadata';
import { SitemapMetadata } from '../content-type-snippets/sitemap_metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Solutions page 1: Reach more customers
 * Id: c3c0dae3-7088-426b-b623-b89780c7de8f
 * Codename: solutions_page_reach_more_customers
 */
export type SolutionsPageReachMoreCustomersModel = IContentItem<{
  /**
   * Summary "Kontent helps you" (rich_text)
   * Required: true
   * Id: c2a76754-6481-4d1d-a6b8-c3cb0a289b9f
   * Codename: summary_kontent_helps_you
   */
  summaryKontentHelpsYou: Elements.RichTextElement;

  /**
   * Logo sub-headline (text)
   * Required: true
   * Id: ab0e69bc-8790-4d31-bee9-7ba02ed9566e
   * Codename: logo_sub_headline
   */
  logoSubHeadline: Elements.TextElement;

  /**
   * Logo unit (modular_content)
   * Required: true
   * Id: cdee992d-b67f-4ddf-9248-be057e475b82
   * Codename: logo_unit
   */
  logoUnit: Elements.LinkedItemsElement<LogoModel>;

  /**
   * Capability unit: Localize content (modular_content)
   * Required: true
   * Id: ea80ec67-ece1-4326-ac27-386ada3bb754
   * Codename: capability_unit_localize_content
   *
   * For devs: display text on the left, image on the right
   */
  capabilityUnitLocalizeContent: Elements.LinkedItemsElement<SolutionsPageProductCapabilityModel>;

  /**
   * Customer Highlight (modular_content)
   * Required: true
   * Id: 5330a6ba-ba62-4b68-97d5-a3175d836822
   * Codename: customer_highlight
   *
   * For devs: display text on the right, image on the left
   */
  customerHighlight: Elements.LinkedItemsElement<SolutionsPageCustomerHighlightModel>;

  /**
   * Capability unit: Reach customers (modular_content)
   * Required: true
   * Id: c5708a19-43ea-4e7c-96c7-7d1d84d1840a
   * Codename: capability_unit_reach_customers
   */
  capabilityUnitReachCustomers: Elements.LinkedItemsElement<SolutionsPageProductCapabilityModel>;

  /**
   * Testimonial (modular_content)
   * Required: true
   * Id: f55a0737-4a37-4896-a127-29ce92a7d44b
   * Codename: testimonial
   */
  testimonial: Elements.LinkedItemsElement<TestimonialModel>;

  /**
   * Capability unit: Deliver relevant content (modular_content)
   * Required: true
   * Id: e09f2c3e-2d86-4395-bb05-c20057f8a579
   * Codename: capability_unit_deliver_relevant_content
   */
  capabilityUnitDeliverRelevantContent: Elements.LinkedItemsElement<SolutionsPageProductCapabilityModel>;

  /**
   * Capability unit: Control the experience (modular_content)
   * Required: true
   * Id: e3fbfa7d-1d81-4445-b5d4-d9b362b4a8be
   * Codename: capability_unit_control_experience
   */
  capabilityUnitControlExperience: Elements.LinkedItemsElement<SolutionsPageProductCapabilityModel>;

  /**
   * CTA unit (modular_content)
   * Required: true
   * Id: 0bae70f5-9424-4ea2-9a6c-a1d5295b1c79
   * Codename: cta
   */
  cta: Elements.LinkedItemsElement<SolutionsPageCtaModel>;

  /**
   * Related assets (modular_content)
   * Required: true
   * Id: 7f3fdd42-8298-4ab1-9417-31e319a3c5e6
   * Codename: related_assets
   */
  relatedAssets: Elements.LinkedItemsElement<SolutionsPageRelatedAssetModel>;
}> &
  HeroKK &
  Metadata &
  SitemapMetadata;
