import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { HeroKK } from '../content-type-snippets/hero_kk';
import { LogoModel } from './LogoModel';
import { SolutionsPageProductCapabilityModel } from './SolutionsPageProductCapabilityModel';
import { SolutionsPageCustomerHighlightModel } from './SolutionsPageCustomerHighlightModel';
import { TestimonialModel } from './TestimonialModel';
import { SolutionsPageCtaModel } from './SolutionsPageCtaModel';
import { SolutionsPageRelatedAssetModel } from './SolutionsPageRelatedAssetModel';
import { Metadata } from '../content-type-snippets/metadata';
import { SitemapMetadata } from '../content-type-snippets/sitemap_metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Solutions page 3: Unify content
 * Id: 1f7f282f-38ea-4fa4-b45c-07a06697186d
 * Codename: solutions_page_unify_content
 */
export type SolutionsPageUnifyContentModel = IContentItem<{
  /**
   * Summary "Kontent helps you" (rich_text)
   * Required: true
   * Id: 53edee7c-0814-4040-a606-cb0a03c8777a
   * Codename: summary_kontent_helps_you
   */
  summaryKontentHelpsYou: Elements.RichTextElement;

  /**
   * Logo sub-headline (text)
   * Required: true
   * Id: f89eb80e-483c-43fb-a4e4-f0ac2196fee5
   * Codename: logo_sub_headline
   */
  logoSubHeadline: Elements.TextElement;

  /**
   * Logo unit (modular_content)
   * Required: true
   * Id: 7ff6ef55-d720-42e6-ac5d-004f450306de
   * Codename: logo_unit
   */
  logoUnit: Elements.LinkedItemsElement<LogoModel>;

  /**
   * Capability unit: Organize content (modular_content)
   * Required: false
   * Id: 2331ab7b-0b9a-41d1-8502-44a12469bff6
   * Codename: capability_unit_organize_content
   */
  capabilityUnitOrganizeContent: Elements.LinkedItemsElement<SolutionsPageProductCapabilityModel>;

  /**
   * Capability unit: Govern access to content types (modular_content)
   * Required: true
   * Id: 1a1dd328-b70f-4a65-9b0b-69607347e4d0
   * Codename: capability_unit_govern_access
   *
   * For devs: display text on the left, image on the right
   */
  capabilityUnitGovernAccess: Elements.LinkedItemsElement<SolutionsPageProductCapabilityModel>;

  /**
   * Customer Highlight (modular_content)
   * Required: true
   * Id: 86175049-da47-4899-882e-727cfe0b50a9
   * Codename: customer_highlight
   *
   * For devs: display text on the right, image on the left
   */
  customerHighlight: Elements.LinkedItemsElement<SolutionsPageCustomerHighlightModel>;

  /**
   * Capability unit: Collaborate with stakeholders (modular_content)
   * Required: true
   * Id: 22f1cce4-5e5b-4b9c-ac80-2ef5df2d91fc
   * Codename: capability_unit_collaborate
   */
  capabilityUnitCollaborate: Elements.LinkedItemsElement<SolutionsPageProductCapabilityModel>;

  /**
   * Testimonial (modular_content)
   * Required: true
   * Id: ed245593-1f1f-4d5e-8ae4-464330940533
   * Codename: testimonial
   */
  testimonial: Elements.LinkedItemsElement<TestimonialModel>;

  /**
   * Capability unit: Improve brand consistency (modular_content)
   * Required: true
   * Id: 99b87eb5-ba02-4333-bd19-fbe539b68e14
   * Codename: capability_unit_improve_brand_consistency
   */
  capabilityUnitImproveBrandConsistency: Elements.LinkedItemsElement<SolutionsPageProductCapabilityModel>;

  /**
   * Capability unit: Reuse content (modular_content)
   * Required: true
   * Id: a2480420-3738-4c50-8d8f-db49a48d1c18
   * Codename: capability_unit_reuse_content
   */
  capabilityUnitReuseContent: Elements.LinkedItemsElement<SolutionsPageProductCapabilityModel>;

  /**
   * Capability unit: Distribute content (modular_content)
   * Required: true
   * Id: abd3fda4-698d-40e0-bed5-84f7db049edd
   * Codename: capability_unit_distribute_content
   */
  capabilityUnitDistributeContent: Elements.LinkedItemsElement<SolutionsPageProductCapabilityModel>;

  /**
   * CTA unit (modular_content)
   * Required: true
   * Id: e6c2905b-ee18-45ce-922f-efc2c94dd834
   * Codename: cta
   */
  cta: Elements.LinkedItemsElement<SolutionsPageCtaModel>;

  /**
   * Related assets (modular_content)
   * Required: true
   * Id: 10d53db4-92d0-4f7e-9377-606d7638c7ac
   * Codename: related_assets
   */
  relatedAssets: Elements.LinkedItemsElement<SolutionsPageRelatedAssetModel>;
}> &
  HeroKK &
  Metadata &
  SitemapMetadata;
