import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { HeroKK } from '../content-type-snippets/hero_kk';
import { LogoModel } from './LogoModel';
import { SolutionsPageProductCapabilityModel } from './SolutionsPageProductCapabilityModel';
import { SolutionsPageCustomerHighlightModel } from './SolutionsPageCustomerHighlightModel';
import { TestimonialModel } from './TestimonialModel';
import { SolutionsPageCtaModel } from './SolutionsPageCtaModel';
import { SolutionsPageRelatedAssetModel } from './SolutionsPageRelatedAssetModel';
import { Metadata } from '../content-type-snippets/metadata';
import { SitemapMetadata } from '../content-type-snippets/sitemap_metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Solutions page
 * Id: 58a05197-d532-4733-a49b-a7af564e7168
 * Codename: solutions_page
 */
export type SolutionsPageModel = IContentItem<{
  /**
   * Summary "Kontent helps you" (rich_text)
   * Required: false
   * Id: dad7af85-9f79-422f-aa8a-0d3dda43a0dc
   * Codename: summary__kontent_helps_you_
   */
  summaryKontentHelpsYou: Elements.RichTextElement;

  /**
   * Logo sub-headline (text)
   * Required: false
   * Id: ca05b27e-f2c3-41b1-908d-b43706022903
   * Codename: logo_sub_headline
   */
  logoSubHeadline: Elements.TextElement;

  /**
   * Logo unit (modular_content)
   * Required: true
   * Id: 0b6fdc42-9be4-4394-8035-c96abb52637c
   * Codename: logo_unit
   */
  logoUnit: Elements.LinkedItemsElement<LogoModel>;

  /**
   * Capability unit (modular_content)
   * Required: true
   * Id: 58cd39e1-e442-49a8-b10e-9ac17c47ceb9
   * Codename: capability_unit
   *
   * For devs: display text on the left, image on the right
   */
  capabilityUnit: Elements.LinkedItemsElement<SolutionsPageProductCapabilityModel>;

  /**
   * Customer Highlight (modular_content)
   * Required: true
   * Id: ffc68191-2cbf-4d8c-8eac-e25386047bd6
   * Codename: customer_highlight
   *
   * For devs: display text on the right, image on the left
   */
  customerHighlight: Elements.LinkedItemsElement<SolutionsPageCustomerHighlightModel>;

  /**
   * Capability unit (modular_content)
   * Required: true
   * Id: b3f795d7-3968-4ba7-84f9-a1cb2f17b332
   * Codename: capability_unit_2
   */
  capabilityUnit2: Elements.LinkedItemsElement<SolutionsPageProductCapabilityModel>;

  /**
   * Testimonial (modular_content)
   * Required: true
   * Id: 35a46766-6a57-4942-995c-3866375a1305
   * Codename: testimonial
   */
  testimonial: Elements.LinkedItemsElement<TestimonialModel>;

  /**
   * Capability units (modular_content)
   * Required: true
   * Id: 1ce262b1-9285-420c-9d2a-6ad4f6359f8b
   * Codename: capability_units
   */
  capabilityUnits: Elements.LinkedItemsElement<SolutionsPageProductCapabilityModel>;

  /**
   * CTA unit (modular_content)
   * Required: true
   * Id: 2665fb61-acd4-4fa2-b6c9-9e08195ffe24
   * Codename: cta
   */
  cta: Elements.LinkedItemsElement<SolutionsPageCtaModel>;

  /**
   * Related assets (modular_content)
   * Required: false
   * Id: 48c75cc5-47eb-4ed2-a88e-d13ec4c9ff03
   * Codename: related_assets
   */
  relatedAssets: Elements.LinkedItemsElement<SolutionsPageRelatedAssetModel>;
}> &
  HeroKK &
  Metadata &
  SitemapMetadata;
