import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Stat
 * Id: 917a4cd0-f230-46c6-9a0f-260dc1e5acaf
 * Codename: stat
 */
export type StatModel = IContentItem<{
  /**
   * Metric (text)
   * Required: false
   * Id: 8be412c4-2c08-4d24-b98a-d578a60eb021
   * Codename: metric
   */
  metric: Elements.TextElement;

  /**
   * Description (text)
   * Required: false
   * Id: c84d5f83-e443-4145-b391-82671df07285
   * Codename: description
   */
  description: Elements.TextElement;

  /**
   * Note (text)
   * Required: false
   * Id: d9e72281-916f-4c1a-a36e-e106c7b0e6f2
   * Codename: note
   */
  note: Elements.TextElement;

  /**
   * Link text (text)
   * Required: false
   * Id: 3f95247c-395d-42d3-bcc9-b219a44caac3
   * Codename: link_text
   */
  linkText: Elements.TextElement;

  /**
   * Link URL (text)
   * Required: false
   * Id: ab9c768d-11b6-4aef-8547-c0466024ba2d
   * Codename: link_url
   */
  linkUrl: Elements.TextElement;
}>;
