import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { SharedContentModel } from './SharedContentModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Table - Cell
 * Id: 6d67bde8-4567-4724-a086-d517d4c4356f
 * Codename: table___cell
 */
export type TableCellModel = IContentItem<{
  /**
   * Content (rich_text)
   * Required: false
   * Id: dbb7e6f8-f9f7-4931-b31f-cb7df2e6378c
   * Codename: content
   *
   * Use in case you want to display text/image in the table cell. Only use CONTENT or LINK. Never both.
   */
  content: Elements.RichTextElement;

  /**
   * Link (modular_content)
   * Required: false
   * Id: f02af199-529b-4978-b890-ad4b1cdaab44
   * Codename: link
   *
   * Use if you want to add Link to the last row of the table. Only use CONTENT or LINK. Never both.
   */
  link: Elements.LinkedItemsElement<SharedContentModel>;
}>;
