import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { TableCellModel } from './TableCellModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Table - Row
 * Id: 7221ce95-8ab3-4db4-b2a2-824ee3fbbb8b
 * Codename: table___row
 */
export type TableRowModel = IContentItem<{
  /**
   * Side Heading (rich_text)
   * Required: false
   * Id: 7d4e795f-66b7-4aaf-898d-72b8e094fb83
   * Codename: side_heading
   */
  sideHeading: Elements.RichTextElement;

  /**
   * Cells (modular_content)
   * Required: false
   * Id: e948b1bf-6f34-4bc7-af69-dc70c18b1abe
   * Codename: cells
   */
  cells: Elements.LinkedItemsElement<TableCellModel>;
}>;
