import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { TableHeadItemModel } from './TableHeadItemModel';
import { TableRowModel } from './TableRowModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Table
 * Id: 7406cb1f-24c6-4f80-9f5f-a6ec61588de0
 * Codename: table
 */
export type TableModel = IContentItem<{
  /**
   * Heading (text)
   * Required: false
   * Id: 6cd82e32-7b8a-48fc-9064-a998dce9b029
   * Codename: table_heading
   *
   * Optional heading
   */
  tableHeading: Elements.TextElement;

  /**
   * Column Headings (modular_content)
   * Required: false
   * Id: e95e61ca-769d-4b7d-a41e-856f5b4ead54
   * Codename: column_headings
   */
  columnHeadings: Elements.LinkedItemsElement<TableHeadItemModel>;

  /**
   * Table Rows (modular_content)
   * Required: false
   * Id: ced60469-638e-46ba-93a1-2e9706cc1cee
   * Codename: table_rows
   */
  tableRows: Elements.LinkedItemsElement<TableRowModel>;

  /**
   * Cell text alignment (multiple_choice)
   * Required: true
   * Id: c56be027-627b-49ab-b180-5fe8c78681fb
   * Codename: cell_text_alignment
   */
  cellTextAlignment: Elements.MultipleChoiceElement;

  /**
   * Heading text alignment (multiple_choice)
   * Required: true
   * Id: c426c356-ba7b-4842-bf01-91df63a1dd35
   * Codename: heading_text_alignment
   */
  headingTextAlignment: Elements.MultipleChoiceElement;

  /**
   * Visibility (multiple_choice)
   * Required: false
   * Id: 5a28071d-930b-4e32-843c-78d34a4362df
   * Codename: visibility
   */
  visibility: Elements.MultipleChoiceElement;
}>;
