import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Table - Head Item
 * Id: a564f8d5-6f94-4f1c-b739-5da3c5a191da
 * Codename: table___head_item
 */
export type TableHeadItemModel = IContentItem<{
  /**
   * Content (rich_text)
   * Required: false
   * Id: 8b4450cd-5ab1-4de5-9d32-2393d11b6825
   * Codename: content
   */
  content: Elements.RichTextElement;
}>;
