import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { AchievementModel } from './AchievementModel';
import { RichTestimonialModel } from './RichTestimonialModel';
import { CtaBannerComponentModel } from './CtaBannerComponentModel';
import { SitemapMetadata } from '../content-type-snippets/sitemap_metadata';
import { Metadata } from '../content-type-snippets/metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Trial page
 * Id: 18245128-2933-428d-8b86-d9bb1d08b5f1
 * Codename: trial_page
 */
export type TrialPageModel = IContentItem<{
  /**
   * Hero headline (rich_text)
   * Required: false
   * Id: 8bd7d73f-3e2c-40ae-9351-c5b561a3719a
   * Codename: hero_headline
   */
  heroHeadline: Elements.RichTextElement;

  /**
   * Hero lead paragraph (rich_text)
   * Required: false
   * Id: 063dd394-f638-4d4c-afa1-4c8c5a31c190
   * Codename: hero_lead_paragraph
   */
  heroLeadParagraph: Elements.RichTextElement;

  /**
   * Hero image (asset)
   * Required: false
   * Id: bd630f7b-eaea-4f76-8d88-9349fc20bf40
   * Codename: hero_image
   */
  heroImage: Elements.AssetsElement;

  /**
   * Form Box Title (text)
   * Required: false
   * Id: 760ead74-37ba-4dee-85fb-477bb6e2d6f6
   * Codename: form_box_title
   */
  formBoxTitle: Elements.TextElement;

  /**
   * Form CTA Title (text)
   * Required: false
   * Id: 893c459f-8012-415e-990f-e5d634a13035
   * Codename: form_cta_title
   */
  formCtaTitle: Elements.TextElement;

  /**
   * Clients headline (text)
   * Required: true
   * Id: 6406d626-d416-427a-bc3e-e1ed7f3be8ec
   * Codename: clients_headline
   */
  clientsHeadline: Elements.TextElement;

  /**
   * Logos headline (rich_text)
   * Required: true
   * Id: 70ab4e0a-e64a-4e59-bfba-e13129df682f
   * Codename: logos_headline
   */
  logosHeadline: Elements.RichTextElement;

  /**
   * Achievements headline (rich_text)
   * Required: false
   * Id: d316ac4d-3b0a-4132-9215-e5faf8996a0a
   * Codename: achievements_headline
   */
  achievementsHeadline: Elements.RichTextElement;

  /**
   * Achievements lead paragraph (rich_text)
   * Required: false
   * Id: bdb73055-f777-4cf5-83a4-2bf154d17452
   * Codename: achievements_lead_paragraph
   */
  achievementsLeadParagraph: Elements.RichTextElement;

  /**
   * Achievements list (modular_content)
   * Required: false
   * Id: 05670f7f-cad5-4eab-b6f4-e21eae433261
   * Codename: achievements_list
   */
  achievementsList: Elements.LinkedItemsElement<AchievementModel>;

  /**
   * Testimonial (modular_content)
   * Required: false
   * Id: 51e24357-d098-4cfe-93ae-63719dba9e3b
   * Codename: testimonial
   */
  testimonial: Elements.LinkedItemsElement<RichTestimonialModel>;

  /**
   * CTA Banner (modular_content)
   * Required: false
   * Id: fb7cfb20-ed1d-4c85-a234-95c0bea95411
   * Codename: cta_banner
   */
  ctaBanner: Elements.LinkedItemsElement<CtaBannerComponentModel>;
}> &
  SitemapMetadata &
  Metadata;
