import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Standalone text
 * Id: 05e5f4c7-2bd7-4998-be97-8a15c9d28955
 * Codename: umlp_element___standalone_text
 */
export type UmlpElementStandaloneTextModel = IContentItem<{
  /**
   * Text (rich_text)
   * Required: false
   * Id: 1e00fbad-3fdf-4dac-b579-53c44917a501
   * Codename: text
   */
  text: Elements.RichTextElement;
}>;
