import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { ModularItemCardElementModel } from './ModularItemCardElementModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Compare with competitor
 * Id: 572e6e5a-fcd0-415d-b4f1-dd43a0635081
 * Codename: umlp_element___compare_with_competitor
 */
export type UmlpElementCompareWithCompetitorModel = IContentItem<{
  /**
   * Heading (text)
   * Required: true
   * Id: 53660a0b-33d5-45fb-8d07-1b8da83414ce
   * Codename: heading
   */
  heading: Elements.TextElement;

  /**
   * Text (rich_text)
   * Required: false
   * Id: a349975f-f05d-42ff-91cc-3df2474b6b85
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * Tiles (modular_content)
   * Required: true
   * Id: 3f69f2fe-a8e3-4b49-998b-3f7e50d4215e
   * Codename: tiles
   */
  tiles: Elements.LinkedItemsElement<ModularItemCardElementModel>;
}>;
