import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { EnhancedContentBlockModel } from './EnhancedContentBlockModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - RoC - Intro Section
 * Id: ee4fa1d2-fc80-497d-9c56-99faf2bfce82
 * Codename: umlp_element___roc___intro_section
 */
export type UmlpElementRocIntroSectionModel = IContentItem<{
  /**
   * Content block (modular_content)
   * Required: true
   * Id: 4ffaa022-b1b1-4081-aeb9-97fc55932015
   * Codename: content_block
   */
  contentBlock: Elements.LinkedItemsElement<EnhancedContentBlockModel>;

  /**
   * Style (multiple_choice)
   * Required: true
   * Id: 1a0aaab7-8f87-4bca-a653-8cabb3edc9c7
   * Codename: pillar
   */
  pillar: Elements.MultipleChoiceElement;
}>;
