import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { ModularItemCardElementModel } from './ModularItemCardElementModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Kontent.ai Feature Showcase
 * Id: b81f15da-529d-44f4-8326-1d72af94a0fa
 * Codename: umlp_element___kontent_ai_feature_showcase
 */
export type UmlpElementKontentAiFeatureShowcaseModel = IContentItem<{
  /**
   * Heading (text)
   * Required: false
   * Id: 36b45428-1c69-4d14-a0e0-27c9ca5b0b86
   * Codename: heading
   */
  heading: Elements.TextElement;

  /**
   * Cards (modular_content)
   * Required: true
   * Id: 07f94c93-4eae-4da6-84d4-048c00b37a2d
   * Codename: cards
   */
  cards: Elements.LinkedItemsElement<ModularItemCardElementModel>;
}>;
