import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { IntegrationModel } from './IntegrationModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Integration showcase
 * Id: b4ec8d89-1f98-438c-bcd1-b348841a8414
 * Codename: umlp_element___integration_showcase
 */
export type UmlpElementIntegrationShowcaseModel = IContentItem<{
  /**
   * Heading (text)
   * Required: true
   * Id: 6dab308a-d509-404f-8e8a-b7e498b87f6c
   * Codename: heading
   */
  heading: Elements.TextElement;

  /**
   * Text (rich_text)
   * Required: true
   * Id: e92cba26-b9fc-4c62-a034-9eb4facca899
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * Integrations (modular_content)
   * Required: true
   * Id: 630ab0b0-dbce-4a1f-ab90-1f1bef022f92
   * Codename: integrations
   */
  integrations: Elements.LinkedItemsElement<IntegrationModel>;
}>;
