import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { FileModel } from './FileModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Download
 * Id: f969552e-b620-4b09-a814-99ee6435938a
 * Codename: umlp_element___download
 */
export type UmlpElementDownloadModel = IContentItem<{
  /**
   * Files (modular_content)
   * Required: true
   * Id: f26fe3aa-a6cf-44df-b4ec-f9b289115f05
   * Codename: files
   */
  files: Elements.LinkedItemsElement<FileModel>;
}>;
