import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { EnhancedContentBlockModel } from './EnhancedContentBlockModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - RoC - Pillar Customer Testimonials
 * Id: 815fd95a-b0f8-42aa-a882-0557d430e957
 * Codename: umlp_element___roc___pillar_customer_testimonials
 */
export type UmlpElementRocPillarCustomerTestimonialsModel = IContentItem<{
  /**
   * Customer testimonials (modular_content)
   * Required: true
   * Id: 43cd9244-30d3-4846-9184-204e0b4eb03c
   * Codename: customer_testimonials
   *
   * Required fields: Image, Heading, Description
   */
  customerTestimonials: Elements.LinkedItemsElement<EnhancedContentBlockModel>;

  /**
   * Style (multiple_choice)
   * Required: true
   * Id: f96deebb-43f4-4dc7-9ec6-7432929ebb05
   * Codename: style
   */
  style: Elements.MultipleChoiceElement;
}>;
