import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { SharedContentModel } from './SharedContentModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Hero Simple
 * Id: 441fea46-a441-4fd8-8261-aed93dc56cf6
 * Codename: umlp_element___hero_simple
 */
export type UmlpElementHeroSimpleModel = IContentItem<{
  /**
   * Heading (text)
   * Required: true
   * Id: 767766e2-39c5-4648-a61a-7d3824dddd07
   * Codename: heading
   */
  heading: Elements.TextElement;

  /**
   * Text (rich_text)
   * Required: false
   * Id: ca211f03-7d20-4050-91cd-f347b2714773
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * Buttons (modular_content)
   * Required: false
   * Id: 7e5702e1-1341-4d86-bdc5-627bedfada12
   * Codename: buttons
   */
  buttons: Elements.LinkedItemsElement<SharedContentModel>;
}>;
