import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { ModularItemCardElementModel } from './ModularItemCardElementModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Card columns
 * Id: e21fb565-0d40-4387-aa1d-18ee8e1d55c9
 * Codename: umlp_element___card_columns
 */
export type UmlpElementCardColumnsModel = IContentItem<{
  /**
   * Cards (modular_content)
   * Required: true
   * Id: d7b85003-6175-437d-a633-82310fa0de0d
   * Codename: cards
   */
  cards: Elements.LinkedItemsElement<ModularItemCardElementModel>;
}>;
