import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { TableModel } from './TableModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Basic Table
 * Id: 274661ce-c4b8-479e-bb3e-1de7c11dfa91
 * Codename: umlp_element___basic_table
 */
export type UmlpElementBasicTableModel = IContentItem<{
  /**
   * Heading (text)
   * Required: false
   * Id: d881c694-9a6c-486d-9831-4df38e7ac33e
   * Codename: heading
   */
  heading: Elements.TextElement;

  /**
   * Table (modular_content)
   * Required: true
   * Id: 240c121b-8392-4302-9c89-df0bf2252a78
   * Codename: table
   */
  table: Elements.LinkedItemsElement<TableModel>;
}>;
