import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Support Feature
 * Id: 48db6cf7-8ff8-496b-a470-446dacaed07f
 * Codename: umlp_element___support_feature
 */
export type UmlpElementSupportFeatureModel = IContentItem<{
  /**
   * Headline (rich_text)
   * Required: false
   * Id: 76a8cf7d-c7f8-4f52-952e-2c69a7131a47
   * Codename: headline
   */
  headline: Elements.RichTextElement;

  /**
   * Lead Paragraph (rich_text)
   * Required: false
   * Id: 5efeb109-c4c0-4147-995b-de88e2e628d9
   * Codename: lead_paragraph
   */
  leadParagraph: Elements.RichTextElement;
}>;
