import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Twitter
 * Id: 89c12e55-48e6-4e21-a390-e775fa9b60e9
 * Codename: umlp_element___twitter
 */
export type UmlpElementTwitterModel = IContentItem<{
  /**
   * Tweet ID (text)
   * Required: true
   * Id: 1d906927-6ace-40b6-a9b4-c72f7ee2057a
   * Codename: tweet_id
   */
  tweetId: Elements.TextElement;
}>;
