import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Open positions filter
 * Id: 2bf6a20e-39a0-4eb8-bf34-f72f93df842e
 * Codename: umlp_element___open_positions_filter
 */
export type UmlpElementOpenPositionsFilterModel = IContentItem<{
  /**
   * No content (text)
   * Required: false
   * Id: e94fa93f-43c8-42f7-b4a9-4b3f2d04f540
   * Codename: no_content
   *
   * This content type is only a placeholder, no content is needed/being used
   */
  noContent: Elements.TextElement;
}>;
