import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { FeaturesCategoryModel } from './FeaturesCategoryModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Content management and Dev rundown
 * Id: 10607d54-bb21-4e0d-a070-5d868bd83856
 * Codename: umlp_element___content_management_and_dev_rundown
 */
export type UmlpElementContentManagementAndDevRundownModel = IContentItem<{
  /**
   * Category (modular_content)
   * Required: true
   * Id: 14990e2c-e307-42ff-a0d5-3adbc7a99be6
   * Codename: category
   */
  category: Elements.LinkedItemsElement<FeaturesCategoryModel>;
}>;
