import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { ContentItemYoutubeVideoModel } from './ContentItemYoutubeVideoModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP Element - Video Section
 * Id: 3a7a5c8d-0084-49b1-901a-817b64c2db86
 * Codename: umlp_element___video_section
 */
export type UmlpElementVideoSectionModel = IContentItem<{
  /**
   * Heading (text)
   * Required: true
   * Id: 9ccccae7-b140-41dd-9349-83d05d52a4e6
   * Codename: heading
   */
  heading: Elements.TextElement;

  /**
   * Text (rich_text)
   * Required: true
   * Id: d4b38066-e8e0-42bf-8d3d-cc66b993bf0f
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * Video (modular_content)
   * Required: true
   * Id: 67e91af0-5c94-488d-be84-b21b5b3ef6fb
   * Codename: video
   */
  video: Elements.LinkedItemsElement<ContentItemYoutubeVideoModel>;
}>;
