import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Content flow infographic
 * Id: e8ebb641-5d18-46ac-b667-71a4f9e5ceda
 * Codename: umlp_element___content_flow_infographic
 */
export type UmlpElementContentFlowInfographicModel = IContentItem<{
  /**
   * Heading (text)
   * Required: true
   * Id: e3d29829-2ad9-4544-8ecc-3813e1f00e9b
   * Codename: heading
   */
  heading: Elements.TextElement;

  /**
   * Text (rich_text)
   * Required: true
   * Id: 24761ee6-a79c-4c78-ae71-75167b3c9103
   * Codename: text
   */
  text: Elements.RichTextElement;
}>;
