import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { BubbleModel } from './BubbleModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Plain Bubbles Grid
 * Id: 89fa0af3-1bce-4b80-9fed-29a4d2da62d0
 * Codename: umlp_element___plain_bubbles_grid
 */
export type UmlpElementPlainBubblesGridModel = IContentItem<{
  /**
   * Bubbles (modular_content)
   * Required: true
   * Id: 218000e3-4687-48ac-9f04-5467287f11cc
   * Codename: bubbles
   */
  bubbles: Elements.LinkedItemsElement<BubbleModel>;
}>;
