import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { BubbleCardModel } from './BubbleCardModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Bubble Cards
 * Id: 4e65318b-67cb-4565-a698-e4633561f949
 * Codename: umlp_element___bubble_cards
 */
export type UmlpElementBubbleCardsModel = IContentItem<{
  /**
   * Heading (text)
   * Required: false
   * Id: a54a5cf4-940e-4842-a13e-0e78b532d4df
   * Codename: heading
   *
   * Optional heading
   */
  heading: Elements.TextElement;

  /**
   * Cards (modular_content)
   * Required: true
   * Id: 782f5b9f-2000-4894-a692-b37e641f15e6
   * Codename: cards
   */
  cards: Elements.LinkedItemsElement<BubbleCardModel>;
}>;
