import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Jamstack vizualization
 * Id: 1e1571d5-d393-4ab5-9cd9-acf9e9f583f4
 * Codename: umlp_element__jamstack_vizualization
 */
export type UmlpElementJamstackVizualizationModel = IContentItem<{
  /**
   * Placeholder with no meaning (text)
   * Required: false
   * Id: 46acf389-face-4a2d-944c-3f91006ae83f
   * Codename: placeholder_with_no_meaning
   */
  placeholderWithNoMeaning: Elements.TextElement;
}>;
