import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { CtaBannerComponentModel } from './CtaBannerComponentModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - CTA Box
 * Id: 853600ee-4b48-466f-9d02-f82b2bca2d8a
 * Codename: umlp_element___cta_banner
 */
export type UmlpElementCtaBannerModel = IContentItem<{
  /**
   * Headline (rich_text)
   * Required: false
   * Id: 61606544-0b01-4654-a847-56ef4a6cd9eb
   * Codename: headline
   */
  headline: Elements.RichTextElement;

  /**
   * Lead Paragraph (rich_text)
   * Required: false
   * Id: 06a5f35e-0f1c-4406-9676-6a3d96f637f4
   * Codename: lead_paragraph
   */
  leadParagraph: Elements.RichTextElement;

  /**
   * CTA Banner (modular_content)
   * Required: false
   * Id: 88bafa1e-a56c-4934-8e62-ec43de0c38e1
   * Codename: cta_banner
   */
  ctaBanner: Elements.LinkedItemsElement<CtaBannerComponentModel>;
}>;
