import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP Element - Text/Image Block
 * Id: 740a39ae-4cd0-44b7-9f8e-f0109d0dddb8
 * Codename: umlp_element___text_image_block
 */
export type UmlpElementTextImageBlockModel = IContentItem<{
  /**
   * Image (asset)
   * Required: false
   * Id: 9f8c9e7a-8d86-4d53-b7f9-273a3a749e91
   * Codename: image
   */
  image: Elements.AssetsElement;

  /**
   * Text (rich_text)
   * Required: true
   * Id: e3600582-86d6-4579-8c60-27e39a84e83c
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * Image position (multiple_choice)
   * Required: false
   * Id: d16b3c9c-c7d4-4402-a660-95e59268c492
   * Codename: image_position
   *
   * Horizontal image position on desktop. By default, the image will be displayed on the right.
   */
  imagePosition: Elements.MultipleChoiceElement;

  /**
   * Background color (multiple_choice)
   * Required: false
   * Id: c60899f1-9b72-4264-8a6f-a820a092b547
   * Codename: background_color
   *
   * Background color of the section. The default option is white (if nothing is ticked).
   */
  backgroundColor: Elements.MultipleChoiceElement;

  /**
   * Text size (multiple_choice)
   * Required: false
   * Id: 79dbbcec-a364-4b50-9fde-b74651b1fb76
   * Codename: text_size
   *
   * Base text size. Intro => 22px. Default => 18px (if nothing is ticked)
   */
  textSize: Elements.MultipleChoiceElement;
}>;
