import { IContentItem } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - How it works scheme
 * Id: 4f87807a-a0f5-4e05-a6b4-ad9872f3f2fb
 * Codename: umlp_element___how_it_works_scheme
 */
export type UmlpElementHowItWorksSchemeModel = IContentItem<{}>;
