import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { ResourceModel } from './ResourceModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Breadcrumbs
 * Id: 50696592-da6e-47ab-8039-dd8c8a46dd51
 * Codename: umlp_element___breadcrumbs
 */
export type UmlpElementBreadcrumbsModel = IContentItem<{
  /**
   * Resource (modular_content)
   * Required: false
   * Id: 004c768a-57f0-44f3-821d-116d788a65e9
   * Codename: resource
   */
  resource: Elements.LinkedItemsElement<ResourceModel>;
}>;
