import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - RoC - Demo form
 * Id: 6cafbf21-01d2-4822-8aa6-d03aba36ced1
 * Codename: umlp_element___roc___demo_form
 */
export type UmlpElementRocDemoFormModel = IContentItem<{
  /**
   * Pardot URL (text)
   * Required: true
   * Id: ad13d6da-ca6c-4e93-99ef-92b1abfdb574
   * Codename: pardot_url
   *
   * Valid pardot URL, needs to start with "https", just "http" will not work
   */
  pardotUrl: Elements.TextElement;

  /**
   * Thank you message (rich_text)
   * Required: true
   * Id: b488df01-a4ed-476f-8e55-0ead547d7727
   * Codename: thank_you_message
   *
   * Short thank you message
   */
  thankYouMessage: Elements.RichTextElement;
}>;
