import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { SharedContentModel } from './SharedContentModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Lead
 * Id: 4f8f3267-7b8c-4b64-a80a-f7aec2644e25
 * Codename: umlp_element___lead
 */
export type UmlpElementLeadModel = IContentItem<{
  /**
   * Headline (rich_text)
   * Required: false
   * Id: ac14e19f-e8b5-4e7d-95b7-4f10733787b8
   * Codename: headline
   */
  headline: Elements.RichTextElement;

  /**
   * Lead Paragraph (rich_text)
   * Required: false
   * Id: 1d26c962-db28-411d-bbe5-60da74866fdb
   * Codename: lead_paragraph
   */
  leadParagraph: Elements.RichTextElement;

  /**
   * CTA (modular_content)
   * Required: false
   * Id: 4d4afb98-42bf-4ed0-9516-491c970f3ed3
   * Codename: cta
   *
   * Should be a link, not a button.
   */
  cta: Elements.LinkedItemsElement<SharedContentModel>;
}>;
