import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { ComponentGroupModel } from './ComponentGroupModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Element Groups
 * Id: cd546a80-b948-49c4-a675-3e5795ac6161
 * Codename: umlp_element___element_groups
 */
export type UmlpElementElementGroupsModel = IContentItem<{
  /**
   * Groups (modular_content)
   * Required: true
   * Id: 8cc773bb-d719-47af-ad2c-978468088f39
   * Codename: groups
   */
  groups: Elements.LinkedItemsElement<ComponentGroupModel>;
}>;
