import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { AchievementModel } from './AchievementModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Achievements v2
 * Id: 31afb68b-efc3-40d3-9ad5-942e17bada16
 * Codename: umlp_element___achievements_v2
 */
export type UmlpElementAchievementsV2Model = IContentItem<{
  /**
   * Heading (text)
   * Required: false
   * Id: c4338b64-7218-4a5d-9418-8d77ebe403d2
   * Codename: heading
   */
  heading: Elements.TextElement;

  /**
   * Achievements (modular_content)
   * Required: true
   * Id: f847fa6f-c540-4548-92cf-a4453d57b5da
   * Codename: achievements
   */
  achievements: Elements.LinkedItemsElement<AchievementModel>;
}>;
