import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { CaseStudyModel } from './CaseStudyModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Selected customer success stories
 * Id: 2d1eb9b2-85ea-428e-a409-7e4d2a654fc8
 * Codename: umlp_element___selected_customer_success_stories
 */
export type UmlpElementSelectedCustomerSuccessStoriesModel = IContentItem<{
  /**
   * Heading (text)
   * Required: true
   * Id: 88d6511c-f326-41de-8f5c-f4003bcfbc0a
   * Codename: heading
   */
  heading: Elements.TextElement;

  /**
   * Stories (modular_content)
   * Required: true
   * Id: e4fd5534-d9a5-48e9-9fb7-c5d2170fa13f
   * Codename: stories
   */
  stories: Elements.LinkedItemsElement<CaseStudyModel>;

  /**
   * Theme (multiple_choice)
   * Required: true
   * Id: c3b2926e-6420-46d3-9338-ecf4d4f8e835
   * Codename: theme
   */
  theme: Elements.MultipleChoiceElement;
}>;
