import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { LogoModel } from './LogoModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP Element - Logos Custom
 * Id: 5204a6b9-9229-4b0e-b9e0-418a78b7f0c9
 * Codename: umlp_element___logos_custom
 */
export type UmlpElementLogosCustomModel = IContentItem<{
  /**
   * Heading (text)
   * Required: false
   * Id: c299d3a3-1b1f-4e60-a407-e796da0867db
   * Codename: heading
   */
  heading: Elements.TextElement;

  /**
   * Logo size (multiple_choice)
   * Required: true
   * Id: a003af48-d3fd-49db-ab4f-458dbeaa0a13
   * Codename: logo_size
   */
  logoSize: Elements.MultipleChoiceElement;

  /**
   * Logos (modular_content)
   * Required: true
   * Id: fd5d5b1f-312a-4265-a9cd-b6e8ce61cdf2
   * Codename: logos
   */
  logos: Elements.LinkedItemsElement<LogoModel>;
}>;
