import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { ModularItemCardElementModel } from './ModularItemCardElementModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Cards
 * Id: 254ab330-b154-4bda-8698-d8c362adad4c
 * Codename: umlp_element___cards
 */
export type UmlpElementCardsModel = IContentItem<{
  /**
   * Heading (text)
   * Required: false
   * Id: 0d450593-1ceb-4a68-983d-27f1865ff6e2
   * Codename: heading
   *
   * Optional
   */
  heading: Elements.TextElement;

  /**
   * Cards (modular_content)
   * Required: false
   * Id: 10711737-3bef-4d52-be5c-bdd5d62737bc
   * Codename: cards
   */
  cards: Elements.LinkedItemsElement<ModularItemCardElementModel>;

  /**
   * Top indent size (multiple_choice)
   * Required: true
   * Id: f41a57c7-d067-4eb5-9bd3-edca2e9efc7d
   * Codename: top_indent_size
   *
   * Possibility to decrease top section indent, if you want to make the cards look more connected to the element above (you would probably want to omit the heading in this case as well)
   */
  topIndentSize: Elements.MultipleChoiceElement;
}>;
