import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { StatModel } from './StatModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Stat Bubbles
 * Id: 33e9abd6-fce5-4f7f-b6b8-804c2c224b90
 * Codename: umlp_element___stat_bubbles
 */
export type UmlpElementStatBubblesModel = IContentItem<{
  /**
   * Bubbles (modular_content)
   * Required: true
   * Id: 4fe41dac-d235-4b96-8f28-d2c75a95e1ab
   * Codename: bubbles
   */
  bubbles: Elements.LinkedItemsElement<StatModel>;
}>;
