import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Infographics Deliver
 * Id: 348615e3-62a5-410e-97ee-e6881558f72a
 * Codename: umlp_element___infographics_deliver
 */
export type UmlpElementInfographicsDeliverModel = IContentItem<{
  /**
   * Headline (rich_text)
   * Required: false
   * Id: cf1854f6-ba4e-432b-982a-1b385e6eda8f
   * Codename: headline
   */
  headline: Elements.RichTextElement;

  /**
   * Lead paragraph (rich_text)
   * Required: false
   * Id: db320e0b-2f56-4da6-9702-bfebf5c1a3af
   * Codename: lead_paragraph
   */
  leadParagraph: Elements.RichTextElement;

  /**
   * Type (multiple_choice)
   * Required: false
   * Id: 87fd32b2-7d21-4446-af8a-371af8c5cf3b
   * Codename: type
   */
  type: Elements.MultipleChoiceElement;
}>;
