import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Custom Tag
 * Id: 103f7767-7a11-499d-8aaa-b0d020bc734d
 * Codename: umlp_element___custom_tag
 */
export type UmlpElementCustomTagModel = IContentItem<{
  /**
   * Tag text (text)
   * Required: true
   * Id: c82f4476-9868-4524-83d3-e261a2deb0cd
   * Codename: tag_text
   */
  tagText: Elements.TextElement;
}>;
