import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { LogoModel } from './LogoModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Logo strip
 * Id: ca4ecfeb-b5db-441b-bf10-98cb821d81ca
 * Codename: umlp_element___logo_strip
 */
export type UmlpElementLogoStripModel = IContentItem<{
  /**
   * Logos (modular_content)
   * Required: true
   * Id: 051f5414-3cdd-4b65-858e-a221608aa89d
   * Codename: logos
   */
  logos: Elements.LinkedItemsElement<LogoModel>;
}>;
