import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { ProductFeatureGroupModel } from './ProductFeatureGroupModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Product roadmap
 * Id: c0b7561e-bda1-4e32-8a67-b942378a063b
 * Codename: umlp_element___product_roadmap
 */
export type UmlpElementProductRoadmapModel = IContentItem<{
  /**
   * Feature groups (modular_content)
   * Required: true
   * Id: 42980e3c-a3b5-4eca-82a6-36a9197cd1b6
   * Codename: feature_groups
   */
  featureGroups: Elements.LinkedItemsElement<ProductFeatureGroupModel>;
}>;
