import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { CaseStudyModel } from './CaseStudyModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Featured customer success stories
 * Id: b8d0b321-e62d-440b-b52a-6e0e68b6e085
 * Codename: umlp_element___featured_customer_success_stories
 */
export type UmlpElementFeaturedCustomerSuccessStoriesModel = IContentItem<{
  /**
   * Heading (text)
   * Required: false
   * Id: d2cd9955-31a5-4b33-89a4-edfee22caeb7
   * Codename: heading
   */
  heading: Elements.TextElement;

  /**
   * Success Stories (modular_content)
   * Required: true
   * Id: f736ce6a-4000-494b-ad7d-0f8c59f25f33
   * Codename: success_stories
   */
  successStories: Elements.LinkedItemsElement<CaseStudyModel>;
}>;
