import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { CodeExampleModel } from './CodeExampleModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Technology
 * Id: 95a06a92-5f17-4453-b1b7-9c43200e047c
 * Codename: umlp_element___technology
 */
export type UmlpElementTechnologyModel = IContentItem<{
  /**
   * Heading (text)
   * Required: false
   * Id: c95bca04-7aaf-4709-b0e1-d4232a28ff50
   * Codename: heading
   */
  heading: Elements.TextElement;

  /**
   * Headline (rich_text)
   * Required: false
   * Id: 0f979c0d-cfb1-473a-a007-1468aca14548
   * Codename: headline
   */
  headline: Elements.RichTextElement;

  /**
   * Lead Paragraph (rich_text)
   * Required: false
   * Id: a0785405-d8a5-4624-9f74-0cf20bf7b4a2
   * Codename: lead_paragraph
   */
  leadParagraph: Elements.RichTextElement;

  /**
   * Code Examples (modular_content)
   * Required: false
   * Id: fb9d53b7-d4d8-4e06-92f7-a1b893d7f33a
   * Codename: code_examples
   */
  codeExamples: Elements.LinkedItemsElement<CodeExampleModel>;
}>;
