import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { ContactUsKkCardModel } from './ContactUsKkCardModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * UMLP element - Contact Cards
 * Id: 4ce5ba03-0cb9-413d-9078-39a6ef16822c
 * Codename: umlp_element___contact_cards
 */
export type UmlpElementContactCardsModel = IContentItem<{
  /**
   * Cards (modular_content)
   * Required: true
   * Id: d3feb4d1-af62-4d3e-ac90-358015e48f3c
   * Codename: cards
   */
  cards: Elements.LinkedItemsElement<ContactUsKkCardModel>;
}>;
