import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Webinar/Event Topic
 * Id: dc986a8b-10ad-4e69-a5bd-a2f7e65f6491
 * Codename: webinar_event_topic
 */
export type WebinarEventTopicModel = IContentItem<{
  /**
   * Title (text)
   * Required: false
   * Id: 1cf55097-4a34-4088-8212-bf47ca30bc5c
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * URL Slug (url_slug)
   * Required: true
   * Id: ecee5cbd-5efb-4417-8721-c4dbdbfb0801
   * Codename: url_slug
   */
  urlSlug: Elements.UrlSlugElement;
}>;
