import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { SharedContentModel } from './SharedContentModel';
import { SitemapMetadata } from '../content-type-snippets/sitemap_metadata';
import { Metadata } from '../content-type-snippets/metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Webinar On-Demand
 * Id: 27247279-4e3c-422b-aaca-4c5119ca55f6
 * Codename: webinar_on_demand
 */
export type WebinarOnDemandModel = IContentItem<{
  /**
   * Title (text)
   * Required: false
   * Id: a3b55fac-7fc2-4a86-81b5-c698d6b6cd78
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Description (rich_text)
   * Required: false
   * Id: caf42949-2824-4a92-b19e-b3c9806b2fab
   * Codename: description
   */
  description: Elements.RichTextElement;

  /**
   * Header image (asset)
   * Required: false
   * Id: 97f5859e-3ee2-488d-b489-cc1a41b8f990
   * Codename: header_image
   *
   * Ideal size: 570x280
   */
  headerImage: Elements.AssetsElement;

  /**
   * Text (rich_text)
   * Required: false
   * Id: c8f2373a-5ae4-424e-a7be-f7923a143781
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * Card Title (text)
   * Required: false
   * Id: cd9e5451-8419-4395-8263-022323b25c71
   * Codename: card_title
   */
  cardTitle: Elements.TextElement;

  /**
   * CTA (modular_content)
   * Required: false
   * Id: 70a99d63-6991-4eb1-9266-abb543a0e584
   * Codename: cta
   */
  cta: Elements.LinkedItemsElement<SharedContentModel>;

  /**
   * Form Title (text)
   * Required: false
   * Id: a44ab451-1d11-4bcb-b92f-7924d8004e1f
   * Codename: form_title
   */
  formTitle: Elements.TextElement;

  /**
   * Webinar URL (text)
   * Required: false
   * Id: de8422a8-cf22-4cec-bda7-227947fc1d3e
   * Codename: webinar_url
   */
  webinarUrl: Elements.TextElement;

  /**
   * Webinar Video Poster (asset)
   * Required: false
   * Id: 6efc068a-d07a-49ba-a0d6-049166e14b63
   * Codename: webinar_video_poster
   */
  webinarVideoPoster: Elements.AssetsElement;

  /**
   * URL Slug (url_slug)
   * Required: false
   * Id: 42768864-2c74-40d9-8887-1582b19ddfd3
   * Codename: url_slug
   */
  urlSlug: Elements.UrlSlugElement;
}> &
  SitemapMetadata &
  Metadata;
