import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { AuthorModel } from './AuthorModel';
import { PartnerModel } from './PartnerModel';
import { WebinarEventTopicModel } from './WebinarEventTopicModel';
import { EventsAndWebinarsThankYouPageModel } from './EventsAndWebinarsThankYouPageModel';
import { Metadata } from '../content-type-snippets/metadata';
import { TimeZoneModel } from './TimeZoneModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Webinar
 * Id: 96b79562-0b47-422e-a5f7-1c8d49db8cf4
 * Codename: webinar
 */
export type WebinarModel = IContentItem<{
  /**
   * Title (text)
   * Required: true
   * Id: eb2c5117-1b72-4dbd-9e64-6085d14f319d
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Overview (rich_text)
   * Required: false
   * Id: 1f61a06a-d573-4cac-b213-52fac4a967bd
   * Codename: overview
   *
   * Short summary of the webinar (displayed on the webinar card)
   */
  overview: Elements.RichTextElement;

  /**
   * Description (rich_text)
   * Required: true
   * Id: c06c82ed-0a64-4ab3-8daf-89a51f0a121d
   * Codename: description
   */
  description: Elements.RichTextElement;

  /**
   * Speakers (modular_content)
   * Required: false
   * Id: e07177b2-1dab-493f-ac49-46ab6335de9f
   * Codename: speakers
   *
   * Speakers for this webinar
   */
  speakers: Elements.LinkedItemsElement<AuthorModel>;

  /**
   * Partnership (modular_content)
   * Required: false
   * Id: 00f80482-4aab-4922-8628-7bd81bcac9a0
   * Codename: partnership
   *
   * Partner for this webinar
   */
  partnership: Elements.LinkedItemsElement<PartnerModel>;

  /**
   * Wrap Up (rich_text)
   * Required: false
   * Id: 73dc028a-c74c-42f1-8a44-6b162161721b
   * Codename: wrap_up
   *
   * Post-webinar wrap-up
   */
  wrapUp: Elements.RichTextElement;

  /**
   * Subtitle (obsolete) (text)
   * Required: false
   * Id: 64cf73df-72f5-48f2-805e-efdeb77cb1f3
   * Codename: subtitle
   */
  subtitle: Elements.TextElement;

  /**
   * Topic (modular_content)
   * Required: false
   * Id: da46d3c5-2e8f-4a6d-89a7-677f6c7c4de2
   * Codename: topic
   */
  topic: Elements.LinkedItemsElement<WebinarEventTopicModel>;

  /**
   * Card image (asset)
   * Required: true
   * Id: f265c7c3-b8da-4ae7-926c-8b9383577145
   * Codename: card_image
   *
   * A smaller image used for the card on the webinars page.DISCLAIMER: If the webinar is used in the featured section at /events-and-webinars as the HORIZONTAL card - you need to use 2 images. 1st image will be used for a standard card (on smaller viewports and in the standard listing) and the 2nd image (narrower) will be used for the horizontal card.
   */
  cardImage: Elements.AssetsElement;

  /**
   * Image strip image (asset)
   * Required: false
   * Id: 6166522a-6508-4e6b-b4f4-bda97647aad4
   * Codename: image_strip_image
   *
   * Optional full-width image black and white image used on the webinar detail page.
   */
  imageStripImage: Elements.AssetsElement;

  /**
   * Hero image (asset)
   * Required: false
   * Id: cee06220-00c5-48d7-9673-fcd71f40744a
   * Codename: hero_image
   *
   * Optional hero image used on the webinar detail page with a petal (if there's no image strip). If no image strip or hero image is provided, only the petal will be shown.
   */
  heroImage: Elements.AssetsElement;

  /**
   * Recording poster (asset)
   * Required: false
   * Id: 2c7f15fe-fd81-44bb-8e61-dedb41377c98
   * Codename: recording_poster
   *
   * Poster image for the webinar video iframe. If no poster is provided, the video will be shown without a poster (default YouTube iframe behaviour).
   */
  recordingPoster: Elements.AssetsElement;

  /**
   * Registration URL (text)
   * Required: false
   * Id: da667a6d-f209-41e4-a28e-9f665692aad1
   * Codename: registration_url
   *
   * Used for attending webinars where we're not collecting registrations
   */
  registrationUrl: Elements.TextElement;

  /**
   * Recording URL (text)
   * Required: false
   * Id: e62166bb-fd4f-46cc-a80a-7dffef3ca095
   * Codename: recording_url
   *
   * URL of a webinar recording (YouTube). Use this format: https://www.youtube.com/watch?v=J3XRGtUeGXc
   */
  recordingUrl: Elements.TextElement;

  /**
   * URL Slug (url_slug)
   * Required: true
   * Id: 17dc5e59-857e-4e29-aa6f-823334f57e21
   * Codename: url_slug
   *
   * URL slug for this webinar (e.g. /content-modeling-1-on-1)
   */
  urlSlug: Elements.UrlSlugElement;

  /**
   * Previously used URL slugs (custom)
   * Required: false
   * Id: a2973439-829a-4d8d-a9de-039bfe087b8f
   * Codename: previously_used_url_slugs
   */
  previouslyUsedUrlSlugs: Elements.CustomElement;

  /**
   * Form heading (text)
   * Required: false
   * Id: 59fb4833-03fc-48dd-add4-d703a8de194e
   * Codename: form_heading
   */
  formHeading: Elements.TextElement;

  /**
   * Button text (text)
   * Required: false
   * Id: 67970d03-fb2a-4e8b-9d0c-23ef15a6c38f
   * Codename: button_text
   */
  buttonText: Elements.TextElement;

  /**
   * Thank You Page (modular_content)
   * Required: true
   * Id: 32a83716-d039-4530-8d9b-b75286676162
   * Codename: thank_you_page
   */
  thankYouPage: Elements.LinkedItemsElement<EventsAndWebinarsThankYouPageModel>;

  /**
   * Schema.org description (text)
   * Required: false
   * Id: a0a18466-0c18-4ad5-a834-83333f72e53c
   * Codename: schema_org_description
   */
  schemaOrgDescription: Elements.TextElement;

  /**
   * Schema.org performer (text)
   * Required: false
   * Id: daeabed3-7eae-4f39-ab67-d51ded3b7666
   * Codename: schema_org_performer
   */
  schemaOrgPerformer: Elements.TextElement;

  /**
   * Pardot URL (text)
   * Required: false
   * Id: b6f31231-ab8c-4668-81d2-77985f5bfedd
   * Codename: pardot_url
   *
   * Pardot iframe URL, ie. https://tracker.kontent.ai/l/849473/2020-03-04/2kny
   */
  pardotUrl: Elements.TextElement;

  /**
   * Demio event ID (text)
   * Required: false
   * Id: 0a722b36-083c-4739-a0ca-4ff2793e87aa
   * Codename: demio_event_id
   *
   * ID of the Demio event (last part of the registration URL) e.g. https://my.demio.com/ref/DLUQZzRux56aX4Jq => ID => DLUQZzRux56aX4Jq
   */
  demioEventId: Elements.TextElement;

  /**
   * Start Date and Time (date_time)
   * Required: false
   * Id: aa142aba-37a3-481d-9f0b-61e02c41437a
   * Codename: start_date_and_time
   */
  startDateAndTime: Elements.DateTimeElement;

  /**
   * End Date and Time (date_time)
   * Required: false
   * Id: 0558de30-d6b0-4781-807d-49b0b378c95c
   * Codename: end_date_and_time
   */
  endDateAndTime: Elements.DateTimeElement;

  /**
   * Time zone (modular_content)
   * Required: true
   * Id: 0a9b55bb-7f14-4794-b9f9-5f666af58974
   * Codename: time_zone
   */
  timeZone: Elements.LinkedItemsElement<TimeZoneModel>;

  /**
   * Registration open (multiple_choice)
   * Required: true
   * Id: 340d8e79-2c66-4a45-a444-561d1e494cba
   * Codename: registration_open
   */
  registrationOpen: Elements.MultipleChoiceElement;
}> &
  Metadata;
