import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { CtaBannerComponentModel } from './CtaBannerComponentModel';
import { Metadata } from '../content-type-snippets/metadata';
import { SitemapMetadata } from '../content-type-snippets/sitemap_metadata';
import { EventModel } from './EventModel';
import { WebinarModel } from './WebinarModel';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Webinars Page
 * Id: 87cee9a0-5e02-4874-9eb0-40c04037190f
 * Codename: webinars_page
 */
export type WebinarsPageModel = IContentItem<{
  /**
   * Hero Title (text)
   * Required: true
   * Id: 6c646aba-049a-4934-aff4-03780e8abaf4
   * Codename: hero_title
   */
  heroTitle: Elements.TextElement;

  /**
   * Display featured section (multiple_choice)
   * Required: true
   * Id: 64f38e08-d96a-4f23-a3a8-5f730dab1623
   * Codename: display_featured_section
   */
  displayFeaturedSection: Elements.MultipleChoiceElement;

  /**
   * CTA Banner (modular_content)
   * Required: false
   * Id: 9329fcf7-47ac-4cb4-93e6-4569421a710e
   * Codename: cta_banner
   */
  ctaBanner: Elements.LinkedItemsElement<CtaBannerComponentModel>;

  /**
   * Featured (modular_content)
   * Required: true
   * Id: ee2adb54-929f-4047-99b2-f6e81af620f4
   * Codename: featured
   *
   * Featured webinars/events
   */
  featured: Elements.LinkedItemsElement<EventModel | WebinarModel>;
}> &
  Metadata &
  SitemapMetadata;
