import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';
import { WebinarDateModel } from './WebinarDateModel';
import { Metadata } from '../content-type-snippets/metadata';

/**
 * Generated by '@kontent-ai/model-generator@5.7.0'
 *
 * Webinar Topic
 * Id: 96b79562-0b47-422e-a5f7-1c8d49db8cf4
 * Codename: webinar_topic
 */
export type WebinarTopicModel = IContentItem<{
  /**
   * Title (text)
   * Required: true
   * Id: eb2c5117-1b72-4dbd-9e64-6085d14f319d
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Subtitle (text)
   * Required: false
   * Id: 64cf73df-72f5-48f2-805e-efdeb77cb1f3
   * Codename: subtitle
   */
  subtitle: Elements.TextElement;

  /**
   * Description (rich_text)
   * Required: true
   * Id: c06c82ed-0a64-4ab3-8daf-89a51f0a121d
   * Codename: description
   */
  description: Elements.RichTextElement;

  /**
   * Header Image (asset)
   * Required: false
   * Id: 2fb6ab8f-a84e-4cbe-be8b-a011f66e18ce
   * Codename: header_image
   *
   * Ideal size: 1165x280
   */
  headerImage: Elements.AssetsElement;

  /**
   * Webinar Dates (modular_content)
   * Required: false
   * Id: 5398d8ce-72af-4c7f-b14c-3d4a70c8e57c
   * Codename: webinar_dates
   */
  webinarDates: Elements.LinkedItemsElement<WebinarDateModel>;

  /**
   * Type (multiple_choice)
   * Required: true
   * Id: bd4cc50b-8f46-4912-aef8-98f837f6397a
   * Codename: type
   */
  type: Elements.MultipleChoiceElement;

  /**
   * Sticky (multiple_choice)
   * Required: true
   * Id: d54acad4-c8e6-46ba-a180-e00ab5a86427
   * Codename: sticky
   */
  sticky: Elements.MultipleChoiceElement;

  /**
   * Schema.org description (text)
   * Required: false
   * Id: a0a18466-0c18-4ad5-a834-83333f72e53c
   * Codename: schema_org_description
   */
  schemaOrgDescription: Elements.TextElement;

  /**
   * Schema.org performer (text)
   * Required: false
   * Id: daeabed3-7eae-4f39-ab67-d51ded3b7666
   * Codename: schema_org_performer
   */
  schemaOrgPerformer: Elements.TextElement;
}> &
  Metadata;
